// @ts-check
import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock core and context globals
const mockCore = {
  info: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  summary: {
    addRaw: vi.fn().mockReturnThis(),
    write: vi.fn(),
  },
};

const mockContext = {
  repo: {
    owner: "testowner",
    repo: "testrepo",
  },
};

global.core = mockCore;
global.context = mockContext;

describe("close_expired_issues", () => {
  let mockGithub;

  beforeEach(() => {
    vi.clearAllMocks();
    delete process.env.GH_AW_DEFAULT_UTC;
    delete process.env.GITHUB_WORKSPACE;
    mockGithub = {
      graphql: vi.fn(),
      rest: {
        issues: {
          createComment: vi.fn(),
          update: vi.fn(),
        },
      },
    };
    global.github = mockGithub;
  });

  describe("main - no issues found", () => {
    it("should handle case when no issues with expiration markers exist", async () => {
      const module = await import("./close_expired_issues.cjs");

      // Mock the search query to return no issues
      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          issues: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [],
          },
        },
      });

      await module.main();

      // Verify that summary was written
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("No issues with expiration markers found"));
      expect(mockCore.summary.write).toHaveBeenCalled();
    });
  });

  describe("main - expired issue", () => {
    it("should close an expired issue", async () => {
      const module = await import("./close_expired_issues.cjs");

      // Mock the search query to return an open issue with expiration marker
      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          issues: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [
              {
                id: "issue_test123",
                number: 456,
                title: "Test Issue",
                url: "https://github.com/testowner/testrepo/issues/456",
                body: "<!-- gh-aw-workflow-id: test-workflow -->\n> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020, 9:20 AM UTC",
                createdAt: "2020-01-19T09:20:00.000Z",
              },
            ],
          },
        },
      });

      // Mock createComment and update (close issue) responses
      mockGithub.rest.issues.createComment.mockResolvedValueOnce({
        data: {
          id: 12345,
          url: "https://github.com/testowner/testrepo/issues/456#issuecomment-12345",
        },
      });

      mockGithub.rest.issues.update.mockResolvedValueOnce({
        data: {
          id: 456,
          state: "closed",
          state_reason: "not_planned",
          url: "https://github.com/testowner/testrepo/issues/456",
        },
      });

      await module.main();

      // Verify that comment was added
      expect(mockGithub.rest.issues.createComment).toHaveBeenCalledWith({
        owner: "testowner",
        repo: "testrepo",
        issue_number: 456,
        body: expect.stringContaining("automatically closed because it expired"),
      });

      // Verify that issue was closed
      expect(mockGithub.rest.issues.update).toHaveBeenCalledWith({
        owner: "testowner",
        repo: "testrepo",
        issue_number: 456,
        state: "closed",
        state_reason: "not_planned",
      });

      // Verify that success was logged
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("Successfully processed issue #456"));

      // Verify that summary was written with closed issue
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("Successfully Closed Issues"));
      expect(mockCore.summary.write).toHaveBeenCalled();
    });

    it("should format the closing comment in the configured project timezone", async () => {
      const module = await import("./close_expired_issues.cjs");
      process.env.GH_AW_DEFAULT_UTC = "-08:00";

      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          issues: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [
              {
                id: "issue_testtz",
                number: 456,
                title: "Timezone Issue",
                url: "https://github.com/testowner/testrepo/issues/456",
                body: "<!-- gh-aw-workflow-id: test-workflow -->\n> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020, 9:20 AM UTC",
                createdAt: "2020-01-19T09:20:00.000Z",
              },
            ],
          },
        },
      });

      mockGithub.rest.issues.createComment.mockResolvedValueOnce({
        data: {
          id: 12345,
          url: "https://github.com/testowner/testrepo/issues/456#issuecomment-12345",
        },
      });

      mockGithub.rest.issues.update.mockResolvedValueOnce({
        data: {
          id: 456,
          state: "closed",
          state_reason: "not_planned",
          url: "https://github.com/testowner/testrepo/issues/456",
        },
      });

      await module.main();

      const createCommentCall = mockGithub.rest.issues.createComment.mock.calls[0][0];
      expect(createCommentCall.body).toContain("This issue was automatically closed because it expired on Jan 20, 2020, 1:20 AM UTC-08:00.");
    });
  });

  describe("main - not expired issue", () => {
    it("should skip issue that is not yet expired", async () => {
      const module = await import("./close_expired_issues.cjs");

      // Mock the search query to return an open issue with future expiration
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 7); // 7 days in future

      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          issues: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [
              {
                id: "issue_test456",
                number: 789,
                title: "Future Issue",
                url: "https://github.com/testowner/testrepo/issues/789",
                body: `<!-- gh-aw-workflow-id: test-workflow -->\n> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: ${futureDate.toISOString()} --> on ${futureDate.toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" })} UTC`,
                createdAt: new Date().toISOString(),
              },
            ],
          },
        },
      });

      await module.main();

      // Verify that comment was NOT added
      expect(mockGithub.rest.issues.createComment).not.toHaveBeenCalled();

      // Verify that issue was NOT closed
      expect(mockGithub.rest.issues.update).not.toHaveBeenCalled();

      // Verify that info was logged about not expired
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("is NOT expired"));

      // Verify that summary was written with not expired issue
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("**Not yet expired**: 1 issue(s)"));
      expect(mockCore.summary.write).toHaveBeenCalled();
    });
  });

  describe("main - error handling", () => {
    it("should handle errors when closing issue", async () => {
      const module = await import("./close_expired_issues.cjs");

      // Mock the search query to return an open issue with expiration marker
      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          issues: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [
              {
                id: "issue_error123",
                number: 999,
                title: "Error Issue",
                url: "https://github.com/testowner/testrepo/issues/999",
                body: "<!-- gh-aw-workflow-id: test-workflow -->\n> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020, 9:20 AM UTC",
                createdAt: "2020-01-19T09:20:00.000Z",
              },
            ],
          },
        },
      });

      // Mock createComment to throw error
      mockGithub.rest.issues.createComment.mockRejectedValueOnce(new Error("API error"));

      await module.main();

      // Verify that error was logged
      expect(mockCore.error).toHaveBeenCalledWith(expect.stringContaining("Failed to close issue #999"));

      // Verify that summary includes failed issue
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("Failed to Close"));
      expect(mockCore.summary.write).toHaveBeenCalled();
    });
  });

  describe("main - pagination", () => {
    it("should handle paginated results", async () => {
      const module = await import("./close_expired_issues.cjs");

      // Mock the search query to return paginated results
      mockGithub.graphql
        // First page
        .mockResolvedValueOnce({
          repository: {
            issues: {
              pageInfo: {
                hasNextPage: true,
                endCursor: "cursor123",
              },
              nodes: [
                {
                  id: "issue_page1",
                  number: 100,
                  title: "Page 1 Issue",
                  url: "https://github.com/testowner/testrepo/issues/100",
                  body: "<!-- gh-aw-workflow-id: test-workflow -->\n> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020, 9:20 AM UTC",
                  createdAt: "2020-01-19T09:20:00.000Z",
                },
              ],
            },
          },
        })
        // Second page
        .mockResolvedValueOnce({
          repository: {
            issues: {
              pageInfo: {
                hasNextPage: false,
                endCursor: null,
              },
              nodes: [
                {
                  id: "issue_page2",
                  number: 200,
                  title: "Page 2 Issue",
                  url: "https://github.com/testowner/testrepo/issues/200",
                  body: "<!-- gh-aw-workflow-id: test-workflow -->\n> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020, 9:20 AM UTC",
                  createdAt: "2020-01-19T09:20:00.000Z",
                },
              ],
            },
          },
        });

      // Mock REST API calls
      mockGithub.rest.issues.createComment.mockResolvedValue({ data: { id: 1 } });
      mockGithub.rest.issues.update.mockResolvedValue({ data: { id: 1, state: "closed" } });

      await module.main();

      // Verify that GraphQL was called twice (pagination)
      expect(mockGithub.graphql).toHaveBeenCalledTimes(2);

      // Verify that both issues were processed
      expect(mockGithub.rest.issues.createComment).toHaveBeenCalledTimes(2);
      expect(mockGithub.rest.issues.update).toHaveBeenCalledTimes(2);

      // Verify that summary shows 2 issues closed
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("Successfully closed: 2 issue(s)"));
    });
  });
});
