// @ts-check
import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach } from "vitest";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe("comment_memory", () => {
  let originalPromptsDir;

  beforeAll(() => {
    originalPromptsDir = process.env.GH_AW_PROMPTS_DIR;
    process.env.GH_AW_PROMPTS_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "../md");
  });

  afterAll(() => {
    if (originalPromptsDir === undefined) {
      delete process.env.GH_AW_PROMPTS_DIR;
      return;
    }
    process.env.GH_AW_PROMPTS_DIR = originalPromptsDir;
  });

  it("sanitizes valid memory IDs", async () => {
    const module = await import("./comment_memory.cjs");
    expect(module.sanitizeMemoryID("Session_1")).toBe("Session_1");
    expect(module.sanitizeMemoryID("notes-2026")).toBe("notes-2026");
  });

  it("rejects invalid memory IDs", async () => {
    const module = await import("./comment_memory.cjs");
    expect(module.sanitizeMemoryID("bad id")).toBeNull();
    expect(module.sanitizeMemoryID("../oops")).toBeNull();
  });

  it("builds managed comment body with code-fence memory region", async () => {
    const module = await import("./comment_memory.cjs");
    const body = module.buildManagedMemoryBody("Hello world", "default", {
      includeFooter: false,
      runUrl: "https://example.com/run/1",
      workflowName: "Workflow",
      workflowSource: "",
      workflowSourceURL: "",
      historyUrl: undefined,
      triggeringIssueNumber: undefined,
      triggeringPRNumber: undefined,
    });
    expect(body).toContain("### Comment Memory");
    expect(body).toContain("``````gh-aw-comment-memory:default");
    expect(body).toContain("Hello world");
    expect(body).not.toContain('<gh-aw-comment-memory id="default">');
  });

  it("builds managed comment body with footer when enabled", async () => {
    const module = await import("./comment_memory.cjs");
    const body = module.buildManagedMemoryBody("Persist me", "session", {
      includeFooter: true,
      runUrl: "https://example.com/run/2",
      workflowName: "Workflow",
      workflowSource: "",
      workflowSourceURL: "",
      historyUrl: undefined,
      triggeringIssueNumber: 123,
      triggeringPRNumber: undefined,
    });

    expect(body).toContain("### Comment Memory");
    expect(body).toContain("``````gh-aw-comment-memory:session");
    expect(body).toContain("Persist me");
    expect(body).toContain("> [!NOTE]");
    expect(body).toContain("> It stores persistent context for this thread in the code block");
    expect(body).toContain("Generated by");
    const codeFenceIdx = body.indexOf("``````gh-aw-comment-memory:session");
    const noteIdx = body.indexOf("> [!NOTE]");
    const footerIdx = body.indexOf("Generated by");
    expect(codeFenceIdx).toBeLessThan(noteIdx);
    expect(noteIdx).toBeLessThan(footerIdx);
  });

  it("appends a configured body footer independently of the generated footer", async () => {
    const module = await import("./comment_memory.cjs");
    const body = module.buildManagedMemoryBody("Persist me", "session", {
      includeFooter: false,
      bodyFooter: "Custom footer for {workflow_name}: {run_url}",
      runUrl: "https://example.com/run/2",
      workflowName: "Workflow",
      workflowSource: "",
      workflowSourceURL: "",
      historyUrl: undefined,
      triggeringIssueNumber: undefined,
      triggeringPRNumber: undefined,
    });
    expect(body).toContain("Custom footer for Workflow: https://example.com/run/2");
    expect(body).not.toContain("Generated by");
  });

  it("throws E001 for invalid memory ID in managed body builder", async () => {
    const module = await import("./comment_memory.cjs");
    expect(() =>
      module.buildManagedMemoryBody("Persist me", "bad id", {
        includeFooter: false,
        runUrl: "https://example.com/run/3",
        workflowName: "Workflow",
        workflowSource: "",
        workflowSourceURL: "",
        historyUrl: undefined,
        triggeringIssueNumber: undefined,
        triggeringPRNumber: undefined,
      })
    ).toThrow("E001:");
  });

  it("finds only managed comments with provenance marker", async () => {
    const module = await import("./comment_memory.cjs");
    const github = {
      rest: {
        issues: {
          listComments: async () => ({
            data: [
              { id: 1, body: "``````gh-aw-comment-memory:default\nold\n``````" },
              {
                id: 2,
                body: "``````gh-aw-comment-memory:default\nmanaged\n``````\n\n<!-- gh-aw-agentic-workflow: Workflow, run: https://example.com -->",
              },
            ],
          }),
        },
      },
    };

    const found = await module.findManagedComment(github, "octo", "repo", 123, "default");
    expect(found?.id).toBe(2);
  });

  it("finds legacy xml-format managed comments with provenance marker", async () => {
    const module = await import("./comment_memory.cjs");
    const github = {
      rest: {
        issues: {
          listComments: async () => ({
            data: [
              { id: 1, body: '<gh-aw-comment-memory id="default">\nold\n</gh-aw-comment-memory>' },
              {
                id: 2,
                body: '<gh-aw-comment-memory id="default">\nmanaged\n</gh-aw-comment-memory>\n\n<!-- gh-aw-agentic-workflow: Workflow, run: https://example.com -->',
              },
            ],
          }),
        },
      },
    };

    const found = await module.findManagedComment(github, "octo", "repo", 123, "default");
    expect(found?.id).toBe(2);
  });

  describe("handler integration", () => {
    let mockCore;
    let mockGithub;
    let mockContext;
    let originalGlobals;

    beforeEach(() => {
      originalGlobals = {
        core: global.core,
        github: global.github,
        context: global.context,
      };

      mockCore = {
        debug: () => {},
        info: () => {},
        warning: () => {},
        error: () => {},
        setOutput: () => {},
        setFailed: () => {},
      };

      mockGithub = {
        rest: {
          issues: {
            listComments: async () => ({ data: [] }),
            createComment: async () => ({
              data: { id: 99, html_url: "https://github.com/owner/repo/issues/1#issuecomment-99" },
            }),
            updateComment: async () => ({
              data: { id: 99, html_url: "https://github.com/owner/repo/issues/1#issuecomment-99" },
            }),
          },
        },
      };

      mockContext = {
        eventName: "pull_request",
        runId: 1,
        repo: { owner: "owner", repo: "repo" },
        payload: { pull_request: { number: 42 } },
        serverUrl: "https://github.com",
      };

      global.core = mockCore;
      global.github = mockGithub;
      global.context = mockContext;
    });

    afterEach(() => {
      global.core = originalGlobals.core;
      global.github = originalGlobals.github;
      global.context = originalGlobals.context;
    });

    it("should skip (not fail) when target is 'triggering' but running in workflow_dispatch context", async () => {
      const commentMemoryScript = fs.readFileSync(path.join(__dirname, "comment_memory.cjs"), "utf8");

      let warningCalls = [];
      mockCore.warning = msg => {
        warningCalls.push(msg);
      };

      // workflow_dispatch has no triggering issue or PR
      mockContext.eventName = "workflow_dispatch";
      mockContext.payload = {};

      const handler = await eval(`(async () => { ${commentMemoryScript}; return await main({ target: 'triggering' }); })()`);

      const result = await handler({ type: "comment_memory", body: "Agent memory" }, {});

      // Should be skipped, not failed — workflow_dispatch has no triggering issue/PR
      expect(result.success).toBe(false);
      expect(result.skipped).toBe(true);
      expect(result.error).toContain("triggering");

      // Should have warned about the failed target resolution
      const targetWarning = warningCalls.find(msg => msg.includes("target resolution failed"));
      expect(targetWarning).toBeTruthy();
    });
  });
});
