// @ts-check
/// <reference types="@actions/github-script" />

import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock the core module
global.core = {
  info: vi.fn(),
  warning: vi.fn(),
};

const { searchEntitiesWithExpiration } = require("./expired_entity_search_helpers.cjs");

describe("searchEntitiesWithExpiration", () => {
  let mockGithub;
  const owner = "test-owner";
  const repo = "test-repo";

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("should search for issues with expiration markers", async () => {
    const mockIssue = {
      id: "issue-1",
      number: 123,
      title: "Test Issue",
      url: "https://github.com/test-owner/test-repo/issues/123",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [mockIssue],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    expect(result.items).toHaveLength(1);
    expect(result.items[0]).toEqual(mockIssue);
    expect(result.stats.pageCount).toBe(1);
    expect(result.stats.totalScanned).toBe(1);
  });

  it("should search for pull requests with expiration markers", async () => {
    const mockPR = {
      id: "pr-1",
      number: 456,
      title: "Test PR",
      url: "https://github.com/test-owner/test-repo/pull/456",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          pullRequests: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [mockPR],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "pull requests",
      graphqlField: "pullRequests",
      resultKey: "pullRequests",
    });

    expect(result.items).toHaveLength(1);
    expect(result.items[0]).toEqual(mockPR);
    expect(result.stats.pageCount).toBe(1);
    expect(result.stats.totalScanned).toBe(1);
  });

  it("should search for discussions with expiration markers", async () => {
    const mockDiscussion = {
      id: "discussion-1",
      number: 789,
      title: "Test Discussion",
      url: "https://github.com/test-owner/test-repo/discussions/789",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          discussions: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [mockDiscussion],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "discussions",
      graphqlField: "discussions",
      resultKey: "discussions",
    });

    expect(result.items).toHaveLength(1);
    expect(result.items[0]).toEqual(mockDiscussion);
    expect(result.stats.pageCount).toBe(1);
    expect(result.stats.totalScanned).toBe(1);
  });

  it("should filter out entities without agentic workflow markers", async () => {
    const agenticIssue = {
      id: "issue-1",
      number: 1,
      title: "Agentic Issue",
      url: "https://github.com/test-owner/test-repo/issues/1",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    const manualIssue = {
      id: "issue-2",
      number: 2,
      title: "Manual Issue",
      url: "https://github.com/test-owner/test-repo/issues/2",
      body: "Regular issue without agentic marker\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [agenticIssue, manualIssue],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    expect(result.items).toHaveLength(1);
    expect(result.items[0]).toEqual(agenticIssue);
    expect(result.stats.totalScanned).toBe(2);
  });

  it("should filter out entities without expiration markers", async () => {
    const withExpiration = {
      id: "issue-1",
      number: 1,
      title: "Issue with expiration",
      url: "https://github.com/test-owner/test-repo/issues/1",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    const withoutExpiration = {
      id: "issue-2",
      number: 2,
      title: "Issue without expiration",
      url: "https://github.com/test-owner/test-repo/issues/2",
      body: "> AI generated by workflow\n\nNo expiration marker\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [withExpiration, withoutExpiration],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    expect(result.items).toHaveLength(1);
    expect(result.items[0]).toEqual(withExpiration);
    expect(result.stats.totalScanned).toBe(2);
  });

  it("should find issues with legacy expiration format (without HTML comment)", async () => {
    const legacyFormatIssue = {
      id: "issue-legacy",
      number: 12667,
      title: "Legacy Format Issue",
      url: "https://github.com/test-owner/test-repo/issues/12667",
      body: "> AI generated by workflow\n\n> - [x] expires  on Jan 31, 2026, 6:04 AM UTC\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-30T04:04:42Z",
    };

    const newFormatIssue = {
      id: "issue-new",
      number: 123,
      title: "New Format Issue",
      url: "https://github.com/test-owner/test-repo/issues/123",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z --> on Dec 31, 2026, 11:59 PM UTC\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [legacyFormatIssue, newFormatIssue],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    expect(result.items).toHaveLength(2);
    expect(result.items).toContainEqual(legacyFormatIssue);
    expect(result.items).toContainEqual(newFormatIssue);
    expect(result.stats.totalScanned).toBe(2);
  });

  it("should handle pagination correctly", async () => {
    const page1Issue = {
      id: "issue-1",
      number: 1,
      title: "Issue 1",
      url: "https://github.com/test-owner/test-repo/issues/1",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    const page2Issue = {
      id: "issue-2",
      number: 2,
      title: "Issue 2",
      url: "https://github.com/test-owner/test-repo/issues/2",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi
        .fn()
        .mockResolvedValueOnce({
          repository: {
            issues: {
              pageInfo: { hasNextPage: true, endCursor: "cursor-1" },
              nodes: [page1Issue],
            },
          },
        })
        .mockResolvedValueOnce({
          repository: {
            issues: {
              pageInfo: { hasNextPage: false, endCursor: null },
              nodes: [page2Issue],
            },
          },
        }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    expect(result.items).toHaveLength(2);
    expect(result.stats.pageCount).toBe(2);
    expect(result.stats.totalScanned).toBe(2);
    expect(mockGithub.graphql).toHaveBeenCalledTimes(2);
  });

  it("should deduplicate entities when enableDedupe is true", async () => {
    const discussion = {
      id: "discussion-1",
      number: 1,
      title: "Duplicate Discussion",
      url: "https://github.com/test-owner/test-repo/discussions/1",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    // Same discussion appears on two pages (duplicate)
    mockGithub = {
      graphql: vi
        .fn()
        .mockResolvedValueOnce({
          repository: {
            discussions: {
              pageInfo: { hasNextPage: true, endCursor: "cursor-1" },
              nodes: [discussion],
            },
          },
        })
        .mockResolvedValueOnce({
          repository: {
            discussions: {
              pageInfo: { hasNextPage: false, endCursor: null },
              nodes: [discussion], // Same discussion again
            },
          },
        }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "discussions",
      graphqlField: "discussions",
      resultKey: "discussions",
      enableDedupe: true,
    });

    expect(result.items).toHaveLength(1); // Only one, not two
    expect(result.stats.pageCount).toBe(2);
    expect(result.stats.totalScanned).toBe(2);
    expect(result.stats.duplicateCount).toBe(1);
  });

  it("should not deduplicate when enableDedupe is false", async () => {
    const issue1 = {
      id: "issue-1",
      number: 1,
      title: "Issue 1",
      url: "https://github.com/test-owner/test-repo/issues/1",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    const issue2 = {
      id: "issue-1", // Same ID (unlikely in practice for issues, but testing the logic)
      number: 1,
      title: "Issue 1",
      url: "https://github.com/test-owner/test-repo/issues/1",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi
        .fn()
        .mockResolvedValueOnce({
          repository: {
            issues: {
              pageInfo: { hasNextPage: true, endCursor: "cursor-1" },
              nodes: [issue1],
            },
          },
        })
        .mockResolvedValueOnce({
          repository: {
            issues: {
              pageInfo: { hasNextPage: false, endCursor: null },
              nodes: [issue2],
            },
          },
        }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
      enableDedupe: false, // Deduplication disabled
    });

    expect(result.items).toHaveLength(2); // Both included
    expect(result.stats.pageCount).toBe(2);
    expect(result.stats.totalScanned).toBe(2);
    expect(result.stats.duplicateCount).toBeUndefined();
  });

  it("should handle empty results", async () => {
    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    expect(result.items).toHaveLength(0);
    expect(result.stats.pageCount).toBe(1);
    expect(result.stats.totalScanned).toBe(0);
  });

  it("should handle null or missing GraphQL data gracefully", async () => {
    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: null,
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    expect(result.items).toHaveLength(0);
    expect(result.stats.pageCount).toBe(1);
    expect(result.stats.totalScanned).toBe(0);
    expect(global.core.warning).toHaveBeenCalledWith("GraphQL query returned no data at page 1");
  });

  it("should log appropriate messages during search", async () => {
    const mockIssue = {
      id: "issue-1",
      number: 123,
      title: "Test Issue",
      url: "https://github.com/test-owner/test-repo/issues/123",
      body: "> AI generated by workflow\n\n> - [x] expires <!-- gh-aw-expires: 2026-12-31T23:59:59Z -->\n\n<!-- gh-aw-workflow-id: test-workflow -->",
      createdAt: "2026-01-01T00:00:00Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [mockIssue],
          },
        },
      }),
    };

    await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    expect(global.core.info).toHaveBeenCalledWith("Starting GraphQL search for open issues in test-owner/test-repo");
    expect(global.core.info).toHaveBeenCalledWith("Fetching page 1 of open issues (cursor: initial)");
    expect(global.core.info).toHaveBeenCalledWith("Page 1: Retrieved 1 open issues (total scanned: 1)");
    expect(global.core.info).toHaveBeenCalledWith(expect.stringMatching(/Found issue #123 with expiration marker \((new|legacy) format\):/));
    expect(global.core.info).toHaveBeenCalledWith("Search complete: Scanned 1 issues across 1 pages, found 1 with expiration markers");
  });

  it("should NOT find issue #12669 without XML workflow markers", async () => {
    // Issue #12669: https://github.com/github/gh-aw/issues/12669
    // This issue was not detected because it lacks XML comment markers
    // (gh-aw-workflow-id or gh-aw-agentic-workflow)
    // This is correct behavior - only issues with XML markers should be auto-closed
    const issue12669 = {
      id: "I_kwDOPc1QR87m5TZ3",
      number: 12669,
      title: "Smoke Copilot - Issue Group",
      url: "https://github.com/github/gh-aw/issues/12669",
      body: `# Smoke Copilot

Parent issue for grouping related issues from <a>Smoke Copilot</a>.



Sub-issues are automatically linked below (max 64 per parent).


> Workflow: [Smoke Copilot]()
> - [x] expires  on Jan 31, 2026, 6:05 AM UTC`,
      createdAt: "2026-01-30T04:05:02Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [issue12669],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    // This issue should NOT be found because it lacks XML workflow markers
    // Issues without markers are not managed by agentic workflows and shouldn't be auto-closed
    expect(result.items).toHaveLength(0);
    expect(result.stats.totalScanned).toBe(1);
  });

  it("should find issues with gh-aw-workflow-id XML marker", async () => {
    const issueWithWorkflowId = {
      id: "issue-with-id",
      number: 12670,
      title: "Test Issue with Workflow ID",
      url: "https://github.com/test-owner/test-repo/issues/12670",
      body: `# Test Issue

Some content here

> AI generated by [Smoke Copilot]()
> - [x] expires  on Jan 31, 2026, 6:05 AM UTC

<!-- gh-aw-workflow-id: smoke-copilot -->`,
      createdAt: "2026-01-30T04:05:02Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [issueWithWorkflowId],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    // This issue should be found because it has gh-aw-workflow-id marker
    expect(result.items).toHaveLength(1);
    expect(result.items[0]).toEqual(issueWithWorkflowId);
    expect(result.stats.totalScanned).toBe(1);
  });

  it("should find issues with gh-aw-agentic-workflow XML marker", async () => {
    const issueWithAgenticWorkflow = {
      id: "issue-with-agentic",
      number: 12671,
      title: "Test Issue with Agentic Workflow",
      url: "https://github.com/test-owner/test-repo/issues/12671",
      body: `# Test Issue

Content goes here

> AI generated by [Test Workflow](https://example.com)
> - [x] expires  on Feb 1, 2026, 10:00 AM UTC

<!-- gh-aw-agentic-workflow: Test Workflow, run: https://example.com -->`,
      createdAt: "2026-01-30T04:05:02Z",
    };

    mockGithub = {
      graphql: vi.fn().mockResolvedValue({
        repository: {
          issues: {
            pageInfo: { hasNextPage: false, endCursor: null },
            nodes: [issueWithAgenticWorkflow],
          },
        },
      }),
    };

    const result = await searchEntitiesWithExpiration(mockGithub, owner, repo, {
      entityType: "issues",
      graphqlField: "issues",
      resultKey: "issues",
    });

    // This issue should be found because it has gh-aw-agentic-workflow marker
    expect(result.items).toHaveLength(1);
    expect(result.items[0]).toEqual(issueWithAgenticWorkflow);
    expect(result.stats.totalScanned).toBe(1);
  });
});
