// @ts-check
import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock core and context globals
const mockCore = {
  info: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  summary: {
    addRaw: vi.fn().mockReturnThis(),
    write: vi.fn(),
  },
};

const mockContext = {
  repo: {
    owner: "testowner",
    repo: "testrepo",
  },
};

global.core = mockCore;
global.context = mockContext;

describe("expired_entity_main_flow", () => {
  let mockGithub;

  beforeEach(() => {
    vi.clearAllMocks();
    mockGithub = {
      graphql: vi.fn(),
      rest: {
        issues: {
          createComment: vi.fn(),
        },
      },
    };
    global.github = mockGithub;
  });

  describe("executeExpiredEntityCleanup - integration", () => {
    it("should handle no entities found scenario", async () => {
      const module = await import("./expired_entity_main_flow.cjs");

      // Mock the search query to return no entities
      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          issues: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [],
          },
        },
      });

      const config = {
        entityType: "issues",
        graphqlField: "issues",
        resultKey: "issues",
        entityLabel: "Issue",
        summaryHeading: "Expired Issues Cleanup",
        processEntity: vi.fn(),
      };

      await module.executeExpiredEntityCleanup(mockGithub, "owner", "repo", config);

      expect(mockCore.info).toHaveBeenCalledWith("Searching for expired issues in owner/repo");
      expect(mockCore.info).toHaveBeenCalledWith("No issues with expiration markers found");
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("Expired Issues Cleanup"));
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("No issues with expiration markers found"));
      expect(mockCore.summary.write).toHaveBeenCalled();
    });

    it("should handle entities found but none expired", async () => {
      const module = await import("./expired_entity_main_flow.cjs");

      // Mock the search query to return an entity that expires in the future
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 7); // 7 days in future

      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          issues: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [
              {
                id: "issue_123",
                number: 1,
                title: "Test Issue",
                url: "https://github.com/testowner/testrepo/issues/1",
                body: `<!-- gh-aw-workflow-id: test-workflow -->\n> AI generated by Test\n>\n> - [x] expires <!-- gh-aw-expires: ${futureDate.toISOString()} --> on future date`,
                createdAt: new Date().toISOString(),
              },
            ],
          },
        },
      });

      const config = {
        entityType: "issues",
        graphqlField: "issues",
        resultKey: "issues",
        entityLabel: "Issue",
        summaryHeading: "Expired Issues Cleanup",
        processEntity: vi.fn(),
      };

      await module.executeExpiredEntityCleanup(mockGithub, "owner", "repo", config);

      expect(mockCore.info).toHaveBeenCalledWith("No expired issues found");
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("**Expired**: 0 issues"));
      expect(config.processEntity).not.toHaveBeenCalled();
    });

    it("should process expired entities successfully", async () => {
      const module = await import("./expired_entity_main_flow.cjs");

      // Mock the search query to return an expired entity
      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          issues: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [
              {
                id: "issue_expired",
                number: 42,
                title: "Expired Issue",
                url: "https://github.com/testowner/testrepo/issues/42",
                body: "<!-- gh-aw-workflow-id: test -->\n> AI generated\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020",
                createdAt: "2020-01-19T09:20:00.000Z",
              },
            ],
          },
        },
      });

      mockGithub.rest.issues.createComment.mockResolvedValueOnce({ data: { id: 1 } });

      const processEntityMock = vi.fn().mockResolvedValue({
        status: "closed",
        record: { number: 42, url: "https://github.com/testowner/testrepo/issues/42", title: "Expired Issue" },
      });

      const config = {
        entityType: "issues",
        graphqlField: "issues",
        resultKey: "issues",
        entityLabel: "Issue",
        summaryHeading: "Expired Issues Cleanup",
        processEntity: processEntityMock,
      };

      await module.executeExpiredEntityCleanup(mockGithub, "owner", "repo", config);

      expect(processEntityMock).toHaveBeenCalledTimes(1);
      expect(processEntityMock).toHaveBeenCalledWith(
        expect.objectContaining({
          number: 42,
          title: "Expired Issue",
        })
      );

      expect(mockCore.info).toHaveBeenCalledWith("Successfully closed 1 expired issue(s)");
      expect(mockCore.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining("Successfully Closed Issues"));
    });

    it("should enable dedupe when configured", async () => {
      const module = await import("./expired_entity_main_flow.cjs");

      // Mock the search query to return no entities
      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          discussions: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [],
          },
        },
      });

      const config = {
        entityType: "discussions",
        graphqlField: "discussions",
        resultKey: "discussions",
        entityLabel: "Discussion",
        summaryHeading: "Expired Discussions Cleanup",
        enableDedupe: true,
        processEntity: vi.fn(),
      };

      await module.executeExpiredEntityCleanup(mockGithub, "owner", "repo", config);

      // Just verify it completes without error
      expect(mockCore.summary.write).toHaveBeenCalled();
    });
  });
});
