// @ts-check
import { describe, it, expect, beforeAll, afterEach, afterAll } from "vitest";
import { createRequire } from "module";
import path from "path";
import { fileURLToPath } from "url";

const require = createRequire(import.meta.url);
const { assembleMarkdownBodyParts } = require("./markdown_body_helpers.cjs");

describe("markdown_body_helpers", () => {
  let originalPromptsDir;

  beforeAll(() => {
    const promptsDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "../md");
    originalPromptsDir = process.env.GH_AW_PROMPTS_DIR;
    process.env.GH_AW_PROMPTS_DIR = promptsDir;
  });

  afterEach(() => {
    delete process.env.GH_AW_DETECTION_CONCLUSION;
    delete process.env.GH_AW_DETECTION_REASON;
  });

  afterAll(() => {
    if (originalPromptsDir === undefined) {
      delete process.env.GH_AW_PROMPTS_DIR;
      return;
    }
    process.env.GH_AW_PROMPTS_DIR = originalPromptsDir;
  });

  it("builds workflow-id fallback marker when footer is disabled", () => {
    const parts = assembleMarkdownBodyParts({
      includeFooter: false,
      workflowName: "Workflow",
      runUrl: "https://example.com/runs/1",
      workflowId: "test-workflow",
      markerWhenFooterDisabled: "workflow-id",
    });

    expect(parts.noFooterMarker).toBe("<!-- gh-aw-workflow-id: test-workflow -->");
    expect(parts.footer).toBe("");
  });

  it("builds XML fallback marker when footer is disabled", () => {
    const parts = assembleMarkdownBodyParts({
      includeFooter: false,
      workflowName: "Workflow",
      runUrl: "https://example.com/runs/2",
      markerWhenFooterDisabled: "xml",
    });

    expect(parts.noFooterMarker).toContain("gh-aw-agentic-workflow: Workflow");
    expect(parts.footer).toBe("");
  });

  it("includes caution once in detection warning mode while footer remains caution-free", () => {
    process.env.GH_AW_DETECTION_CONCLUSION = "warning";
    process.env.GH_AW_DETECTION_REASON = "threat_detected";

    const parts = assembleMarkdownBodyParts({
      includeFooter: true,
      workflowName: "Workflow",
      runUrl: "https://example.com/runs/3",
      workflowSource: "owner/repo/.github/workflows/test.yml@main",
      workflowSourceURL: "https://github.com/owner/repo/blob/main/.github/workflows/test.yml",
      historyUrl: "https://github.com/search?q=test",
    });

    expect(parts.detectionCaution).toContain("[!CAUTION]");
    expect(parts.footer).toContain("Generated by");
    expect(parts.footer).not.toContain("[!CAUTION]");
  });
});
