// @ts-check
/// <reference types="@actions/github-script" />

/**
 * Safe Output Type Validator
 *
 * A data-driven validation engine for safe output types.
 * Validation rules are loaded from GH_AW_VALIDATION_CONFIG environment variable,
 * which is generated by the Go compiler from the single source of truth.
 */

const { sanitizeContent } = require("./sanitize_content.cjs");
const { isTemporaryId, normalizeTemporaryId } = require("./temporary_id.cjs");
const { getErrorMessage } = require("./error_helpers.cjs");
const { unfenceMarkdown } = require("./markdown_unfencing.cjs");
const { validateValueAgainstSchema } = require("./mcp_scripts_validation.cjs");
const { resolveDataSchema } = require("./data_schema_normalizer.cjs");

/**
 * Default max body length for GitHub content
 */
const MAX_BODY_LENGTH = 65000;

/**
 * Maximum length for GitHub usernames
 * Reference: https://github.com/dead-claudia/github-limits
 */
const MAX_GITHUB_USERNAME_LENGTH = 39;
const ISSUE_INTENT_RATIONALE_MAX_LENGTH = 280;

/**
 * @typedef {{
 *   allowedAliases?: string[],
 *   maxMentions?: number,
 *   allowedAliasesSeen?: Set<string>,
 *   maxBotMentions?: number,
 *   normalizeIssueClosingKeywords?: boolean,
 *   dataEnabled?: boolean,
 *   dataSchema?: any
 * }} ValidateOptions
 */

// GitHub issue-closing keywords:
// https://docs.github.com/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
const ISSUE_CLOSING_KEYWORDS = "fix|fixes|fixed|close|closes|closed|resolve|resolves|resolved";
const ISSUE_REFERENCE_PATTERN = "(?:[a-zA-Z0-9_.-]+\\/[a-zA-Z0-9_.-]+)?#\\d+";
// eslint-disable-next-line gh-aw-custom/require-escaped-regexp-interpolation -- ISSUE_CLOSING_KEYWORDS and ISSUE_REFERENCE_PATTERN are intentional regex fragments (alternation and character classes), not user input
const ISSUE_CLOSING_WHOLE_SPAN_PATTERN = new RegExp(`\`(\\b(?:${ISSUE_CLOSING_KEYWORDS})\\b\\s+${ISSUE_REFERENCE_PATTERN})\``, "gi");
// eslint-disable-next-line gh-aw-custom/require-escaped-regexp-interpolation -- ISSUE_CLOSING_KEYWORDS and ISSUE_REFERENCE_PATTERN are intentional regex fragments (alternation and character classes), not user input
const ISSUE_CLOSING_BOTH_BACKTICK_PATTERN = new RegExp(`\`(\\b(?:${ISSUE_CLOSING_KEYWORDS})\\b)\`(\\s+)\`(${ISSUE_REFERENCE_PATTERN})\``, "gi");
// eslint-disable-next-line gh-aw-custom/require-escaped-regexp-interpolation -- ISSUE_CLOSING_KEYWORDS and ISSUE_REFERENCE_PATTERN are intentional regex fragments (alternation and character classes), not user input
const ISSUE_CLOSING_KEYWORD_BACKTICK_PATTERN = new RegExp(`\`(\\b(?:${ISSUE_CLOSING_KEYWORDS})\\b)\`(\\s+)(${ISSUE_REFERENCE_PATTERN})`, "gi");
// eslint-disable-next-line gh-aw-custom/require-escaped-regexp-interpolation -- ISSUE_CLOSING_KEYWORDS and ISSUE_REFERENCE_PATTERN are intentional regex fragments (alternation and character classes), not user input
const ISSUE_CLOSING_REFERENCE_BACKTICK_PATTERN = new RegExp(`(\\b(?:${ISSUE_CLOSING_KEYWORDS})\\b)(\\s+)\`(${ISSUE_REFERENCE_PATTERN})\``, "gi");
const NORMALIZE_CLOSER_BODY_TYPES = new Set(["create_issue", "add_comment", "create_pull_request"]);
const ISSUE_INTENT_LABEL_TYPES = new Set(["add_labels", "remove_labels", "update_issue"]);
const STRUCTURED_DATA_LABEL = "Structured data:";

/**
 * Remove markdown backticks around recognized issue-closing keyword references.
 * Only applied to body fields for configured safe output types.
 * @param {string} content
 * @returns {string}
 */
function normalizeIssueClosingKeywordBackticks(content) {
  if (typeof content !== "string" || content.length === 0) {
    return content;
  }

  // Order matters:
  // 1) whole-span backticks: `Closes #1`
  // 2) both parts backticked: `Closes` `#1`
  // 3) keyword only: `Closes` #1
  // 4) reference only: Closes `#1`
  // Each step removes one specific form without reintroducing backticks, so later steps
  // only need to handle the remaining unmatched variants.
  let normalized = content.replace(ISSUE_CLOSING_WHOLE_SPAN_PATTERN, "$1");
  normalized = normalized.replace(ISSUE_CLOSING_BOTH_BACKTICK_PATTERN, "$1$2$3");
  normalized = normalized.replace(ISSUE_CLOSING_KEYWORD_BACKTICK_PATTERN, "$1$2$3");
  return normalized.replace(ISSUE_CLOSING_REFERENCE_BACKTICK_PATTERN, "$1$2$3");
}

/**
 * Normalize issue-intent rationale text while enforcing the GitHub API hard limit.
 * sanitizeContent appends a truncation marker when it shortens content, so this
 * helper slices again to ensure the final payload never exceeds 280 characters.
 * @param {string} rationale
 * @param {ValidateOptions} [options]
 * @returns {string}
 */
function normalizeIssueIntentRationale(rationale, options) {
  const sanitizedRationale = sanitizeContent(unfenceMarkdown(rationale), {
    maxLength: ISSUE_INTENT_RATIONALE_MAX_LENGTH,
    allowedAliases: options?.allowedAliases || [],
    maxMentions: options?.maxMentions,
    allowedAliasesSeen: options?.allowedAliasesSeen,
    maxBotMentions: options?.maxBotMentions,
  }).trim();
  // sanitizeContent appends "\n[Content truncated due to length]" when it truncates,
  // so clamp again to guarantee the GitHub API hard limit.
  return sanitizedRationale.length > ISSUE_INTENT_RATIONALE_MAX_LENGTH ? sanitizedRationale.slice(0, ISSUE_INTENT_RATIONALE_MAX_LENGTH) : sanitizedRationale;
}

/**
 * Validate and normalize issue-intent-aware label arrays.
 * @param {any[]} value
 * @param {number} lineNum
 * @param {string} itemType
 * @param {string} fieldName
 * @param {ValidateOptions} [options]
 * @returns {{isValid: boolean, normalizedValue?: any[], error?: string}}
 */
function validateIssueIntentLabels(value, lineNum, itemType, fieldName, options) {
  const normalized = [];
  // Structured label validation is intentionally handled here (instead of generic field validation),
  // so optional confidence/rationale stripping is implemented inline in this code path.
  for (let i = 0; i < value.length; i++) {
    const label = value[i];
    if (typeof label === "string") {
      const name = sanitizeContent(label, {
        maxLength: 128,
        allowedAliases: options?.allowedAliases || [],
        maxMentions: options?.maxMentions,
        allowedAliasesSeen: options?.allowedAliasesSeen,
        maxBotMentions: options?.maxBotMentions,
      });
      if (!name) {
        return { isValid: false, error: `Line ${lineNum}: ${itemType} ${fieldName}[${i}] must be a non-empty string` };
      }
      normalized.push(name);
      continue;
    }

    if (!label || typeof label !== "object" || Array.isArray(label)) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} ${fieldName}[${i}] must be a string or an object with 'name'`,
      };
    }

    const keys = Object.keys(label);
    const invalidKeys = keys.filter(key => !["name", "rationale", "confidence", "suggest"].includes(key));
    if (invalidKeys.length > 0) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} ${fieldName}[${i}] contains unsupported fields: ${invalidKeys.join(", ")}`,
      };
    }
    if (typeof label.name !== "string") {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} ${fieldName}[${i}].name must be a string`,
      };
    }
    const name = sanitizeContent(label.name, {
      maxLength: 128,
      allowedAliases: options?.allowedAliases || [],
      maxMentions: options?.maxMentions,
      allowedAliasesSeen: options?.allowedAliasesSeen,
      maxBotMentions: options?.maxBotMentions,
    });
    if (!name) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} ${fieldName}[${i}].name must be a non-empty string`,
      };
    }

    /** @type {{ name: string, rationale?: string, confidence?: "LOW"|"MEDIUM"|"HIGH", suggest?: boolean }} */
    const normalizedLabel = { name };
    // Non-string rationale is silently stripped (optional enrichment field).
    if (typeof label.rationale === "string") {
      const rationale = normalizeIssueIntentRationale(label.rationale, options);
      if (rationale) {
        normalizedLabel.rationale = rationale;
      }
    }
    if (label.confidence !== undefined && label.confidence !== null && label.confidence !== "") {
      const confidenceRaw = String(label.confidence).trim().toUpperCase();
      if (confidenceRaw === "LOW" || confidenceRaw === "MEDIUM" || confidenceRaw === "HIGH") {
        normalizedLabel.confidence = confidenceRaw;
      } else {
        // Strip confidence that doesn't match enum values instead of rejecting (optional enrichment field)
      }
    }
    if (label.suggest !== undefined) {
      if (typeof label.suggest !== "boolean") {
        return {
          isValid: false,
          error: `Line ${lineNum}: ${itemType} ${fieldName}[${i}].suggest must be a boolean`,
        };
      }
      if (label.suggest) {
        normalizedLabel.suggest = true;
      }
    }
    normalized.push(normalizedLabel);
  }
  return { isValid: true, normalizedValue: normalized };
}

/**
 * @typedef {Object} FieldValidation
 * @property {boolean} [required] - Whether the field is required
 * @property {string} [type] - Expected type: 'string', 'number', 'boolean', 'array'
 * @property {string} [typeHint] - Overrides the type description in error messages (e.g. "GraphQL node ID string")
 * @property {boolean} [sanitize] - Whether to sanitize string content
 * @property {number} [maxLength] - Maximum length for strings
 * @property {number} [minLength] - Minimum length for strings
 * @property {boolean} [positiveInteger] - Must be a positive integer
 * @property {boolean} [optionalPositiveInteger] - Optional but if present must be positive integer
 * @property {boolean} [allowAuto] - Allows "auto" for optional positive integer fields
 * @property {boolean} [issueOrPRNumber] - Can be issue/PR number or undefined
 * @property {boolean} [issueNumberOrTemporaryId] - Can be issue number or temporary ID
 * @property {string[]} [enum] - Allowed values for the field
 * @property {string} [itemType] - For arrays, the type of items
 * @property {boolean} [itemSanitize] - For arrays, whether to sanitize items
 * @property {number} [itemMaxLength] - For arrays, max length per item
 * @property {string} [pattern] - Regex pattern the value must match
 * @property {string} [patternError] - Error message for pattern mismatch
 * @property {boolean} [rejectIfOversized] - When true, reject the field outright (instead of
 *   silently truncating via sanitizeContent) if the raw pre-sanitization value exceeds
 *   maxLength. Used for external-system fields (e.g. Linear) where truncation could turn an
 *   oversized/placeholder value into a deceptively short but "valid" operation.
 * @property {boolean} [x-strip-on-error] - When true, strip the field on validation failure
 *   instead of rejecting the whole item. Bracket access only (validation["x-strip-on-error"])
 *   because the key contains hyphens. Used for optional enrichment fields like confidence and rationale.
 */

/**
 * @typedef {Object} TypeValidationConfig
 * @property {number} defaultMax - Default max count for this type
 * @property {Object.<string, FieldValidation>} fields - Field validation rules
 * @property {string} [customValidation] - Custom validation rule identifier
 * @property {boolean} [dataEnabled] - Whether structured data is enabled for this type
 * @property {any} [dataSchema] - Optional schema used to validate structured data
 */

/** @type {Object.<string, TypeValidationConfig>|null} */
let cachedValidationConfig = null;

/**
 * Load validation configuration from environment variable
 * @returns {Object.<string, TypeValidationConfig>}
 */
function loadValidationConfig() {
  if (cachedValidationConfig !== null) {
    return cachedValidationConfig;
  }

  const configJson = process.env.GH_AW_VALIDATION_CONFIG;
  if (!configJson) {
    // Return empty config if not provided - validation will be skipped
    cachedValidationConfig = {};
    return cachedValidationConfig;
  }

  try {
    /** @type {Object.<string, TypeValidationConfig>} */
    const parsed = JSON.parse(configJson);
    cachedValidationConfig = parsed || {};
    return cachedValidationConfig;
  } catch (error) {
    const errorMsg = getErrorMessage(error);
    // Log as error since missing validation config is critical
    if (typeof core !== "undefined") {
      core.error(`CRITICAL: Failed to parse validation config: ${errorMsg}. Validation will be skipped.`);
    }
    cachedValidationConfig = {};
    return cachedValidationConfig;
  }
}

/**
 * Reset the cached validation config (for testing)
 */
function resetValidationConfigCache() {
  cachedValidationConfig = null;
}

/**
 * Get the default max count for a type
 * @param {string} itemType - The safe output type
 * @param {Object} [config] - Configuration override from safe-outputs config
 * @returns {number} The max allowed count
 */
function getMaxAllowedForType(itemType, config) {
  const itemConfig = config?.[itemType];
  if (itemConfig && typeof itemConfig === "object" && "max" in itemConfig && itemConfig.max) {
    return itemConfig.max;
  }
  const validationConfig = loadValidationConfig();
  const typeConfig = validationConfig[itemType];
  return typeConfig?.defaultMax ?? 1;
}

/**
 * Get the minimum required count for a type
 * @param {string} itemType - The safe output type
 * @param {Object} [config] - Configuration from safe-outputs config
 * @returns {number} The minimum required count
 */
function getMinRequiredForType(itemType, config) {
  const itemConfig = config?.[itemType];
  if (itemConfig && typeof itemConfig === "object" && "min" in itemConfig && itemConfig.min) {
    return itemConfig.min;
  }
  return 0;
}

/**
 * Validate a positive integer field
 * @param {any} value - Value to validate
 * @param {string} fieldName - Field name for error messages
 * @param {number} lineNum - Line number for error messages
 * @returns {{isValid: boolean, normalizedValue?: number, error?: string}}
 */
function validatePositiveInteger(value, fieldName, lineNum) {
  if (value === undefined || value === null) {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} is required`,
    };
  }
  if (typeof value !== "number" && typeof value !== "string") {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} must be a number or string`,
    };
  }
  const parsed = typeof value === "string" ? parseInt(value, 10) : value;
  if (Number.isNaN(parsed) || parsed <= 0 || !Number.isInteger(parsed)) {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} must be a valid positive integer (got: ${value})`,
    };
  }
  return { isValid: true, normalizedValue: parsed };
}

/**
 * Validate an optional positive integer field
 * @param {any} value - Value to validate
 * @param {string} fieldName - Field name for error messages
 * @param {number} lineNum - Line number for error messages
 * @returns {{isValid: boolean, normalizedValue?: number, error?: string}}
 */
function validateOptionalPositiveInteger(value, fieldName, lineNum) {
  if (value === undefined) {
    return { isValid: true };
  }
  if (typeof value !== "number" && typeof value !== "string") {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} must be a number or string`,
    };
  }
  const parsed = typeof value === "string" ? parseInt(value, 10) : value;
  if (Number.isNaN(parsed) || parsed <= 0 || !Number.isInteger(parsed)) {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} must be a valid positive integer (got: ${value})`,
    };
  }
  return { isValid: true, normalizedValue: parsed };
}

/**
 * Validate an optional positive integer or the "auto" sentinel.
 * @param {any} value - Value to validate
 * @param {string} fieldName - Field name for error messages
 * @param {number} lineNum - Line number for error messages
 * @returns {{isValid: boolean, normalizedValue?: number|string, error?: string}}
 */
function validateOptionalPositiveIntegerOrAuto(value, fieldName, lineNum) {
  if (value === undefined || value === null) {
    return { isValid: true };
  }
  if (typeof value === "string" && value.trim().toLowerCase() === "auto") {
    return { isValid: true, normalizedValue: "auto" };
  }
  return validateOptionalPositiveInteger(value, fieldName, lineNum);
}

/**
 * Validate an issue/PR number field (optional, accepts number or string)
 * @param {any} value - Value to validate
 * @param {string} fieldName - Field name for error messages
 * @param {number} lineNum - Line number for error messages
 * @returns {{isValid: boolean, normalizedValue?: number|string, error?: string}}
 */
function validateIssueOrPRNumber(value, fieldName, lineNum) {
  if (value === undefined) {
    return { isValid: true };
  }
  if (typeof value !== "number" && typeof value !== "string") {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} must be a number or string`,
    };
  }
  return { isValid: true, normalizedValue: value };
}

/**
 * Validate a value that can be either a positive integer (issue number) or a temporary ID.
 * @param {any} value - The value to validate
 * @param {string} fieldName - Name of the field for error messages
 * @param {number} lineNum - Line number for error messages
 * @returns {{isValid: boolean, normalizedValue?: number|string, isTemporary?: boolean, error?: string}}
 */
function validateIssueNumberOrTemporaryId(value, fieldName, lineNum) {
  if (value === undefined || value === null) {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} is required`,
    };
  }
  if (typeof value !== "number" && typeof value !== "string") {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} must be a number or string`,
    };
  }
  // Check if it's a temporary ID. Both 'aw_abc1' and '#aw_abc1' are accepted;
  // isTemporaryId handles both forms, and normalizeTemporaryId strips '#' for map keys.
  if (isTemporaryId(value)) {
    return { isValid: true, normalizedValue: `#${normalizeTemporaryId(String(value))}`, isTemporary: true };
  }
  // Try to parse as positive integer
  const parsed = typeof value === "string" ? parseInt(value, 10) : value;
  if (Number.isNaN(parsed) || parsed <= 0 || !Number.isInteger(parsed)) {
    return {
      isValid: false,
      error: `Line ${lineNum}: ${fieldName} must be a positive integer or temporary ID (got: ${value})`,
    };
  }
  return { isValid: true, normalizedValue: parsed, isTemporary: false };
}

/**
 * Validate a single field based on its validation configuration
 * @param {any} value - The field value
 * @param {string} fieldName - The field name
 * @param {FieldValidation} validation - The validation configuration
 * @param {string} itemType - The item type for error messages
 * @param {number} lineNum - Line number for error messages
 * @param {ValidateOptions} [options] - Optional sanitization options
 * @returns {{isValid: boolean, normalizedValue?: any, error?: string}}
 */
function validateField(value, fieldName, validation, itemType, lineNum, options) {
  // For positiveInteger fields, delegate required check to validatePositiveInteger
  if (validation.positiveInteger) {
    return validatePositiveInteger(value, `${itemType} '${fieldName}'`, lineNum);
  }

  // For issueNumberOrTemporaryId fields, delegate required check to validateIssueNumberOrTemporaryId
  if (validation.issueNumberOrTemporaryId) {
    // If the field is optional and not present, skip validation
    if (!validation.required && (value === undefined || value === null)) {
      return { isValid: true };
    }
    return validateIssueNumberOrTemporaryId(value, `${itemType} '${fieldName}'`, lineNum);
  }

  // Handle required check for other fields
  if (validation.required && (value === undefined || value === null)) {
    const fieldType = validation.typeHint || validation.type || "string";
    return {
      isValid: false,
      error: `Line ${lineNum}: ${itemType} requires a '${fieldName}' field (${fieldType})`,
    };
  }

  // If not required and not present, skip other validations
  if (value === undefined || value === null) {
    return { isValid: true };
  }

  // Handle optionalPositiveInteger validation
  if (validation.optionalPositiveInteger) {
    if (validation.allowAuto) {
      return validateOptionalPositiveIntegerOrAuto(value, `${itemType} '${fieldName}'`, lineNum);
    }
    return validateOptionalPositiveInteger(value, `${itemType} '${fieldName}'`, lineNum);
  }

  // Handle issueOrPRNumber validation
  if (validation.issueOrPRNumber) {
    return validateIssueOrPRNumber(value, `${itemType} '${fieldName}'`, lineNum);
  }

  if (Array.isArray(validation.type)) {
    const actualType = Array.isArray(value) ? "array" : typeof value;
    if (!validation.type.includes(actualType)) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} '${fieldName}' must be one of: ${validation.type.join(", ")}`,
      };
    }
    return { isValid: true, normalizedValue: value };
  }

  // Handle type validation
  if (validation.type === "string") {
    if (typeof value !== "string") {
      // For required fields, use "requires a" format for both missing and wrong type
      if (validation.required) {
        const fieldType = validation.typeHint || "string";
        return {
          isValid: false,
          error: `Line ${lineNum}: ${itemType} requires a '${fieldName}' field (${fieldType})`,
        };
      }
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} '${fieldName}' must be a string`,
      };
    }

    // Handle pattern validation
    if (validation.pattern) {
      const regex = new RegExp(validation.pattern);
      if (!regex.test(value.trim())) {
        const errorMsg = validation.patternError || `must match pattern ${validation.pattern}`;
        return {
          isValid: false,
          error: `Line ${lineNum}: ${itemType} '${fieldName}' ${errorMsg}`,
        };
      }
    }

    // Handle enum validation
    if (validation.enum) {
      const normalizedValue = value.toLowerCase ? value.toLowerCase() : value;
      const normalizedEnum = validation.enum.map(e => (e.toLowerCase ? e.toLowerCase() : e));
      if (!normalizedEnum.includes(normalizedValue)) {
        // Use special format for 2-option enums: "'field' must be 'A' or 'B'"
        // Use standard format for more options: "'field' must be one of: A, B, C"
        let errorMsg;
        if (validation.enum.length === 2) {
          errorMsg = `Line ${lineNum}: ${itemType} '${fieldName}' must be '${validation.enum[0]}' or '${validation.enum[1]}'`;
        } else {
          errorMsg = `Line ${lineNum}: ${itemType} '${fieldName}' must be one of: ${validation.enum.join(", ")}`;
        }
        return {
          isValid: false,
          error: errorMsg,
        };
      }
      // Return the properly cased enum value if there's a case difference
      const matchIndex = normalizedEnum.indexOf(normalizedValue);
      let normalizedResult = validation.enum[matchIndex];
      // Apply sanitization if configured
      if (validation.sanitize && validation.maxLength) {
        normalizedResult = sanitizeContent(normalizedResult, {
          maxLength: validation.maxLength,
          allowedAliases: options?.allowedAliases || [],
          maxMentions: options?.maxMentions,
          allowedAliasesSeen: options?.allowedAliasesSeen,
          maxBotMentions: options?.maxBotMentions,
        });
      }
      return { isValid: true, normalizedValue: normalizedResult };
    }

    // Reject outright (instead of silently truncating) when configured, so an oversized
    // raw value cannot be converted into a deceptively short but "valid" operation.
    if (validation.rejectIfOversized && validation.maxLength && value.length > validation.maxLength) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} '${fieldName}' exceeds maximum length (${validation.maxLength} characters)`,
      };
    }

    // Handle sanitization
    let finalValue = value;
    if (validation.sanitize) {
      // Apply unfencing to remove accidental outer markdown fences before sanitization
      finalValue = sanitizeContent(unfenceMarkdown(value), {
        maxLength: validation.maxLength || MAX_BODY_LENGTH,
        allowedAliases: options?.allowedAliases || [],
        maxMentions: options?.maxMentions,
        allowedAliasesSeen: options?.allowedAliasesSeen,
        maxBotMentions: options?.maxBotMentions,
      });
    }
    if (options?.normalizeIssueClosingKeywords && fieldName === "body" && NORMALIZE_CLOSER_BODY_TYPES.has(itemType)) {
      finalValue = normalizeIssueClosingKeywordBackticks(finalValue);
    }

    // Check minimum length after any sanitization (trim before checking to reject whitespace-padded placeholders)
    if (validation.minLength && finalValue.trim().length < validation.minLength) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} '${fieldName}' is too short (minimum ${validation.minLength} characters)`,
      };
    }

    return { isValid: true, normalizedValue: finalValue };
  }

  if (validation.type === "array") {
    // Backward compatibility: create_issue agents sometimes provide labels as a JSON array
    // or comma-separated string. Normalize either form before strict array validation.
    if (itemType === "create_issue" && fieldName === "labels" && typeof value === "string") {
      const trimmedValue = value.trim();
      if (trimmedValue.startsWith("[")) {
        try {
          const parsedValue = JSON.parse(trimmedValue);
          if (Array.isArray(parsedValue)) {
            // Filter out non-string entries from the JSON-parsed array.
            value = parsedValue.filter(item => typeof item === "string");
          }
          // Non-array JSON values (objects, primitives) fall through to comma-separated parsing.
        } catch {
          // Invalid JSON — ignored, fall back to comma-separated parsing below.
        }
      }
      if (typeof value === "string") {
        value = value
          .split(",")
          .map(item => item.trim())
          .filter(Boolean);
      }
    }

    if (!Array.isArray(value)) {
      // For required fields, use "requires a" format for both missing and wrong type
      if (validation.required) {
        return {
          isValid: false,
          error: `Line ${lineNum}: ${itemType} requires a '${fieldName}' field (array)`,
        };
      }
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} '${fieldName}' must be an array`,
      };
    }

    if (fieldName === "labels" && ISSUE_INTENT_LABEL_TYPES.has(itemType)) {
      return validateIssueIntentLabels(value, lineNum, itemType, fieldName, options);
    }

    // Validate array items
    if (validation.itemType === "string") {
      const hasInvalidItem = value.some(item => typeof item !== "string");
      if (hasInvalidItem) {
        return {
          isValid: false,
          error: `Line ${lineNum}: ${itemType} ${fieldName} array must contain only strings`,
        };
      }

      // Sanitize items if configured
      if (validation.itemSanitize) {
        const sanitizedItems = value.map(item =>
          typeof item === "string"
            ? sanitizeContent(item, {
                maxLength: validation.itemMaxLength || 128,
                allowedAliases: options?.allowedAliases || [],
                maxMentions: options?.maxMentions,
                allowedAliasesSeen: options?.allowedAliasesSeen,
                maxBotMentions: options?.maxBotMentions,
              })
            : item
        );
        return { isValid: true, normalizedValue: sanitizedItems };
      }
    }

    return { isValid: true, normalizedValue: value };
  }

  if (validation.type === "boolean") {
    if (typeof value !== "boolean") {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} '${fieldName}' must be a boolean`,
      };
    }
    return { isValid: true, normalizedValue: value };
  }

  if (validation.type === "number") {
    if (typeof value !== "number") {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} '${fieldName}' must be a number`,
      };
    }
    return { isValid: true, normalizedValue: value };
  }

  // No specific type validation, return as-is
  return { isValid: true, normalizedValue: value };
}

/**
 * Execute custom validation rules
 * @param {Object} item - The item to validate
 * @param {string} customValidation - The custom validation rule identifier
 * @param {number} lineNum - Line number for error messages
 * @param {string} itemType - The item type for error messages
 * @returns {{isValid: boolean, error?: string}|null}
 */
function executeCustomValidation(item, customValidation, lineNum, itemType) {
  if (!customValidation) {
    return null;
  }

  // Parse custom validation rule
  if (customValidation.startsWith("requiresOneOf:")) {
    const fields = customValidation.slice("requiresOneOf:".length).split(",");
    const hasValidField = fields.some(field => item[field] !== undefined && item[field] !== false);
    if (!hasValidField) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} requires at least one of: ${fields.map(f => `'${f}'`).join(", ")} fields`,
      };
    }
  }

  if (customValidation === "startLineLessOrEqualLine") {
    if (item.start_line !== undefined && item.line !== undefined) {
      const startLine = typeof item.start_line === "string" ? parseInt(item.start_line, 10) : item.start_line;
      const endLine = typeof item.line === "string" ? parseInt(item.line, 10) : item.line;
      if (startLine > endLine) {
        return {
          isValid: false,
          error: `Line ${lineNum}: ${itemType} 'start_line' must be less than or equal to 'line'`,
        };
      }
    }
  }

  if (customValidation === "parentAndSubDifferent") {
    // Normalize values for comparison
    const normalizeValue = v => (typeof v === "string" ? v.toLowerCase() : v);
    if (normalizeValue(item.parent_issue_number) === normalizeValue(item.sub_issue_number)) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} 'parent_issue_number' and 'sub_issue_number' must be different`,
      };
    }
  }

  return null;
}

/**
 * Validate a safe output item against its type configuration
 * @param {Object} item - The item to validate
 * @param {string} itemType - The item type (e.g., "create_issue")
 * @param {number} lineNum - Line number for error messages
 * @param {ValidateOptions} [options] - Optional sanitization options
 * @returns {{isValid: boolean, normalizedItem?: Object, error?: string}}
 */
function validateItem(item, itemType, lineNum, options) {
  const validationConfig = loadValidationConfig();
  const typeConfig = validationConfig[itemType];

  if (!typeConfig) {
    // Unknown type - let the caller handle this
    return { isValid: true, normalizedItem: item };
  }

  // Build the downstream payload from the declared contract. The raw item is
  // agent-controlled, so forwarding undeclared fields would let consumers act
  // on values that were never validated.
  const normalizedItem = { type: item.type };
  const errors = [];

  // Run custom validation first if defined
  if (typeConfig.customValidation) {
    const customResult = executeCustomValidation(item, typeConfig.customValidation, lineNum, itemType);
    if (customResult && !customResult.isValid) {
      return customResult;
    }
  }

  // Share mention state across every sanitized field in this output item.
  const validationOptions = { ...options, allowedAliasesSeen: new Set() };

  // Validate each configured field
  for (const [fieldName, validation] of Object.entries(typeConfig.fields)) {
    const fieldValue = item[fieldName];
    const result = validateField(fieldValue, fieldName, validation, itemType, lineNum, validationOptions);

    if (!result.isValid) {
      // When x-strip-on-error is set, strip the invalid optional field instead of rejecting the item.
      // This is used for enrichment-only fields like confidence and rationale.
      if (validation["x-strip-on-error"] && !validation.required) {
        delete normalizedItem[fieldName];
      } else {
        errors.push(result.error);
      }
    } else if (result.normalizedValue !== undefined) {
      normalizedItem[fieldName] = result.normalizedValue;
    } else if (fieldValue !== undefined) {
      let validationKind = Object.keys(validation).sort().join(",") || "unspecified";
      if (validation.type) {
        const validationType = Array.isArray(validation.type) ? validation.type.join("|") : validation.type;
        validationKind = `type=${validationType}`;
      }
      const fieldValueType = Array.isArray(fieldValue) ? "array" : typeof fieldValue;
      errors.push(`Line ${lineNum}: ${itemType} '${fieldName}' validation (${validationKind}) accepted ${fieldValueType} but did not produce a normalized value`);
    }
  }

  if (errors.length > 0) {
    return { isValid: false, error: errors[0] }; // Return first error
  }

  if (item.data !== undefined) {
    const runtimeDataSchema = options?.dataSchema;
    const runtimeDataEnabled = options?.dataEnabled === true || runtimeDataSchema !== undefined;
    const configDataEnabled = typeConfig.dataEnabled === true || typeConfig.dataSchema !== undefined;
    const dataEnabled = runtimeDataEnabled || configDataEnabled;
    if (!dataEnabled) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} 'data' is not enabled (set safe-outputs.data in workflow frontmatter)`,
      };
    }
    if (!item.data || typeof item.data !== "object" || Array.isArray(item.data)) {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} 'data' must be an object`,
      };
    }

    let dataJSON;
    let normalizedData;
    try {
      dataJSON = JSON.stringify(item.data, null, 2);
      normalizedData = JSON.parse(dataJSON);
    } catch {
      return {
        isValid: false,
        error: `Line ${lineNum}: ${itemType} 'data' must be JSON-serializable`,
      };
    }

    // Preserve normalized data on the item for downstream automation.
    normalizedItem.data = normalizedData;

    const schemaSource = runtimeDataSchema !== undefined ? runtimeDataSchema : typeConfig.dataSchema;
    if (schemaSource !== undefined) {
      let dataSchema;
      try {
        dataSchema = resolveDataSchema(schemaSource, `safe-outputs.${itemType}.data`);
      } catch (error) {
        return {
          isValid: false,
          error: `Line ${lineNum}: ${itemType} 'data' schema is invalid: ${getErrorMessage(error)}`,
        };
      }
      const dataSchemaError = validateValueAgainstSchema(normalizedData, dataSchema);
      if (dataSchemaError) {
        const errorPath = dataSchemaError.path ? `.${dataSchemaError.path}` : "";
        return {
          isValid: false,
          error: `Line ${lineNum}: ${itemType} 'data'${errorPath} ${dataSchemaError.message}`,
        };
      }
    }

    // If this safe-output type supports a body field, append structured data
    // as fenced JSON so it survives body sanitization.
    if (Object.prototype.hasOwnProperty.call(typeConfig.fields, "body")) {
      const dataBlock = `${STRUCTURED_DATA_LABEL}\n\`\`\`json\n${dataJSON}\n\`\`\``;
      if (typeof normalizedItem.body === "string" && normalizedItem.body.length > 0) {
        normalizedItem.body = `${normalizedItem.body}\n\n${dataBlock}`;
      } else {
        normalizedItem.body = dataBlock;
      }
    }
  }

  return { isValid: true, normalizedItem };
}

/**
 * Check if a type has validation configuration
 * @param {string} itemType - The item type
 * @returns {boolean}
 */
function hasValidationConfig(itemType) {
  const validationConfig = loadValidationConfig();
  return itemType in validationConfig;
}

/**
 * Get the validation configuration for a type
 * @param {string} itemType - The item type
 * @returns {TypeValidationConfig|undefined}
 */
function getValidationConfig(itemType) {
  const validationConfig = loadValidationConfig();
  return validationConfig[itemType];
}

/**
 * Get all known safe output types
 * @returns {string[]}
 */
function getKnownTypes() {
  const validationConfig = loadValidationConfig();
  return Object.keys(validationConfig);
}

module.exports = {
  // Main validation functions
  validateItem,
  validateField,
  validatePositiveInteger,
  validateOptionalPositiveInteger,
  validateOptionalPositiveIntegerOrAuto,
  validateIssueOrPRNumber,
  validateIssueNumberOrTemporaryId,

  // Configuration accessors
  loadValidationConfig,
  resetValidationConfigCache,
  getMaxAllowedForType,
  getMinRequiredForType,
  hasValidationConfig,
  getValidationConfig,
  getKnownTypes,

  // Constants
  MAX_BODY_LENGTH,
  MAX_GITHUB_USERNAME_LENGTH,
};
