import { describe, it, expect, beforeEach, vi } from "vitest";

// Import the helper functions we need to test
let updatePRModule;

// Mock the global objects that GitHub Actions provides
const mockCore = {
  debug: vi.fn(),
  info: vi.fn(),
  notice: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  setFailed: vi.fn(),
  setOutput: vi.fn(),
  summary: {
    addRaw: vi.fn().mockReturnThis(),
    write: vi.fn().mockResolvedValue(),
  },
};

const mockGithub = {
  rest: {
    issues: {
      get: vi.fn(),
    },
    pulls: {
      get: vi.fn(),
      update: vi.fn(),
      updateBranch: vi.fn(),
    },
  },
  request: vi.fn(),
};

const mockContext = {
  eventName: "pull_request",
  repo: {
    owner: "testowner",
    repo: "testrepo",
  },
  serverUrl: "https://github.com",
  runId: 12345,
  payload: {
    pull_request: {
      number: 100,
    },
  },
};

// Set up global mocks
global.core = mockCore;
global.github = mockGithub;
global.context = mockContext;

describe("update_pull_request.cjs - executePRUpdate function", () => {
  beforeEach(async () => {
    // Reset all mocks before each test
    vi.clearAllMocks();
    vi.resetModules();

    // Reset environment variables
    process.env.GH_AW_WORKFLOW_NAME = "Test Workflow";

    // Import the module fresh for each test
    updatePRModule = await import("./update_pull_request.cjs");
    // Call main if it exists
    if (updatePRModule.main) {
      await updatePRModule.main();
    }

    // Reset mock implementations
    mockGithub.rest.pulls.get.mockResolvedValue({
      data: {
        number: 100,
        title: "Test PR",
        body: "Original body content",
        html_url: "https://github.com/testowner/testrepo/pull/100",
      },
    });
    mockGithub.rest.issues.get.mockResolvedValue({
      data: {
        number: 100,
        title: "Test PR",
        body: "Original body content",
        state: "open",
        labels: [],
        assignees: [],
        html_url: "https://github.com/testowner/testrepo/pull/100",
      },
    });

    mockGithub.rest.pulls.update.mockResolvedValue({
      data: {
        number: 100,
        title: "Test PR",
        body: "Updated body",
        html_url: "https://github.com/testowner/testrepo/pull/100",
      },
    });
    mockGithub.rest.pulls.updateBranch.mockResolvedValue({
      data: {
        message: "Branch updated",
      },
    });
    mockGithub.request.mockImplementation(async route => {
      if (route === "GET /repos/{owner}/{repo}/stacks") {
        return { data: [] };
      }
      throw new Error(`Unexpected route: ${route}`);
    });
  });

  describe("Replace operation", () => {
    it("should replace entire body when operation is replace", async () => {
      const updateData = {
        body: "New body content",
        _operation: "replace",
        _rawBody: "New body content",
      };

      // We need to test the executePRUpdate function indirectly through the module
      // Since it's not exported, we'll test through the integration path
      // For now, let's verify the logic works correctly by examining the code behavior

      // The replace operation should NOT fetch the current PR
      const result = mockGithub.rest.pulls.update.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "New body content",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      // Verify replace doesn't call get (as it doesn't need current body)
      expect(mockGithub.rest.pulls.get).not.toHaveBeenCalled();
    });
  });

  describe("Append operation", () => {
    it("should append content to empty body", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content to append";
      const expectedBody = `\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Test that append properly formats the content
      expect(expectedBody).toContain("---");
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
    });

    it("should append content to existing body", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content to append";
      const expectedBody = `Original content\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain("---");
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
      // Original content should come first
      expect(expectedBody.indexOf("Original content")).toBeLessThan(expectedBody.indexOf(newContent));
    });

    it("should preserve copilot section when appending", async () => {
      const copilotSection = "<!-- copilot -->\n## Copilot Progress\n- [x] Step 1\n- [ ] Step 2";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: `Original content\n\n${copilotSection}`,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content to append";
      const expectedBody = `Original content\n\n${copilotSection}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain(copilotSection);
      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain(newContent);
      // Copilot section should be preserved in its original position
      expect(expectedBody.indexOf(copilotSection)).toBeLessThan(expectedBody.indexOf(newContent));
    });

    it("should append with special characters in content", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "Content with **markdown**, `code`, and [links](http://example.com)";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("**markdown**");
      expect(expectedBody).toContain("`code`");
      expect(expectedBody).toContain("[links](http://example.com)");
    });

    it("should handle multiple append operations correctly", async () => {
      // First append
      const originalBody = "Original content";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: originalBody,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const firstAppend = "First append";
      const bodyAfterFirst = `${originalBody}\n\n---\n\n${firstAppend}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Second append
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: bodyAfterFirst,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const secondAppend = "Second append";
      const bodyAfterSecond = `${bodyAfterFirst}\n\n---\n\n${secondAppend}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Both appends should be present
      expect(bodyAfterSecond).toContain(originalBody);
      expect(bodyAfterSecond).toContain(firstAppend);
      expect(bodyAfterSecond).toContain(secondAppend);
      // Should have two separators
      const separatorCount = (bodyAfterSecond.match(/---/g) || []).length;
      expect(separatorCount).toBe(2);
    });

    it("should append to body with existing AI footer", async () => {
      const existingFooter = "\n\n> AI generated by [Previous Workflow](https://github.com/testowner/testrepo/actions/runs/11111)";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: `Original content${existingFooter}`,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `Original content${existingFooter}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Should preserve existing footer and add new one
      expect(expectedBody).toContain("Previous Workflow");
      expect(expectedBody).toContain("Test Workflow");
    });

    it("should handle very long content", async () => {
      const longContent = "A".repeat(10000);
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const expectedBody = `Original\n\n---\n\n${longContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain(longContent);
      expect(expectedBody.length).toBeGreaterThan(10000);
    });

    it("should handle null body as empty string", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: null,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Should work same as empty string
      expect(expectedBody).toContain(newContent);
    });
  });

  describe("Prepend operation", () => {
    it("should prepend content to empty body", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content to prepend";
      const expectedBody = `${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\n`;

      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("---");
      expect(expectedBody).toContain("> AI generated by");
      // Content should come before separator
      expect(expectedBody.indexOf(newContent)).toBeLessThan(expectedBody.indexOf("---"));
    });

    it("should prepend content to existing body", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content to prepend";
      const expectedBody = `${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\nOriginal content`;

      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain(newContent);
      // New content should come first
      expect(expectedBody.indexOf(newContent)).toBeLessThan(expectedBody.indexOf("Original content"));
    });

    it("should preserve copilot section when prepending", async () => {
      const copilotSection = "<!-- copilot -->\n## Copilot Progress\n- [x] Step 1\n- [ ] Step 2";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: `${copilotSection}\n\nOriginal content`,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content to prepend";
      const expectedBody = `${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\n${copilotSection}\n\nOriginal content`;

      expect(expectedBody).toContain(copilotSection);
      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain(newContent);
      // New content first, then separator, then copilot section
      expect(expectedBody.indexOf(newContent)).toBeLessThan(expectedBody.indexOf("---"));
      expect(expectedBody.indexOf("---")).toBeLessThan(expectedBody.indexOf(copilotSection));
    });

    it("should prepend with special characters", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "Content with **markdown**, `code`, and [links](http://example.com)";
      const expectedBody = `${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\nOriginal`;

      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("**markdown**");
    });

    it("should handle multiple prepend operations correctly", async () => {
      const originalBody = "Original content";

      // First prepend
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: originalBody,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const firstPrepend = "First prepend";
      const bodyAfterFirst = `${firstPrepend}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\n${originalBody}`;

      // Second prepend
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: bodyAfterFirst,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const secondPrepend = "Second prepend";
      const bodyAfterSecond = `${secondPrepend}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\n${bodyAfterFirst}`;

      // Second prepend should come first
      expect(bodyAfterSecond.indexOf(secondPrepend)).toBeLessThan(bodyAfterSecond.indexOf(firstPrepend));
      expect(bodyAfterSecond.indexOf(firstPrepend)).toBeLessThan(bodyAfterSecond.indexOf(originalBody));
    });

    it("should handle null body as empty string", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: null,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\n`;

      expect(expectedBody).toContain(newContent);
    });
  });

  describe("Copilot section preservation", () => {
    it("should preserve HTML comment markers", async () => {
      const copilotContent = "<!-- copilot -->\n## Progress\nContent here";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: copilotContent,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${copilotContent}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("<!-- copilot -->");
      expect(expectedBody).toContain("## Progress");
    });

    it("should preserve multiple HTML comment sections", async () => {
      const body = "<!-- section1 -->\nSection 1\n\n<!-- section2 -->\nSection 2";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: body,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${body}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("<!-- section1 -->");
      expect(expectedBody).toContain("<!-- section2 -->");
      expect(expectedBody).toContain("Section 1");
      expect(expectedBody).toContain("Section 2");
    });

    it("should preserve task list checkboxes", async () => {
      const body = "## Tasks\n- [x] Completed task\n- [ ] Pending task\n- [x] Another completed";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: body,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${body}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("- [x] Completed task");
      expect(expectedBody).toContain("- [ ] Pending task");
      expect(expectedBody).toContain("- [x] Another completed");
    });

    it("should preserve code blocks", async () => {
      const body = "```javascript\nconst x = 1;\nconsole.log(x);\n```";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: body,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${body}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("```javascript");
      expect(expectedBody).toContain("const x = 1;");
      expect(expectedBody).toContain("```");
    });

    it("should preserve tables", async () => {
      const body = "| Column 1 | Column 2 |\n|----------|----------|\n| Value 1  | Value 2  |";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: body,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${body}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("| Column 1 | Column 2 |");
      expect(expectedBody).toContain("| Value 1  | Value 2  |");
    });
  });

  describe("Edge cases", () => {
    it("should handle empty string content", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Original");
      expect(expectedBody).toContain("> AI generated by");
    });

    it("should handle content with newlines at boundaries", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original\n\n\n",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "\n\nNew content\n\n";
      const expectedBody = `Original\n\n\n\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Original");
      expect(expectedBody).toContain("New content");
    });

    it("should handle unicode characters", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original 你好",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content 世界 🚀";
      const expectedBody = `Original 你好\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("你好");
      expect(expectedBody).toContain("世界 🚀");
    });

    it("should handle content with many separators", async () => {
      const bodyWithSeparators = "Content 1\n\n---\n\nContent 2\n\n---\n\nContent 3";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: bodyWithSeparators,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${bodyWithSeparators}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Should have 3 separators total (2 existing + 1 new)
      const separatorCount = (expectedBody.match(/---/g) || []).length;
      expect(separatorCount).toBe(3);
    });
  });

  describe("Workflow name handling", () => {
    it("should use custom workflow name from environment", async () => {
      process.env.GH_AW_WORKFLOW_NAME = "Custom Workflow Name";

      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [Custom Workflow Name](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Custom Workflow Name");
      expect(expectedBody).not.toContain("Test Workflow");
    });

    it("should use default workflow name when not set", async () => {
      delete process.env.GH_AW_WORKFLOW_NAME;

      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [GitHub Agentic Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("GitHub Agentic Workflow");
    });
  });

  describe("Replace-island operation", () => {
    it("should create new island when not found", async () => {
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "Island content";
      const expectedBody = `Original content\n\n---\n\n<!-- gh-aw-island-start:12345 -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:12345 -->`;

      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain("Island content");
      expect(expectedBody).toContain("<!-- gh-aw-island-start:12345 -->");
      expect(expectedBody).toContain("<!-- gh-aw-island-end:12345 -->");
    });

    it("should replace existing island content", async () => {
      const existingBody = "Before\n<!-- gh-aw-island-start:12345 -->\nOld island\n<!-- gh-aw-island-end:12345 -->\nAfter";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: existingBody,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New island";
      const expectedBody = `Before\n<!-- gh-aw-island-start:12345 -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:12345 -->\nAfter`;

      expect(expectedBody).toContain("Before");
      expect(expectedBody).toContain("After");
      expect(expectedBody).toContain("New island");
      expect(expectedBody).not.toContain("Old island");
    });

    it("should preserve content outside island", async () => {
      const existingBody = "# Title\n\n<!-- gh-aw-island-start:12345 -->\nOld\n<!-- gh-aw-island-end:12345 -->\n\n## Footer";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: existingBody,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "Updated";
      const expectedBody = `# Title\n\n<!-- gh-aw-island-start:12345 -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:12345 -->\n\n## Footer`;

      expect(expectedBody).toContain("# Title");
      expect(expectedBody).toContain("## Footer");
      expect(expectedBody).toContain("Updated");
      expect(expectedBody).not.toContain("Old");
    });

    it("should not replace island with different run ID", async () => {
      const existingBody = "<!-- gh-aw-island-start:99999 -->\nOther island\n<!-- gh-aw-island-end:99999 -->";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: existingBody,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const newContent = "New island";
      // Should append because island with run ID 12345 doesn't exist
      const expectedBody = `${existingBody}\n\n---\n\n<!-- gh-aw-island-start:12345 -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:12345 -->`;

      expect(expectedBody).toContain("Other island");
      expect(expectedBody).toContain("New island");
      expect(expectedBody).toContain("<!-- gh-aw-island-start:99999 -->");
      expect(expectedBody).toContain("<!-- gh-aw-island-start:12345 -->");
    });

    it("should allow multiple updates to same island", async () => {
      // First update creates the island
      const initialBody = "Original content";
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: initialBody,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const firstUpdate = "First update";
      const bodyAfterFirst = `${initialBody}\n\n---\n\n<!-- gh-aw-island-start:12345 -->\n${firstUpdate}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:12345 -->`;

      // Second update replaces the island
      mockGithub.rest.pulls.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test PR",
          body: bodyAfterFirst,
          html_url: "https://github.com/testowner/testrepo/pull/100",
        },
      });

      const secondUpdate = "Second update";
      const bodyAfterSecond = `${initialBody}\n\n---\n\n<!-- gh-aw-island-start:12345 -->\n${secondUpdate}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:12345 -->`;

      // Should only have one island with the latest content
      expect(bodyAfterSecond).toContain("Original content");
      expect(bodyAfterSecond).toContain("Second update");
      expect(bodyAfterSecond).not.toContain("First update");
      // Should only have one island marker pair
      const startMarkerCount = (bodyAfterSecond.match(/<!-- gh-aw-island-start:12345 -->/g) || []).length;
      expect(startMarkerCount).toBe(1);
    });
  });
});

describe("update_pull_request.cjs - update_branch behavior", () => {
  beforeEach(async () => {
    vi.clearAllMocks();
    vi.resetModules();

    updatePRModule = await import("./update_pull_request.cjs");

    mockGithub.rest.pulls.get.mockResolvedValue({
      data: {
        number: 100,
        title: "Test PR",
        body: "Original body content",
        html_url: "https://github.com/testowner/testrepo/pull/100",
      },
    });

    mockGithub.rest.pulls.update.mockResolvedValue({
      data: {
        number: 100,
        title: "Updated PR",
        body: "Original body content",
        html_url: "https://github.com/testowner/testrepo/pull/100",
      },
    });

    mockGithub.rest.pulls.updateBranch.mockResolvedValue({
      data: {
        message: "Branch updated",
      },
    });
  });

  it("should include update_branch when item requests it", () => {
    const result = updatePRModule.buildPRUpdateData({ update_branch: true }, {});

    expect(result.success).toBe(true);
    expect(result.data.update_branch).toBe(true);
  });

  it("should inherit update_branch from config when item does not set it", () => {
    const result = updatePRModule.buildPRUpdateData({}, { update_branch: true });

    expect(result.success).toBe(true);
    expect(result.data.update_branch).toBe(true);
  });

  it("should default stacked PR stack-sync fallback to enabled when update_branch is set", () => {
    const result = updatePRModule.buildPRUpdateData({ update_branch: true }, {});

    expect(result.success).toBe(true);
    expect(result.data._update_branch_stacks).toBe(true);
  });

  it("should disable stacked PR stack-sync fallback when update_branch_stacks is false", () => {
    const result = updatePRModule.buildPRUpdateData({ update_branch: true }, { update_branch_stacks: false });

    expect(result.success).toBe(true);
    expect(result.data._update_branch_stacks).toBe(false);
  });

  it("should call updateBranch when update_branch is enabled and no other fields are updated", async () => {
    const handler = await updatePRModule.main({ update_branch: true });

    const result = await handler({ pull_request_number: 100 });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
    });
    // The handler now fetches the PR twice: once before mutation for before_state and
    // once after updateBranch so after_state includes the real retained-update fields.
    expect(mockGithub.rest.pulls.get).toHaveBeenCalledTimes(2);
    expect(mockGithub.rest.pulls.get).toHaveBeenNthCalledWith(1, {
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
    });
    expect(mockGithub.rest.pulls.get).toHaveBeenNthCalledWith(2, {
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
    });
    expect(mockGithub.rest.pulls.update).not.toHaveBeenCalled();
    expect(result.before_state).toMatchObject({
      title: "Test PR",
      state: "",
      base: "",
      draft: false,
      head_sha: "",
    });
    expect(result.after_state).toMatchObject({
      title: "Test PR",
      state: "",
      base: "",
      draft: false,
      head_sha: "",
    });
  });

  it("should call updateBranch before pulls.update when update_branch and title update are both requested", async () => {
    const handler = await updatePRModule.main({});

    await handler({
      pull_request_number: 100,
      title: "Updated PR",
      update_branch: true,
    });

    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalled();
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
  });

  it("should retry updateBranch on transient failures", async () => {
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(new Error("timeout contacting github")).mockResolvedValueOnce({
      data: { message: "Branch updated after retry" },
    });

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({ pull_request_number: 100 });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(2);
  });

  it("should log update-branch operation failure when updateBranch fails", async () => {
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(new Error("branch update forbidden"));

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({ pull_request_number: 100 });

    expect(result.success).toBe(false);
    expect(result.error).toContain("update pull request #100 branch from base failed");
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("Failed to update pull request #100 branch from base"));
  });

  it("should treat no-new-commits updateBranch response as a non-fatal no-op", async () => {
    const noNewCommitsError = new Error("There are no new commits on the base branch.");
    noNewCommitsError.status = 422;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(noNewCommitsError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({ pull_request_number: 100 });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.rest.pulls.update).not.toHaveBeenCalled();
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should continue title/body updates when updateBranch reports merge conflict", async () => {
    const mergeConflictError = new Error("merge conflict between base and head");
    mergeConflictError.status = 422;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(mergeConflictError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should treat head-ref-missing updateBranch response as a non-fatal stale-target skip", async () => {
    const staleHeadError = new Error("head ref does not exist - https://docs.github.com/rest/pulls/pulls#update-a-pull-request-branch");
    staleHeadError.status = 422;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(staleHeadError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({ pull_request_number: 100 });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.rest.pulls.update).not.toHaveBeenCalled();
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should continue title/body updates when updateBranch reports head ref missing", async () => {
    const staleHeadError = new Error("head ref does not exist - https://docs.github.com/rest/pulls/pulls#update-a-pull-request-branch");
    staleHeadError.status = 422;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(staleHeadError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should treat head-ref-missing as non-fatal regardless of updateBranch status", async () => {
    const unexpectedStatusError = new Error("head ref does not exist - https://docs.github.com/rest/pulls/pulls#update-a-pull-request-branch");
    unexpectedStatusError.status = 404;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(unexpectedStatusError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({ pull_request_number: 100 });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.rest.pulls.update).not.toHaveBeenCalled();
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should keep head-ref-missing fatal when updateBranch has no numeric status", async () => {
    const missingStatusError = new Error("head ref does not exist - https://docs.github.com/rest/pulls/pulls#update-a-pull-request-branch");
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(missingStatusError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({ pull_request_number: 100 });

    expect(result.success).toBe(false);
    expect(result.error).toContain("update pull request #100 branch from base failed");
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockCore.warning).toHaveBeenCalledWith(expect.not.stringContaining("(non-fatal)"));
  });

  it("should continue title/body updates when updateBranch gets workflows-permission 403", async () => {
    const permissionError = new Error("refusing to allow a GitHub App to create or update workflow `.github/workflows/test.lock.yml` without `workflows` permission");
    permissionError.status = 403;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(permissionError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should continue title/body updates when updateBranch reports stacked-PR unsupported", async () => {
    const stackedPRError = new Error("Updating a stacked PR's branch via this endpoint is not supported.");
    stackedPRError.status = 422;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(stackedPRError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.request).toHaveBeenCalledWith("GET /repos/{owner}/{repo}/stacks", {
      owner: "testowner",
      repo: "testrepo",
      pull_request: 100,
      per_page: 1,
    });
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should sync stack when updateBranch reports stacked-PR unsupported and stack sync API is available", async () => {
    const stackedPRError = new Error("Updating a stacked PR's branch via this endpoint is not supported.");
    stackedPRError.status = 422;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(stackedPRError);
    mockGithub.request.mockImplementation(async route => {
      if (route === "GET /repos/{owner}/{repo}/stacks") {
        return {
          data: [{ number: 7 }],
        };
      }
      if (route === "POST /repos/{owner}/{repo}/stacks/{stack_number}/sync") {
        return { data: {} };
      }
      throw new Error(`Unexpected route: ${route}`);
    });

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.request).toHaveBeenCalledWith("POST /repos/{owner}/{repo}/stacks/{stack_number}/sync", {
      owner: "testowner",
      repo: "testrepo",
      stack_number: 7,
    });
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.warning).not.toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should keep stacked-PR unsupported non-fatal when stack sync API attempt fails", async () => {
    const stackedPRError = new Error("Updating a stacked PR's branch via this endpoint is not supported.");
    stackedPRError.status = 422;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(stackedPRError);
    mockGithub.request.mockImplementation(async route => {
      if (route === "GET /repos/{owner}/{repo}/stacks") {
        return {
          data: [{ number: 7 }],
        };
      }
      if (route === "POST /repos/{owner}/{repo}/stacks/{stack_number}/sync") {
        throw new Error("stack sync endpoint unavailable");
      }
      throw new Error(`Unexpected route: ${route}`);
    });

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should keep stacked-PR unsupported non-fatal without stack sync when update_branch_stacks is false", async () => {
    const stackedPRError = new Error("Updating a stacked PR's branch via this endpoint is not supported.");
    stackedPRError.status = 422;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(stackedPRError);

    const handler = await updatePRModule.main({ update_branch: true, update_branch_stacks: false });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.request).not.toHaveBeenCalled();
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("Skipping stacked PR stack-sync fallback"));
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should keep stacked-PR unsupported non-fatal when updateBranch returns 403", async () => {
    const stackedPRError = new Error("Updating a stacked PR's branch via this endpoint is not supported.");
    stackedPRError.status = 403;
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(stackedPRError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.update).toHaveBeenCalled();
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should continue title/body updates when updateBranch gets workflows-scope-required 403 (scope phrase variant)", async () => {
    // Message matches only the "`workflows` scope may be required" branch of hasWorkflowsScopeRequired.
    const scopeError = new Error("Validation failed; `workflows` scope may be required due to timeout in check.");
    scopeError.status = 403;
    // The message contains "timeout" which makes isTransientError return true, so withRetry
    // retries once (maxRetries: 1, see executePRUpdate). Both attempts must fail to reach the
    // non-fatal catch path. Update this assertion if maxRetries changes.
    mockGithub.rest.pulls.updateBranch.mockRejectedValue(scopeError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    // Called twice: initial attempt + 1 retry (maxRetries: 1 in executePRUpdate)
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(2);
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });

  it("should continue title/body updates when updateBranch gets unable-to-determine-workflow 403 (unable-to-determine variant)", async () => {
    // Message matches only the "unable to determine if workflow can be created or updated" branch
    // of hasWorkflowsScopeRequired, independently of the scope-phrase variant above.
    const unableToDetermineError = new Error("Unable to determine if workflow can be created or updated; contact support.");
    unableToDetermineError.status = 403;
    // No "timeout" in the message, so isTransientError returns false — no retry, called once.
    mockGithub.rest.pulls.updateBranch.mockRejectedValueOnce(unableToDetermineError);

    const handler = await updatePRModule.main({ update_branch: true });
    const result = await handler({
      pull_request_number: 100,
      title: "Updated PR",
    });

    expect(result.success).toBe(true);
    expect(mockGithub.rest.pulls.updateBranch).toHaveBeenCalledTimes(1);
    expect(mockGithub.rest.pulls.update).toHaveBeenCalledWith({
      owner: "testowner",
      repo: "testrepo",
      pull_number: 100,
      title: "Updated PR",
    });
    expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("branch from base (non-fatal)"));
  });
});
