import { describe, it, expect, beforeEach, vi } from "vitest";
import { readFileSync } from "fs";
import path from "path";
import * as threatDetectionWarning from "./threat_detection_warning.cjs";
const createTestableFunction = scriptContent => {
  const beforeMainCall = scriptContent.match(/^([\s\S]*?)\s*module\.exports\s*=\s*{[\s\S]*?};?\s*$/);
  if (!beforeMainCall) throw new Error("Could not extract script content before module.exports");
  let scriptBody = beforeMainCall[1];
  // Mock the error_helpers and messages_core modules
  const mockRequire = (module, threatDetectionWarning) => {
    if (module === "./error_helpers.cjs") {
      return { getErrorMessage: error => (error instanceof Error ? error.message : String(error)) };
    }
    if (module === "./messages_core.cjs") {
      return {
        getMessages: () => {
          // Return messages config from environment
          const messagesEnv = process.env.GH_AW_SAFE_OUTPUT_MESSAGES;
          if (!messagesEnv) return null;
          try {
            return JSON.parse(messagesEnv);
          } catch (e) {
            return null;
          }
        },
      };
    }
    if (module === "./sanitize_content.cjs") {
      // Mock sanitizeContent to return input as-is for testing
      return { sanitizeContent: content => content };
    }
    if (module === "./messages_run_status.cjs") {
      const messagesEnv = process.env.GH_AW_SAFE_OUTPUT_MESSAGES;
      const messages = messagesEnv ? JSON.parse(messagesEnv) : null;
      const renderTmpl = (tmpl, ctx) => tmpl.replace(/\{(\w+)\}/g, (m, k) => (ctx[k] !== undefined ? String(ctx[k]) : m));
      const toSnake = obj => {
        const r = {};
        for (const [k, v] of Object.entries(obj)) {
          r[k.replace(/([A-Z])/g, "_$1").toLowerCase()] = v;
          r[k] = v;
        }
        return r;
      };
      return {
        getPullRequestCreatedMessage: ctx => {
          const tc = toSnake(ctx);
          const def = "Pull request created: [#{item_number}]({item_url})";
          return messages?.pullRequestCreated ? renderTmpl(messages.pullRequestCreated, tc) : renderTmpl(def, tc);
        },
        getIssueCreatedMessage: ctx => {
          const tc = toSnake(ctx);
          const def = "Issue created: [#{item_number}]({item_url})";
          return messages?.issueCreated ? renderTmpl(messages.issueCreated, tc) : renderTmpl(def, tc);
        },
        getCommitPushedMessage: ctx => {
          const tc = toSnake(ctx);
          const def = "Commit pushed: [`{short_sha}`]({commit_url})";
          return messages?.commitPushed ? renderTmpl(messages.commitPushed, tc) : renderTmpl(def, tc);
        },
        getDetectionWarningMessage: ctx => {
          const reasonText = threatDetectionWarning.getDetectionReasonText(ctx.reason);
          const warning = threatDetectionWarning.getThreatWarningPresentation(ctx.reason);
          return `> [!${warning.admonition}]\n> ${warning.title}\n> ${warning.summary}\n> ${warning.marker}\n>\n> ${reasonText}`;
        },
      };
    }
    if (module === "./templatable.cjs") {
      return {
        parseBoolTemplatable: (value, defaultValue = true) => {
          if (value === undefined || value === null) return defaultValue;
          return String(value) !== "false";
        },
      };
    }
    if (module === "./generate_footer.cjs") {
      return {
        generateXMLMarker: (workflowName, runUrl) => `<!-- gh-aw-agentic-workflow: ${workflowName}, run: ${runUrl} -->`,
      };
    }
    if (module === "./messages_footer.cjs") {
      return {
        getFooterMessage: ctx => `> Generated by [${ctx.workflowName}](${ctx.runUrl})`,
        getDetectionCautionAlert: (workflowName, runUrl) => {
          const conclusion = process.env.GH_AW_DETECTION_CONCLUSION;
          if (conclusion !== "warning") return "";
          const reason = process.env.GH_AW_DETECTION_REASON || "";
          return mockRequire("./messages_run_status.cjs", threatDetectionWarning).getDetectionWarningMessage({ workflowName, runUrl, reason });
        },
      };
    }
    if (module === "./threat_detection_warning.cjs") {
      return threatDetectionWarning;
    }
    if (module === "./workflow_metadata_helpers.cjs") {
      return {
        buildWorkflowRunUrl: (ctx, repo) => {
          const server = ctx.serverUrl || "https://github.com";
          return `${server}/${repo.owner}/${repo.repo}/actions/runs/${ctx.runId}`;
        },
      };
    }
    if (module === "./github_api_helpers.cjs") {
      return {
        resolveTopLevelDiscussionCommentId: async (githubClient, commentNodeId) => {
          // In tests, simulate that the triggering comment is always a top-level comment
          return commentNodeId;
        },
      };
    }
    if (module === "./invocation_context_helpers.cjs") {
      return {
        resolveInvocationContext: ctx => {
          if (ctx?.eventName === "repository_dispatch" && ctx?.payload?.client_payload) {
            const payload = ctx.payload.client_payload;
            const eventRepo = payload?.repository?.owner?.login && payload?.repository?.name ? { owner: payload.repository.owner.login, repo: payload.repository.name } : ctx.eventRepo || ctx.repo;
            return {
              source: "repository_dispatch",
              eventName: ctx.payload.action || ctx.eventName,
              eventPayload: payload,
              workflowRepo: ctx.workflowRepo || ctx.repo,
              eventRepo,
            };
          }

          if (ctx?.eventName === "workflow_dispatch" && ctx?.payload?.inputs) {
            const inputs = ctx.payload.inputs;
            let parsedPayload = ctx.payload;
            if (typeof inputs.event_payload === "string" && inputs.event_payload) {
              try {
                parsedPayload = JSON.parse(inputs.event_payload);
              } catch (_error) {
                parsedPayload = ctx.payload;
              }
            }
            const eventRepo =
              typeof inputs.event_repo === "string" && inputs.event_repo.includes("/")
                ? (() => {
                    const [owner, repo] = inputs.event_repo.split("/");
                    return { owner, repo };
                  })()
                : ctx.eventRepo || ctx.repo;
            return {
              source: "workflow_dispatch",
              eventName: inputs.event_name || ctx.eventName,
              eventPayload: parsedPayload,
              workflowRepo: ctx.workflowRepo || ctx.repo,
              eventRepo,
            };
          }

          return {
            source: "native",
            eventName: ctx?.eventName || "",
            eventPayload: ctx?.payload || {},
            workflowRepo: ctx?.workflowRepo || ctx?.repo,
            eventRepo: ctx?.eventRepo || ctx?.repo,
          };
        },
      };
    }
    throw new Error(`Module ${module} not mocked in test`);
  };
  return new Function(
    `\n    const { github, core, context, process, threatDetectionWarning } = arguments[0];\n    const mockRequire = ${mockRequire.toString()};\n    const require = module => mockRequire(module, threatDetectionWarning);\n    \n    ${scriptBody}\n    \n    return { updateActivationComment, updateActivationCommentWithCommit, updateActivationCommentWithMessage };\n  `
  );
};
describe("update_activation_comment.cjs", () => {
  let createFunctionFromScript, mockDependencies;
  (beforeEach(() => {
    const scriptPath = path.join(process.cwd(), "update_activation_comment.cjs"),
      scriptContent = readFileSync(scriptPath, "utf8");
    ((createFunctionFromScript = createTestableFunction(scriptContent)),
      (mockDependencies = {
        github: { graphql: vi.fn(), request: vi.fn() },
        core: { info: vi.fn(), warning: vi.fn(), setFailed: vi.fn() },
        context: { repo: { owner: "testowner", repo: "testrepo" } },
        process: { env: {} },
        threatDetectionWarning,
      }));
  }),
    it("should skip comment when no activation comment ID or triggering context exists", async () => {
      mockDependencies.process.env.GH_AW_COMMENT_ID = "";
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42);
      expect(mockDependencies.core.info).toHaveBeenCalledWith("No activation comment to update (GH_AW_COMMENT_ID not set)");
      expect(mockDependencies.github.request).not.toHaveBeenCalled();
    }),
    it("should create new comment on triggering PR when GH_AW_COMMENT_ID is not set", async () => {
      mockDependencies.process.env.GH_AW_COMMENT_ID = "";
      mockDependencies.context.payload = { pull_request: { number: 10 } };
      mockDependencies.github.request.mockResolvedValue({
        data: { id: 789012, html_url: "https://github.com/testowner/testrepo/issues/10#issuecomment-789012" },
      });
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42);
      expect(mockDependencies.core.info).toHaveBeenCalledWith("No activation comment to update (GH_AW_COMMENT_ID not set), creating new comment on testowner/testrepo#10");
      expect(mockDependencies.github.request).toHaveBeenCalledWith(
        "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
        expect.objectContaining({
          owner: "testowner",
          repo: "testrepo",
          issue_number: 10,
          body: expect.stringContaining("Pull request created: [#42]"),
        })
      );
      expect(mockDependencies.core.info).toHaveBeenCalledWith("Successfully created comment with pull request link on #10");
    }),
    it("should use workflowRepo for run attribution in footer when context includes workflowRepo", async () => {
      mockDependencies.process.env.GH_AW_COMMENT_ID = "";
      mockDependencies.context = {
        ...mockDependencies.context,
        runId: 12345,
        repo: { owner: "targetowner", repo: "targetrepo" },
        workflowRepo: { owner: "sideowner", repo: "siderepo" },
        payload: { pull_request: { number: 10 } },
      };
      mockDependencies.github.request.mockResolvedValue({
        data: { id: 123, html_url: "https://github.com/targetowner/targetrepo/issues/10#issuecomment-123" },
      });

      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/targetowner/targetrepo/pull/42", 42);

      expect(mockDependencies.github.request).toHaveBeenCalledWith(
        "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
        expect.objectContaining({
          body: expect.stringContaining("https://github.com/sideowner/siderepo/actions/runs/12345"),
        })
      );
    }),
    it.each([
      ["agent_failure", "> threat detection engine error", "<!-- gh-aw-threat-engine-error -->", "<!-- gh-aw-threat-detected -->"],
      ["threat_detected", "> agentic threat detected", "<!-- gh-aw-threat-detected -->", "<!-- gh-aw-threat-engine-error -->"],
    ])("should include the %s detection banner in created activation comments", async (reason, titleLine, expectedMarker, unexpectedMarker) => {
      mockDependencies.process.env.GH_AW_COMMENT_ID = "";
      mockDependencies.process.env.GH_AW_DETECTION_CONCLUSION = "warning";
      mockDependencies.process.env.GH_AW_DETECTION_REASON = reason;
      mockDependencies.context = {
        ...mockDependencies.context,
        runId: 12345,
        payload: { pull_request: { number: 10 } },
      };
      mockDependencies.github.request.mockResolvedValue({
        data: { id: 789012, html_url: "https://github.com/testowner/testrepo/issues/10#issuecomment-789012" },
      });

      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42);

      const [, requestParams] = mockDependencies.github.request.mock.calls[0];
      expect(requestParams.body).toContain(titleLine);
      expect(requestParams.body).toContain(expectedMarker);
      expect(requestParams.body).not.toContain(unexpectedMarker);
    }),
    it("should skip update when GH_AW_COMMENT_ID is not set and no target issue number", async () => {
      mockDependencies.process.env.GH_AW_COMMENT_ID = "";
      const { updateActivationCommentWithMessage } = createFunctionFromScript(mockDependencies);
      await updateActivationCommentWithMessage(mockDependencies.github, mockDependencies.context, mockDependencies.core, "\n\ntest message", "test");
      expect(mockDependencies.core.info).toHaveBeenCalledWith("No activation comment to update (GH_AW_COMMENT_ID not set)");
      expect(mockDependencies.github.request).not.toHaveBeenCalled();
    }),
    it("should update issue comment with PR link", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "123456"),
        (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"),
        mockDependencies.github.request.mockImplementation(async (method, params) =>
          method.startsWith("GET")
            ? { data: { body: "Agentic [workflow](https://github.com/testowner/testrepo/actions/runs/12345) triggered by this issue." } }
            : method.startsWith("PATCH")
              ? { data: { id: 123456, html_url: "https://github.com/testowner/testrepo/issues/1#issuecomment-123456" } }
              : { data: {} }
        ));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.github.request).toHaveBeenCalledWith("GET /repos/{owner}/{repo}/issues/comments/{comment_id}", expect.objectContaining({ owner: "testowner", repo: "testrepo", comment_id: 123456 })),
        expect(mockDependencies.github.request).toHaveBeenCalledWith(
          "PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}",
          expect.objectContaining({ owner: "testowner", repo: "testrepo", comment_id: 123456, body: expect.stringContaining("Pull request created: [#42](https://github.com/testowner/testrepo/pull/42)") })
        ),
        expect(mockDependencies.core.info).toHaveBeenCalledWith("Successfully updated comment with pull request link"));
    }),
    it("should update discussion comment with PR link using GraphQL", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "DC_kwDOABCDEF4ABCDEF"),
        (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"),
        mockDependencies.github.graphql.mockImplementation(async (query, params) =>
          query.includes("query")
            ? { node: { body: "Agentic [workflow](https://github.com/testowner/testrepo/actions/runs/12345) triggered by this discussion." } }
            : query.includes("mutation")
              ? { updateDiscussionComment: { comment: { id: "DC_kwDOABCDEF4ABCDEF", url: "https://github.com/testowner/testrepo/discussions/1#discussioncomment-123456" } } }
              : {}
        ));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.github.graphql).toHaveBeenCalledWith(expect.stringContaining("query($commentId: ID!)"), expect.objectContaining({ commentId: "DC_kwDOABCDEF4ABCDEF" })),
        expect(mockDependencies.github.graphql).toHaveBeenCalledWith(
          expect.stringContaining("mutation($commentId: ID!, $body: String!)"),
          expect.objectContaining({ commentId: "DC_kwDOABCDEF4ABCDEF", body: expect.stringContaining("Pull request created: [#42](https://github.com/testowner/testrepo/pull/42)") })
        ),
        expect(mockDependencies.core.info).toHaveBeenCalledWith("Successfully updated discussion comment with pull request link"));
    }),
    it("should not fail workflow if comment update fails", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "123456"), (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"), mockDependencies.github.request.mockRejectedValue(new Error("Comment update failed")));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.core.warning).toHaveBeenCalledWith("Failed to update activation comment: Comment update failed"),
        expect(mockDependencies.core.setFailed).not.toHaveBeenCalled());
    }),
    it("should use default repo from context if comment_repo not set", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "123456"),
        mockDependencies.github.request.mockImplementation(async (method, params) =>
          method.startsWith("GET") ? { data: { body: "Original comment" } } : method.startsWith("PATCH") ? { data: { id: 123456, html_url: "https://github.com/testowner/testrepo/issues/1#issuecomment-123456" } } : { data: {} }
        ));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.github.request).toHaveBeenCalledWith("GET /repos/{owner}/{repo}/issues/comments/{comment_id}", expect.objectContaining({ owner: "testowner", repo: "testrepo" })));
    }),
    it("should handle invalid comment_repo format and fall back to context", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "123456"),
        (mockDependencies.process.env.GH_AW_COMMENT_REPO = "invalid-format"),
        mockDependencies.github.request.mockImplementation(async (method, params) =>
          method.startsWith("GET") ? { data: { body: "Original comment" } } : method.startsWith("PATCH") ? { data: { id: 123456, html_url: "https://github.com/testowner/testrepo/issues/1#issuecomment-123456" } } : { data: {} }
        ));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.core.warning).toHaveBeenCalledWith('Invalid comment repo format: invalid-format, expected "owner/repo". Falling back to context.repo.'),
        expect(mockDependencies.github.request).toHaveBeenCalledWith("GET /repos/{owner}/{repo}/issues/comments/{comment_id}", expect.objectContaining({ owner: "testowner", repo: "testrepo" })));
    }),
    it("should handle deleted discussion comment (null body in GraphQL)", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "DC_kwDOABCDEF4ABCDEF"), (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"), mockDependencies.github.graphql.mockResolvedValue({ node: { body: null } }));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.core.warning).toHaveBeenCalledWith("Unable to fetch current comment body, comment may have been deleted or is inaccessible"),
        expect(mockDependencies.github.graphql).toHaveBeenCalledTimes(1));
    }),
    it("should handle deleted discussion comment (null node in GraphQL)", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "DC_kwDOABCDEF4ABCDEF"), (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"), mockDependencies.github.graphql.mockResolvedValue({ node: null }));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.core.warning).toHaveBeenCalledWith("Unable to fetch current comment body, comment may have been deleted or is inaccessible"),
        expect(mockDependencies.github.graphql).toHaveBeenCalledTimes(1));
    }),
    it("should handle deleted issue comment (null body in REST API)", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "123456"), (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"), mockDependencies.github.request.mockResolvedValue({ data: { body: null } }));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.core.warning).toHaveBeenCalledWith("Unable to fetch current comment body, comment may have been deleted"),
        expect(mockDependencies.github.request).toHaveBeenCalledTimes(1));
    }),
    it("should handle deleted issue comment (undefined body in REST API)", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "123456"), (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"), mockDependencies.github.request.mockResolvedValue({ data: {} }));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/42", 42),
        expect(mockDependencies.core.warning).toHaveBeenCalledWith("Unable to fetch current comment body, comment may have been deleted"),
        expect(mockDependencies.github.request).toHaveBeenCalledTimes(1));
    }),
    it("should update issue comment with issue link when itemType is 'issue'", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "123456"),
        (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"),
        mockDependencies.github.request.mockImplementation(async (method, params) =>
          method.startsWith("GET")
            ? { data: { body: "Agentic [workflow](https://github.com/testowner/testrepo/actions/runs/12345) triggered by this issue." } }
            : method.startsWith("PATCH")
              ? { data: { id: 123456, html_url: "https://github.com/testowner/testrepo/issues/1#issuecomment-123456" } }
              : { data: {} }
        ));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/issues/99", 99, "issue"),
        expect(mockDependencies.github.request).toHaveBeenCalledWith(
          "PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}",
          expect.objectContaining({ owner: "testowner", repo: "testrepo", comment_id: 123456, body: expect.stringContaining("Issue created: [#99](https://github.com/testowner/testrepo/issues/99)") })
        ),
        expect(mockDependencies.core.info).toHaveBeenCalledWith("Successfully updated comment with issue link"));
    }),
    it("should update discussion comment with issue link using GraphQL when itemType is 'issue'", async () => {
      ((mockDependencies.process.env.GH_AW_COMMENT_ID = "DC_kwDOABCDEF4ABCDEF"),
        (mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo"),
        mockDependencies.github.graphql.mockImplementation(async (query, params) =>
          query.includes("query")
            ? { node: { body: "Agentic [workflow](https://github.com/testowner/testrepo/actions/runs/12345) triggered by this discussion." } }
            : query.includes("mutation")
              ? { updateDiscussionComment: { comment: { id: "DC_kwDOABCDEF4ABCDEF", url: "https://github.com/testowner/testrepo/discussions/1#discussioncomment-123456" } } }
              : {}
        ));
      const { updateActivationComment } = createFunctionFromScript(mockDependencies);
      (await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/issues/99", 99, "issue"),
        expect(mockDependencies.github.graphql).toHaveBeenCalledWith(
          expect.stringContaining("mutation($commentId: ID!, $body: String!)"),
          expect.objectContaining({ commentId: "DC_kwDOABCDEF4ABCDEF", body: expect.stringContaining("Issue created: [#99](https://github.com/testowner/testrepo/issues/99)") })
        ),
        expect(mockDependencies.core.info).toHaveBeenCalledWith("Successfully updated discussion comment with issue link"));
    }),
    describe("fallback comment creation when no activation comment", () => {
      (it("should create new comment on target PR via updateActivationCommentWithCommit when no activation comment", async () => {
        mockDependencies.process.env.GH_AW_COMMENT_ID = "";
        mockDependencies.github.request.mockResolvedValue({
          data: { id: 789012, html_url: "https://github.com/testowner/testrepo/issues/225#issuecomment-789012" },
        });
        const { updateActivationCommentWithCommit } = createFunctionFromScript(mockDependencies);
        await updateActivationCommentWithCommit(
          mockDependencies.github,
          mockDependencies.context,
          mockDependencies.core,
          "41b061a0abc1c574c8ca4344bb69961efee7b45c",
          "https://github.com/testowner/testrepo/commit/41b061a0abc1c574c8ca4344bb69961efee7b45c",
          { targetIssueNumber: 225 }
        );
        expect(mockDependencies.core.info).toHaveBeenCalledWith("No activation comment to update (GH_AW_COMMENT_ID not set), creating new comment on testowner/testrepo#225");
        expect(mockDependencies.github.request).toHaveBeenCalledWith(
          "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
          expect.objectContaining({
            owner: "testowner",
            repo: "testrepo",
            issue_number: 225,
            body: expect.stringContaining("Commit pushed:"),
          })
        );
        expect(mockDependencies.core.info).toHaveBeenCalledWith("Successfully created comment with commit link on #225");
      }),
        it("should use context.payload.pull_request.number when no targetIssueNumber", async () => {
          mockDependencies.process.env.GH_AW_COMMENT_ID = "";
          mockDependencies.context.payload = { pull_request: { number: 100 } };
          mockDependencies.github.request.mockResolvedValue({
            data: { id: 789013, html_url: "https://github.com/testowner/testrepo/issues/100#issuecomment-789013" },
          });
          const { updateActivationCommentWithMessage } = createFunctionFromScript(mockDependencies);
          await updateActivationCommentWithMessage(mockDependencies.github, mockDependencies.context, mockDependencies.core, "\n\n✅ Test message", "test");
          expect(mockDependencies.core.info).toHaveBeenCalledWith("No activation comment to update (GH_AW_COMMENT_ID not set), creating new comment on testowner/testrepo#100");
          expect(mockDependencies.github.request).toHaveBeenCalledWith("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", expect.objectContaining({ issue_number: 100 }));
        }),
        it("should use context.payload.issue.number when no targetIssueNumber and no pull_request", async () => {
          mockDependencies.process.env.GH_AW_COMMENT_ID = "";
          mockDependencies.context.payload = { issue: { number: 50 } };
          mockDependencies.github.request.mockResolvedValue({
            data: { id: 789014, html_url: "https://github.com/testowner/testrepo/issues/50#issuecomment-789014" },
          });
          const { updateActivationCommentWithMessage } = createFunctionFromScript(mockDependencies);
          await updateActivationCommentWithMessage(mockDependencies.github, mockDependencies.context, mockDependencies.core, "\n\n✅ Test message", "test");
          expect(mockDependencies.core.info).toHaveBeenCalledWith("No activation comment to update (GH_AW_COMMENT_ID not set), creating new comment on testowner/testrepo#50");
          expect(mockDependencies.github.request).toHaveBeenCalledWith("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", expect.objectContaining({ issue_number: 50 }));
        }),
        it("should not fail if fallback comment creation fails", async () => {
          mockDependencies.process.env.GH_AW_COMMENT_ID = "";
          mockDependencies.github.request.mockRejectedValue(new Error("API rate limit exceeded"));
          const { updateActivationCommentWithCommit } = createFunctionFromScript(mockDependencies);
          await updateActivationCommentWithCommit(
            mockDependencies.github,
            mockDependencies.context,
            mockDependencies.core,
            "41b061a0abc1c574c8ca4344bb69961efee7b45c",
            "https://github.com/testowner/testrepo/commit/41b061a0abc1c574c8ca4344bb69961efee7b45c",
            { targetIssueNumber: 225 }
          );
          expect(mockDependencies.core.warning).toHaveBeenCalledWith("Failed to create comment on testowner/testrepo#225: API rate limit exceeded");
          expect(mockDependencies.core.setFailed).not.toHaveBeenCalled();
        }),
        it("should log skip message when no activation comment, no targetIssueNumber, and no context payload", async () => {
          mockDependencies.process.env.GH_AW_COMMENT_ID = "";
          const { updateActivationCommentWithCommit } = createFunctionFromScript(mockDependencies);
          await updateActivationCommentWithCommit(
            mockDependencies.github,
            mockDependencies.context,
            mockDependencies.core,
            "41b061a0abc1c574c8ca4344bb69961efee7b45c",
            "https://github.com/testowner/testrepo/commit/41b061a0abc1c574c8ca4344bb69961efee7b45c"
          );
          expect(mockDependencies.core.info).toHaveBeenCalledWith("No activation comment to update (GH_AW_COMMENT_ID not set)");
          expect(mockDependencies.github.request).not.toHaveBeenCalled();
        }));
    }),
    describe("append-only-comments mode", () => {
      it("should create new issue comment instead of updating when append-only-comments is enabled", async () => {
        mockDependencies.process.env.GH_AW_COMMENT_ID = "123456";
        mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo";
        mockDependencies.process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
          appendOnlyComments: true,
        });
        mockDependencies.context.eventName = "issues";
        mockDependencies.context.payload = { issue: { number: 42 } };

        mockDependencies.github.request.mockImplementation(async (method, params) => {
          if (method.startsWith("POST")) {
            return {
              data: {
                id: 789012,
                html_url: "https://github.com/testowner/testrepo/issues/42#issuecomment-789012",
              },
            };
          }
          return { data: {} };
        });

        const { updateActivationComment } = createFunctionFromScript(mockDependencies);
        await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/99", 99);

        // Should create a new comment, not update the existing one
        expect(mockDependencies.github.request).toHaveBeenCalledWith(
          "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
          expect.objectContaining({
            owner: "testowner",
            repo: "testrepo",
            issue_number: 42,
            body: expect.stringContaining("Pull request created: [#99]"),
          })
        );
        expect(mockDependencies.core.info).toHaveBeenCalledWith("Append-only-comments enabled: creating a new comment");
        expect(mockDependencies.core.info).toHaveBeenCalledWith("Successfully created append-only comment with pull request link");

        // Should NOT call GET or PATCH for updating existing comment
        expect(mockDependencies.github.request).not.toHaveBeenCalledWith("GET /repos/{owner}/{repo}/issues/comments/{comment_id}", expect.any(Object));
        expect(mockDependencies.github.request).not.toHaveBeenCalledWith("PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}", expect.any(Object));
      });

      it("should create new discussion comment instead of updating when append-only-comments is enabled", async () => {
        mockDependencies.process.env.GH_AW_COMMENT_ID = "DC_kwDOABCDEF4ABCDEF";
        mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo";
        mockDependencies.process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
          appendOnlyComments: true,
        });
        mockDependencies.context.eventName = "discussion";
        mockDependencies.context.payload = { discussion: { number: 10 } };

        mockDependencies.github.graphql.mockImplementation(async (query, params) => {
          if (query.includes("query") && query.includes("discussion(number")) {
            return {
              repository: {
                discussion: {
                  id: "D_kwDOABCDEF4ABCDEF",
                },
              },
            };
          }
          if (query.includes("mutation") && query.includes("addDiscussionComment")) {
            return {
              addDiscussionComment: {
                comment: {
                  id: "DC_kwDOABCDEF4NEW",
                  url: "https://github.com/testowner/testrepo/discussions/10#discussioncomment-new",
                },
              },
            };
          }
          return {};
        });

        const { updateActivationComment } = createFunctionFromScript(mockDependencies);
        await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/99", 99);

        // Should create a new discussion comment
        expect(mockDependencies.github.graphql).toHaveBeenCalledWith(
          expect.stringContaining("mutation"),
          expect.objectContaining({
            dId: "D_kwDOABCDEF4ABCDEF",
            body: expect.stringContaining("Pull request created: [#99]"),
          })
        );
        expect(mockDependencies.core.info).toHaveBeenCalledWith("Successfully created append-only discussion comment with pull request link");

        // Should NOT call updateDiscussionComment mutation
        expect(mockDependencies.github.graphql).not.toHaveBeenCalledWith(expect.stringContaining("updateDiscussionComment"), expect.any(Object));
      });

      it("should handle missing issue number gracefully in append-only mode", async () => {
        mockDependencies.process.env.GH_AW_COMMENT_ID = "123456";
        mockDependencies.process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
          appendOnlyComments: true,
        });
        mockDependencies.context.eventName = "issues";
        mockDependencies.context.payload = {}; // No issue number

        const { updateActivationComment } = createFunctionFromScript(mockDependencies);
        await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/99", 99);

        expect(mockDependencies.core.warning).toHaveBeenCalledWith("Unable to determine issue/PR number for append-only comment; skipping");
        expect(mockDependencies.github.request).not.toHaveBeenCalled();
      });

      it("should update existing comment when append-only-comments is false", async () => {
        mockDependencies.process.env.GH_AW_COMMENT_ID = "123456";
        mockDependencies.process.env.GH_AW_COMMENT_REPO = "testowner/testrepo";
        mockDependencies.process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
          appendOnlyComments: false,
        });

        mockDependencies.github.request.mockImplementation(async (method, params) => {
          if (method.startsWith("GET")) {
            return { data: { body: "Original comment" } };
          }
          if (method.startsWith("PATCH")) {
            return {
              data: {
                id: 123456,
                html_url: "https://github.com/testowner/testrepo/issues/1#issuecomment-123456",
              },
            };
          }
          return { data: {} };
        });

        const { updateActivationComment } = createFunctionFromScript(mockDependencies);
        await updateActivationComment(mockDependencies.github, mockDependencies.context, mockDependencies.core, "https://github.com/testowner/testrepo/pull/99", 99);

        // Should update the existing comment (standard behavior)
        expect(mockDependencies.github.request).toHaveBeenCalledWith("GET /repos/{owner}/{repo}/issues/comments/{comment_id}", expect.objectContaining({ comment_id: 123456 }));
        expect(mockDependencies.github.request).toHaveBeenCalledWith("PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}", expect.objectContaining({ comment_id: 123456 }));
      });
    }));
});
