import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock core for logging
const mockCore = {
  info: vi.fn(),
  debug: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
};

global.core = mockCore;

// Import the module
const { buildAIFooter, buildUpdatedBody, buildIslandStartMarker, buildIslandEndMarker, findIsland, updateBody } = await import("./update_pr_description_helpers.cjs");

describe("update_pr_description_helpers.cjs", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("buildAIFooter", () => {
    it("should build AI footer with workflow name and run URL using messages system", () => {
      const footer = buildAIFooter("Test Workflow", "https://github.com/owner/repo/actions/runs/123");
      // Should use the default footer from messages system
      expect(footer).toContain("Test Workflow");
      expect(footer).toContain("https://github.com/owner/repo/actions/runs/123");
      expect(footer).toContain("Generated by"); // Professional message
    });

    it("should handle special characters in workflow name", () => {
      const footer = buildAIFooter("Test & Workflow", "https://github.com/owner/repo/actions/runs/123");
      expect(footer).toContain("Test & Workflow");
    });

    it("should include historyUrl in footer when provided", () => {
      const historyUrl = "https://github.com/search?q=repo%3Aowner%2Frepo";
      const footer = buildAIFooter("Test Workflow", "https://github.com/owner/repo/actions/runs/123", historyUrl);
      expect(footer).toContain(historyUrl);
    });

    it("should return a non-empty footer string", () => {
      const footer = buildAIFooter("Test Workflow", "https://github.com/owner/repo/actions/runs/123");
      expect(typeof footer).toBe("string");
      expect(footer.length).toBeGreaterThan(0);
    });
  });

  describe("buildUpdatedBody", () => {
    it("uses the workflow repository for attribution and target repository for history", () => {
      process.env.GH_AW_CALLER_WORKFLOW_ID = "caller-workflow";
      const result = buildUpdatedBody({
        context: {
          repo: { owner: "target", repo: "repository" },
          serverUrl: "https://github.example",
          runId: 123,
        },
        currentBody: "Existing body",
        newContent: "New body",
        operation: "append",
        includeFooter: true,
        workflowRepo: { owner: "workflow", repo: "repository" },
        itemType: "issue",
      });

      expect(result).toContain("https://github.example/workflow/repository/actions/runs/123");
      expect(result).toContain("repo%3Atarget%2Frepository");
      delete process.env.GH_AW_CALLER_WORKFLOW_ID;
    });
  });

  describe("buildIslandStartMarker", () => {
    it("should build island start marker with workflow ID", () => {
      const marker = buildIslandStartMarker("test-workflow");
      expect(marker).toBe("<!-- gh-aw-island-start:test-workflow -->");
    });

    it("should handle different workflow IDs", () => {
      expect(buildIslandStartMarker("workflow-1")).toBe("<!-- gh-aw-island-start:workflow-1 -->");
      expect(buildIslandStartMarker("my-awesome-workflow")).toBe("<!-- gh-aw-island-start:my-awesome-workflow -->");
    });
  });

  describe("buildIslandEndMarker", () => {
    it("should build island end marker with workflow ID", () => {
      const marker = buildIslandEndMarker("test-workflow");
      expect(marker).toBe("<!-- gh-aw-island-end:test-workflow -->");
    });

    it("should handle different workflow IDs", () => {
      expect(buildIslandEndMarker("workflow-1")).toBe("<!-- gh-aw-island-end:workflow-1 -->");
      expect(buildIslandEndMarker("my-awesome-workflow")).toBe("<!-- gh-aw-island-end:my-awesome-workflow -->");
    });
  });

  describe("findIsland", () => {
    it("should find island when both markers are present", () => {
      const body = "Before\n<!-- gh-aw-island-start:test-workflow -->\nIsland content\n<!-- gh-aw-island-end:test-workflow -->\nAfter";
      const result = findIsland(body, "test-workflow");
      expect(result.found).toBe(true);
      expect(result.startIndex).toBeGreaterThanOrEqual(0);
      expect(result.endIndex).toBeGreaterThan(result.startIndex);
    });

    it("should not find island when start marker is missing", () => {
      const body = "Before\nIsland content\n<!-- gh-aw-island-end:test-workflow -->\nAfter";
      const result = findIsland(body, "test-workflow");
      expect(result.found).toBe(false);
      expect(result.startIndex).toBe(-1);
      expect(result.endIndex).toBe(-1);
    });

    it("should not find island when end marker is missing", () => {
      const body = "Before\n<!-- gh-aw-island-start:test-workflow -->\nIsland content\nAfter";
      const result = findIsland(body, "test-workflow");
      expect(result.found).toBe(false);
      expect(result.startIndex).toBe(-1);
      expect(result.endIndex).toBe(-1);
    });

    it("should not find island when workflow ID does not match", () => {
      const body = "Before\n<!-- gh-aw-island-start:workflow-a -->\nIsland content\n<!-- gh-aw-island-end:workflow-a -->\nAfter";
      const result = findIsland(body, "workflow-b");
      expect(result.found).toBe(false);
    });

    it("should handle multiple islands with different workflow IDs", () => {
      const body = "<!-- gh-aw-island-start:workflow-1 -->\nIsland 1\n<!-- gh-aw-island-end:workflow-1 -->\n<!-- gh-aw-island-start:workflow-2 -->\nIsland 2\n<!-- gh-aw-island-end:workflow-2 -->";
      const result1 = findIsland(body, "workflow-1");
      const result2 = findIsland(body, "workflow-2");
      expect(result1.found).toBe(true);
      expect(result2.found).toBe(true);
      expect(result1.startIndex).toBeLessThan(result2.startIndex);
    });

    it("should return exact startIndex=0 and endIndex=body.length when island spans entire body", () => {
      const startMarker = buildIslandStartMarker("wf");
      const endMarker = buildIslandEndMarker("wf");
      const body = `${startMarker}inner${endMarker}`;
      const result = findIsland(body, "wf");
      expect(result.found).toBe(true);
      expect(result.startIndex).toBe(0);
      expect(result.endIndex).toBe(body.length);
    });

    it("should not find island in empty body", () => {
      const result = findIsland("", "test-workflow");
      expect(result.found).toBe(false);
      expect(result.startIndex).toBe(-1);
      expect(result.endIndex).toBe(-1);
    });

    it("should find island with prefix content and return correct startIndex", () => {
      const prefix = "prefix content\n";
      const startMarker = buildIslandStartMarker("wf");
      const endMarker = buildIslandEndMarker("wf");
      const body = `${prefix}${startMarker}inner${endMarker}`;
      const result = findIsland(body, "wf");
      expect(result.found).toBe(true);
      expect(result.startIndex).toBe(prefix.length);
      expect(result.endIndex).toBe(body.length);
    });
  });

  describe("updateBody - replace operation", () => {
    it("should replace entire body and add footer", () => {
      const result = updateBody({
        currentBody: "Old content",
        newContent: "New content",
        operation: "replace",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("New content");
      expect(result).not.toContain("Old content");
      // Should include footer with workflow information
      expect(result).toContain("Test");
      expect(result).toContain("https://github.com/test/actions/runs/123");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("replace"));
    });

    it("separates replacement content from the generated footer with a blank line", () => {
      const result = updateBody({
        currentBody: "Old content",
        newContent: "run: https://github.com/owner/repo/actions/runs/123",
        operation: "replace",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });

      expect(result).toContain("run: https://github.com/owner/repo/actions/runs/123\n\n> Generated by [Test]");
      expect(result).not.toContain("runs/123> Generated by [Test]");
    });
  });

  describe("updateBody - append operation", () => {
    it("should append to empty body", () => {
      const result = updateBody({
        currentBody: "",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("---");
      expect(result).toContain("New content");
      // Check for footer elements (uses messages system with pirate theme by default)
      expect(result).toContain("Test");
      expect(result).toContain("https://github.com/test/actions/runs/123");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("append"));
    });

    it("should append to existing body", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("Original content");
      expect(result).toContain("New content");
      expect(result.indexOf("Original content")).toBeLessThan(result.indexOf("New content"));
    });

    it("separates appended content from the generated footer with a blank line", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "run: https://github.com/owner/repo/actions/runs/123",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });

      expect(result).toContain("run: https://github.com/owner/repo/actions/runs/123\n\n> Generated by [Test]");
      expect(result).not.toContain("runs/123> Generated by [Test]");
    });

    it("should preserve markdown formatting", () => {
      const result = updateBody({
        currentBody: "# Title\n\n**Bold**",
        newContent: "- List item",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("# Title");
      expect(result).toContain("**Bold**");
      expect(result).toContain("- List item");
    });
  });

  describe("updateBody - prepend operation", () => {
    it("should prepend to empty body", () => {
      const result = updateBody({
        currentBody: "",
        newContent: "New content",
        operation: "prepend",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("---");
      expect(result).toContain("New content");
      // Check for footer elements (uses messages system)
      expect(result).toContain("Test");
      expect(result).toContain("https://github.com/test/actions/runs/123");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("prepend"));
    });

    it("should prepend to existing body", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "New content",
        operation: "prepend",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("Original content");
      expect(result).toContain("New content");
      expect(result.indexOf("New content")).toBeLessThan(result.indexOf("Original content"));
    });

    it("separates prepended content from the generated footer with a blank line", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "run: https://github.com/owner/repo/actions/runs/123",
        operation: "prepend",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });

      expect(result).toContain("run: https://github.com/owner/repo/actions/runs/123\n\n> Generated by [Test]");
      expect(result).not.toContain("runs/123> Generated by [Test]");
    });
  });

  describe("updateBody - replace-island operation", () => {
    it("should create new island when not found", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "Island content",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("Original content");
      expect(result).toContain("Island content");
      expect(result).toContain("<!-- gh-aw-island-start:test-workflow -->");
      expect(result).toContain("<!-- gh-aw-island-end:test-workflow -->");
      // Check for footer elements (uses messages system)
      expect(result).toContain("Test");
      expect(result).toContain("https://github.com/test/actions/runs/123");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("falling back to append"));
    });

    it("should replace existing island content", () => {
      const currentBody = "Before\n<!-- gh-aw-island-start:test-workflow -->\nOld island\n<!-- gh-aw-island-end:test-workflow -->\nAfter";
      const result = updateBody({
        currentBody,
        newContent: "New island",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("Before");
      expect(result).toContain("After");
      expect(result).toContain("New island");
      expect(result).not.toContain("Old island");
      expect(result).toContain("<!-- gh-aw-island-start:test-workflow -->");
      expect(result).toContain("<!-- gh-aw-island-end:test-workflow -->");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("updating existing island"));
    });

    it("separates island content from the generated footer with a blank line", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "run: https://github.com/owner/repo/actions/runs/123",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });

      expect(result).toContain("run: https://github.com/owner/repo/actions/runs/123\n\n> Generated by [Test]");
      expect(result).not.toContain("runs/123> Generated by [Test]");
    });

    it("should preserve content outside island when replacing", () => {
      const currentBody = "# Title\n\nSome intro\n\n<!-- gh-aw-island-start:test-workflow -->\nOld\n<!-- gh-aw-island-end:test-workflow -->\n\n## Footer\n\nMore content";
      const result = updateBody({
        currentBody,
        newContent: "Updated content",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("# Title");
      expect(result).toContain("Some intro");
      expect(result).toContain("## Footer");
      expect(result).toContain("More content");
      expect(result).toContain("Updated content");
      expect(result).not.toContain("Old");
    });

    it("should not replace island with different workflow ID", () => {
      const currentBody = "Before\n<!-- gh-aw-island-start:other-workflow -->\nOther island\n<!-- gh-aw-island-end:other-workflow -->\nAfter";
      const result = updateBody({
        currentBody,
        newContent: "New island",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      // Should append because island test-workflow doesn't exist
      expect(result).toContain("Other island");
      expect(result).toContain("New island");
      expect(result).toContain("<!-- gh-aw-island-start:other-workflow -->");
      expect(result).toContain("<!-- gh-aw-island-start:test-workflow -->");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("falling back to append"));
    });

    it("should handle multiple islands with same workflow ID (replace first)", () => {
      const currentBody = "<!-- gh-aw-island-start:test-workflow -->\nFirst\n<!-- gh-aw-island-end:test-workflow -->\n<!-- gh-aw-island-start:test-workflow -->\nSecond\n<!-- gh-aw-island-end:test-workflow -->";
      const result = updateBody({
        currentBody,
        newContent: "Replaced",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("Replaced");
      // First island should be replaced
      expect(result.indexOf("Replaced")).toBeLessThan(result.indexOf("Second"));
    });

    it("should handle empty island content", () => {
      const currentBody = "Before\n<!-- gh-aw-island-start:test-workflow -->\n\n<!-- gh-aw-island-end:test-workflow -->\nAfter";
      const result = updateBody({
        currentBody,
        newContent: "New content",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("New content");
      expect(result).toContain("Before");
      expect(result).toContain("After");
    });

    it("should handle special characters in island content", () => {
      const currentBody = "<!-- gh-aw-island-start:test-workflow -->\nOld\n<!-- gh-aw-island-end:test-workflow -->";
      const result = updateBody({
        currentBody,
        newContent: "Content with **markdown**, `code`, [links](https://github.com/example/repo)",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("**markdown**");
      expect(result).toContain("`code`");
      expect(result).toContain("[links](https://github.com/example/repo)");
    });

    it("should handle newlines and whitespace correctly", () => {
      const currentBody = "<!-- gh-aw-island-start:test-workflow -->\n  \n\nOld\n\n  \n<!-- gh-aw-island-end:test-workflow -->";
      const result = updateBody({
        currentBody,
        newContent: "New\n\nMultiline\n\nContent",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("New\n\nMultiline\n\nContent");
    });
  });

  describe("updateBody - edge cases", () => {
    it("should handle empty new content", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("Original");
      // Check for footer elements
      expect(result).toContain("Test");
    });

    it("should handle empty current body", () => {
      const result = updateBody({
        currentBody: "",
        newContent: "New",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("New");
    });

    it("should handle unicode characters", () => {
      const result = updateBody({
        currentBody: "Original 你好",
        newContent: "New 世界 🚀",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("你好");
      expect(result).toContain("世界 🚀");
    });

    it("should handle very long content", () => {
      const longContent = "A".repeat(10000);
      const result = updateBody({
        currentBody: "Original",
        newContent: longContent,
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain(longContent);
      expect(result.length).toBeGreaterThan(10000);
    });

    it("should handle default to append for unknown operation", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New",
        operation: "unknown",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("Original");
      expect(result).toContain("New");
      expect(result).toContain("---");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("append"));
    });
  });

  describe("Footer parameter", () => {
    it("appends body footer independently after the generated footer", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "replace",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        includeFooter: true,
        bodyFooter: "Policy footer for {workflow_name}: {run_url}",
      });
      expect(result).toContain("Generated by");
      expect(result).toContain("Policy footer for Test: https://github.com/test/actions/runs/123");
      expect(result.indexOf("Generated by")).toBeLessThan(result.indexOf("Policy footer"));
    });

    it("appends body footer when the generated footer is disabled", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "replace",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        includeFooter: false,
        bodyFooter: "Required policy footer",
      });
      expect(result).not.toContain("Generated by");
      expect(result).toContain("Required policy footer");
    });

    it("should omit footer when includeFooter is false", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        includeFooter: false,
      });
      expect(result).toContain("Original");
      expect(result).toContain("New content");
      expect(result).not.toContain("Generated by");
      expect(result).not.toContain("AI generated");
    });

    it("should include footer by default when includeFooter is not specified", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        // includeFooter not specified, should default to true
      });
      expect(result).toContain("Original");
      expect(result).toContain("New content");
      expect(result).toContain("Generated by");
    });

    it("should include footer when includeFooter is explicitly true", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        includeFooter: true,
      });
      expect(result).toContain("Original");
      expect(result).toContain("New content");
      expect(result).toContain("Generated by");
    });

    it("should omit footer in replace operation when includeFooter is false", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "Replacement",
        operation: "replace",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        includeFooter: false,
      });
      expect(result).toBe("Replacement\n\n<!-- gh-aw-workflow-id: test-workflow -->");
      expect(result).not.toContain("Generated by");
    });

    it("should omit footer in prepend operation when includeFooter is false", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "Prepended",
        operation: "prepend",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        includeFooter: false,
      });
      expect(result).toContain("Prepended");
      expect(result).toContain("Original");
      expect(result).not.toContain("Generated by");
    });

    it("should omit footer in replace-island operation when includeFooter is false", () => {
      const currentBody = "Before\n<!-- gh-aw-island-start:test-workflow -->\nOld island\n<!-- gh-aw-island-end:test-workflow -->\nAfter";
      const result = updateBody({
        currentBody,
        newContent: "New island",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        includeFooter: false,
      });
      expect(result).toContain("Before");
      expect(result).toContain("New island");
      expect(result).toContain("After");
      expect(result).not.toContain("Generated by");
      expect(result).toContain("<!-- gh-aw-island-start:test-workflow -->");
      expect(result).toContain("<!-- gh-aw-island-end:test-workflow -->");
    });
  });

  describe("historyUrl parameter", () => {
    it("should pass historyUrl to the footer when provided", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
        historyUrl: "https://github.com/search?q=test",
      });
      expect(result).toContain("New content");
      // historyUrl should be included in the footer
      expect(result).toContain("https://github.com/search?q=test");
    });

    it("should work without historyUrl (optional parameter)", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "test-workflow",
      });
      expect(result).toContain("New content");
      expect(result).toContain("Original");
    });
  });

  describe("workflowIdMarker - includeFooter false", () => {
    it("should include workflow ID marker when includeFooter is false and workflowId is provided", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "my-workflow",
        includeFooter: false,
      });
      expect(result).toContain("<!-- gh-aw-workflow-id: my-workflow -->");
    });

    it("should not include workflow ID marker when includeFooter is false and workflowId is empty", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        workflowId: "",
        includeFooter: false,
      });
      expect(result).not.toContain("gh-aw-workflow-id");
    });
  });
});
