import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock the global objects that GitHub Actions provides
const mockCore = {
  debug: vi.fn(),
  info: vi.fn(),
  notice: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  setFailed: vi.fn(),
  setOutput: vi.fn(),
  summary: {
    addRaw: vi.fn().mockReturnThis(),
    write: vi.fn().mockResolvedValue(),
  },
};

const mockGithub = {
  rest: {
    issues: {
      get: vi.fn(),
      update: vi.fn(),
    },
  },
  graphql: vi.fn(),
};

const mockContext = {
  eventName: "issues",
  repo: {
    owner: "testowner",
    repo: "testrepo",
  },
  serverUrl: "https://github.com",
  runId: 12345,
  payload: {
    issue: {
      number: 100,
    },
  },
};

// Set up global mocks
global.core = mockCore;
global.github = mockGithub;
global.context = mockContext;

describe("update_issue.cjs - footer support", () => {
  beforeEach(async () => {
    // Reset all mocks before each test
    vi.clearAllMocks();
    vi.resetModules();

    // Reset environment variables
    process.env.GH_AW_WORKFLOW_NAME = "Test Workflow";
    process.env.GH_AW_WORKFLOW_ID = "test-workflow";

    // Reset mock implementations
    mockGithub.rest.issues.get.mockResolvedValue({
      data: {
        number: 100,
        title: "Test Issue",
        body: "Original body content",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });

    mockGithub.rest.issues.update.mockResolvedValue({
      data: {
        number: 100,
        title: "Test Issue",
        body: "Updated body",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });
    mockGithub.graphql.mockResolvedValue({
      updateIssue: {
        issue: {
          id: "I_kwDO_testissue",
          labels: { nodes: [] },
        },
      },
    });
  });

  describe("Footer addition", () => {
    it("should add footer by default when no operation is specified", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      // When no operation is specified, it should default to "append" and add footer
      const expectedBody = `Original content\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain("---");
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
      expect(expectedBody).toContain("[Test Workflow]");
      // Original content should come first
      expect(expectedBody.indexOf("Original content")).toBeLessThan(expectedBody.indexOf(newContent));
    });

    it("should add footer when using append operation", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content to append";
      const expectedBody = `Original content\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Verify expected body contains all required parts
      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain("---");
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
      expect(expectedBody).toContain("[Test Workflow]");
      // Original content should come first
      expect(expectedBody.indexOf("Original content")).toBeLessThan(expectedBody.indexOf(newContent));
    });

    it("should add footer when using prepend operation", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content to prepend";
      const expectedBody = `${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\nOriginal content`;

      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
      expect(expectedBody).toContain("[Test Workflow]");
      // New content should come first
      expect(expectedBody.indexOf(newContent)).toBeLessThan(expectedBody.indexOf("Original content"));
    });

    it("should use custom workflow name from environment", async () => {
      process.env.GH_AW_WORKFLOW_NAME = "Custom Issue Workflow";

      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [Custom Issue Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Custom Issue Workflow");
      expect(expectedBody).not.toContain("Test Workflow");
    });

    it("should use default workflow name when not set", async () => {
      delete process.env.GH_AW_WORKFLOW_NAME;

      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [GitHub Agentic Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("GitHub Agentic Workflow");
    });

    it("should handle null body as empty string", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: null,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Should work same as empty string
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
    });
  });

  describe("Replace-island operation", () => {
    it("should create new island when not found", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "Island content";
      const expectedBody = `Original content\n\n---\n\n<!-- gh-aw-island-start:test-workflow -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:test-workflow -->`;

      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain("Island content");
      expect(expectedBody).toContain("<!-- gh-aw-island-start:test-workflow -->");
      expect(expectedBody).toContain("<!-- gh-aw-island-end:test-workflow -->");
      expect(expectedBody).toContain("> AI generated by");
    });

    it("should replace existing island content", async () => {
      const existingBody = "Before\n<!-- gh-aw-island-start:test-workflow -->\nOld island\n<!-- gh-aw-island-end:test-workflow -->\nAfter";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: existingBody,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New island";
      const expectedBody = `Before\n<!-- gh-aw-island-start:test-workflow -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:test-workflow -->\nAfter`;

      expect(expectedBody).toContain("Before");
      expect(expectedBody).toContain("After");
      expect(expectedBody).toContain("New island");
      expect(expectedBody).not.toContain("Old island");
      expect(expectedBody).toContain("> AI generated by");
    });
  });

  describe("Replace operation", () => {
    it("should replace entire body and add footer", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original content that will be completely replaced",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "Completely new body content";
      const expectedBody = `${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // With replace operation, the original body is completely replaced but footer is added
      expect(expectedBody).not.toContain("Original content");
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
      expect(expectedBody).toContain("[Test Workflow]");
    });
  });

  describe("Edge cases and special content", () => {
    it("should handle very long content in append", async () => {
      const longContent = "A".repeat(10000);
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const expectedBody = `Original\n\n---\n\n${longContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain(longContent);
      expect(expectedBody.length).toBeGreaterThan(10000);
    });

    it("should handle unicode and emoji characters", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original 你好",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content 世界 🚀 🎉";
      const expectedBody = `Original 你好\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("你好");
      expect(expectedBody).toContain("世界 🚀 🎉");
    });

    it("should handle markdown code blocks", async () => {
      const codeBlock = "```javascript\nconst x = 1;\nconsole.log(x);\n```";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: codeBlock,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${codeBlock}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("```javascript");
      expect(expectedBody).toContain("const x = 1;");
      expect(expectedBody).toContain("```");
    });

    it("should handle markdown tables", async () => {
      const table = "| Column 1 | Column 2 |\n|----------|----------|\n| Value 1  | Value 2  |";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: table,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${table}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("| Column 1 | Column 2 |");
      expect(expectedBody).toContain("| Value 1  | Value 2  |");
    });

    it("should handle HTML comments in body", async () => {
      const bodyWithComments = "Content\n<!-- HTML comment -->\nMore content";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: bodyWithComments,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${bodyWithComments}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("<!-- HTML comment -->");
      expect(expectedBody).toContain("More content");
    });

    it("should handle task lists", async () => {
      const taskList = "## Tasks\n- [x] Completed task\n- [ ] Pending task\n- [x] Another completed";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: taskList,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${taskList}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("- [x] Completed task");
      expect(expectedBody).toContain("- [ ] Pending task");
    });

    it("should handle content with multiple separators", async () => {
      const bodyWithSeparators = "Content 1\n\n---\n\nContent 2\n\n---\n\nContent 3";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: bodyWithSeparators,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `${bodyWithSeparators}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Should have 2 existing separators + 1 new = 3 total
      const separatorCount = (expectedBody.match(/---/g) || []).length;
      expect(separatorCount).toBe(3);
    });

    it("should handle empty string content", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Original");
      expect(expectedBody).toContain("> AI generated by");
    });

    it("should handle content with newlines at boundaries", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original\n\n\n",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "\n\nNew content\n\n";
      const expectedBody = `Original\n\n\n\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Original");
      expect(expectedBody).toContain("New content");
    });

    it("should handle special markdown characters", async () => {
      const specialChars = "Content with *asterisks*, _underscores_, and `backticks`";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: specialChars,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New [link](http://example.com) and **bold**";
      const expectedBody = `${specialChars}\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("*asterisks*");
      expect(expectedBody).toContain("_underscores_");
      expect(expectedBody).toContain("`backticks`");
      expect(expectedBody).toContain("[link](http://example.com)");
      expect(expectedBody).toContain("**bold**");
    });

    it("should handle multiple islands with different run IDs in replace-island", async () => {
      const existingBody = "<!-- gh-aw-island-start:99999 -->\nOther island\n<!-- gh-aw-island-end:99999 -->";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: existingBody,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New island";
      // Should append because island with workflow test-workflow doesn't exist
      const expectedBody = `${existingBody}\n\n---\n\n<!-- gh-aw-island-start:test-workflow -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:test-workflow -->`;

      expect(expectedBody).toContain("Other island");
      expect(expectedBody).toContain("New island");
      expect(expectedBody).toContain("<!-- gh-aw-island-start:99999 -->");
      expect(expectedBody).toContain("<!-- gh-aw-island-start:test-workflow -->");
    });

    it("should preserve content outside island when replacing", async () => {
      const existingBody = "# Title\n\n<!-- gh-aw-island-start:test-workflow -->\nOld\n<!-- gh-aw-island-end:test-workflow -->\n\n## Footer";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: existingBody,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "Updated content";
      const expectedBody = `# Title\n\n<!-- gh-aw-island-start:test-workflow -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:test-workflow -->\n\n## Footer`;

      expect(expectedBody).toContain("# Title");
      expect(expectedBody).toContain("## Footer");
      expect(expectedBody).toContain("Updated content");
      expect(expectedBody).not.toContain("Old");
    });
  });
});

describe("update_issue.cjs - allow_body configuration", () => {
  beforeEach(async () => {
    // Reset all mocks before each test
    vi.clearAllMocks();
    vi.resetModules();
  });

  it("should allow body updates when allow_body is true", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = {
      body: "New body content",
    };

    const config = {
      allow_body: true,
    };

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(true);
    expect(result.data._rawBody).toBe("New body content");
    expect(result.data._operation).toBe("append");
  });

  it("should allow body updates when allow_body is not specified (defaults to true)", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = {
      body: "New body content",
    };

    const config = {};

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(true);
    expect(result.data._rawBody).toBe("New body content");
    expect(result.data._operation).toBe("append");
  });

  it("should block body updates when allow_body is false", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = {
      body: "New body content",
    };

    const config = {
      allow_body: false,
    };

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(true);
    expect(result.data._rawBody).toBeUndefined();
    expect(result.data._operation).toBeUndefined();
    expect(mockCore.warning).toHaveBeenCalledWith("Body update not allowed by safe-outputs configuration");
  });

  it("should still allow other fields when body is blocked", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = {
      title: "New Title",
      body: "New body content",
      status: "closed",
      labels: ["bug", "enhancement"],
    };

    const config = {
      allow_body: false,
    };

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(true);
    expect(result.data.title).toBe("New Title");
    expect(result.data.state).toBe("closed");
    expect(result.data.labels).toEqual(["bug", "enhancement"]);
    expect(result.data._rawBody).toBeUndefined();
    expect(mockCore.warning).toHaveBeenCalledWith("Body update not allowed by safe-outputs configuration");
  });

  it("should respect allow_body true with explicit operation", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = {
      body: "New body content",
      operation: "prepend",
    };

    const config = {
      allow_body: true,
    };

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(true);
    expect(result.data._rawBody).toBe("New body content");
    expect(result.data._operation).toBe("prepend");
  });

  it("should block body update even with explicit operation when allow_body is false", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = {
      body: "New body content",
      operation: "replace",
    };

    const config = {
      allow_body: false,
    };

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(true);
    expect(result.data._rawBody).toBeUndefined();
    expect(result.data._operation).toBeUndefined();
    expect(mockCore.warning).toHaveBeenCalledWith("Body update not allowed by safe-outputs configuration");
  });

  it("should enforce max labels limit (SEC-003)", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = {
      labels: [
        "label1",
        "label2",
        "label3",
        "label4",
        "label5",
        "label6",
        "label7",
        "label8",
        "label9",
        "label10",
        "label11", // 11th label exceeds limit
      ],
    };

    const config = {};

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(false);
    expect(result.error).toContain("E003");
    expect(result.error).toContain("Cannot add more than 10 labels");
    expect(result.error).toContain("received 11");
  });

  it("should enforce max assignees limit (SEC-003)", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = {
      assignees: ["user1", "user2", "user3", "user4", "user5", "user6"], // 6 assignees exceeds limit of 5
    };

    const config = {};

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(false);
    expect(result.error).toContain("E003");
    expect(result.error).toContain("Cannot add more than 5 assignees");
    expect(result.error).toContain("received 6");
  });
});

describe("update_issue.cjs - title_prefix configuration", () => {
  beforeEach(async () => {
    vi.resetAllMocks();
    vi.resetModules();
  });

  it("should store _titlePrefix in updateData when title_prefix is configured", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = { body: "New content" };
    const config = { title_prefix: "[bot] " };

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(true);
    expect(result.data._titlePrefix).toBe("[bot] ");
  });

  it("should not set _titlePrefix when title_prefix is not configured", async () => {
    const { buildIssueUpdateData } = await import("./update_issue.cjs");

    const item = { body: "New content" };
    const config = {};

    const result = buildIssueUpdateData(item, config);

    expect(result.success).toBe(true);
    expect(result.data._titlePrefix).toBeUndefined();
  });

  it("should validate title prefix and succeed when issue title starts with prefix", async () => {
    // The same issue snapshot is used for both before-state capture and the
    // executeIssueUpdate title/body fetch in this path.
    mockGithub.rest.issues.get.mockResolvedValue({
      data: {
        number: 100,
        title: "[bot] Fix something",
        body: "Original body",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });
    mockGithub.rest.issues.update.mockResolvedValueOnce({
      data: {
        number: 100,
        title: "[bot] Fix something",
        body: "Updated",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ title_prefix: "[bot] ", allow_body: true });

    const message = { issue_number: 100, body: "Updated" };
    const result = await handler(message, {});

    expect(result.success).toBe(true);
    expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("Title prefix validation passed"));
  });

  it("should reject update when issue title does not start with required prefix", async () => {
    // The handler may read the issue more than once; returning the same
    // mismatched title keeps the prefix-validation failure deterministic.
    mockGithub.rest.issues.get.mockResolvedValue({
      data: {
        number: 100,
        title: "Some other issue",
        body: "Original body",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ title_prefix: "[bot] ", allow_body: true });

    const message = { issue_number: 100, body: "Updated" };
    const result = await handler(message, {});

    expect(result.success).toBe(false);
    expect(result.error).toContain("[bot] ");
    expect(result.error).toContain("Some other issue");
    // Should not call update API
    expect(mockGithub.rest.issues.update).not.toHaveBeenCalled();
  });
});

describe("update_issue.cjs - cross-repo and operation integration", () => {
  beforeEach(async () => {
    vi.clearAllMocks();
    vi.resetModules();
    process.env.GH_AW_WORKFLOW_NAME = "Test Workflow";
    process.env.GH_AW_WORKFLOW_ID = "test-workflow";
  });

  it("should route API calls to the cross-repo target when repo field is provided", async () => {
    let capturedOwner, capturedRepo;

    mockGithub.rest.issues.get.mockImplementation(async ({ owner, repo, issue_number }) => ({
      data: { number: issue_number, title: "Cross-repo Issue", body: "Original", html_url: `https://github.com/${owner}/${repo}/issues/${issue_number}` },
    }));
    mockGithub.rest.issues.update.mockImplementation(async ({ owner, repo, issue_number, ...data }) => {
      capturedOwner = owner;
      capturedRepo = repo;
      return { data: { number: issue_number, title: "Cross-repo Issue", body: data.body, html_url: `https://github.com/${owner}/${repo}/issues/${issue_number}` } };
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({
      "target-repo": "other-owner/other-repo",
      allowed_repos: ["other-owner/other-repo"],
      target: "*",
    });

    const result = await handler({ issue_number: 42, repo: "other-owner/other-repo", body: "New content" }, {});

    expect(result.success).toBe(true);
    expect(capturedOwner).toBe("other-owner");
    expect(capturedRepo).toBe("other-repo");
  });

  it("should resolve triggering issue from workflow_dispatch aw_context", async () => {
    const savedEventName = mockContext.eventName;
    const savedPayload = mockContext.payload;
    mockContext.eventName = "workflow_dispatch";
    mockContext.payload = {
      inputs: {
        aw_context: JSON.stringify({
          event_type: "issue_comment",
          item_type: "issue",
          item_number: 123,
          repo: "testowner/testrepo",
        }),
      },
    };
    let capturedIssueNumber;

    mockGithub.rest.issues.get.mockResolvedValue({
      data: { number: 123, title: "Test", body: "Original", html_url: "https://github.com/testowner/testrepo/issues/123" },
    });
    mockGithub.rest.issues.update.mockImplementation(async ({ issue_number, body }) => {
      capturedIssueNumber = issue_number;
      return { data: { number: issue_number, title: "Test", body, html_url: `https://github.com/testowner/testrepo/issues/${issue_number}` } };
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main();
    const result = await handler({ body: "Updated from centralized dispatch" }, {});

    expect(result.success).toBe(true);
    expect(capturedIssueNumber).toBe(123);
    mockContext.eventName = savedEventName;
    mockContext.payload = savedPayload;
  });

  it("should use current workflow repo in attribution URL for cross-repo updates", async () => {
    let capturedBody;

    mockGithub.rest.issues.get.mockResolvedValue({
      data: { number: 42, title: "Cross-repo Issue", body: "Original", html_url: "https://github.com/other-owner/other-repo/issues/42" },
    });
    mockGithub.rest.issues.update.mockImplementation(async ({ body }) => {
      capturedBody = body;
      return { data: { number: 42, title: "Cross-repo Issue", body, html_url: "https://github.com/other-owner/other-repo/issues/42" } };
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({
      "target-repo": "other-owner/other-repo",
      allowed_repos: ["other-owner/other-repo"],
      target: "*",
    });

    await handler({ issue_number: 42, repo: "other-owner/other-repo", operation: "replace", body: "New content" }, {});

    // Attribution URL must reference the current workflow's repo, not the cross-repo target
    expect(capturedBody).toContain("testowner/testrepo/actions/runs/12345");
    expect(capturedBody).not.toContain("other-owner/other-repo/actions/runs/12345");
  });

  it("should apply 'append' operation: new content added after existing body", async () => {
    let capturedBody;

    mockGithub.rest.issues.get.mockResolvedValue({
      data: { number: 100, title: "Test", body: "Existing body", html_url: "https://github.com/testowner/testrepo/issues/100" },
    });
    mockGithub.rest.issues.update.mockImplementation(async ({ body }) => {
      capturedBody = body;
      return { data: { number: 100, title: "Test", body, html_url: "https://github.com/testowner/testrepo/issues/100" } };
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ target: "*" });
    await handler({ issue_number: 100, operation: "append", body: "Appended content" }, {});

    expect(capturedBody).toContain("Existing body");
    expect(capturedBody).toContain("Appended content");
    expect(capturedBody.indexOf("Existing body")).toBeLessThan(capturedBody.indexOf("Appended content"));
  });

  it("should apply 'replace' operation: old content replaced by new content", async () => {
    let capturedBody;

    mockGithub.rest.issues.get.mockResolvedValue({
      data: { number: 100, title: "Test", body: "Old body to replace", html_url: "https://github.com/testowner/testrepo/issues/100" },
    });
    mockGithub.rest.issues.update.mockImplementation(async ({ body }) => {
      capturedBody = body;
      return { data: { number: 100, title: "Test", body, html_url: "https://github.com/testowner/testrepo/issues/100" } };
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ target: "*" });
    await handler({ issue_number: 100, operation: "replace", body: "Replacement content" }, {});

    expect(capturedBody).not.toContain("Old body to replace");
    expect(capturedBody).toContain("Replacement content");
  });

  it("should apply 'prepend' operation: new content placed before existing body", async () => {
    let capturedBody;

    mockGithub.rest.issues.get.mockResolvedValue({
      data: { number: 100, title: "Test", body: "Existing body", html_url: "https://github.com/testowner/testrepo/issues/100" },
    });
    mockGithub.rest.issues.update.mockImplementation(async ({ body }) => {
      capturedBody = body;
      return { data: { number: 100, title: "Test", body, html_url: "https://github.com/testowner/testrepo/issues/100" } };
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ target: "*" });
    await handler({ issue_number: 100, operation: "prepend", body: "Prepended content" }, {});

    expect(capturedBody).toContain("Existing body");
    expect(capturedBody).toContain("Prepended content");
    expect(capturedBody.indexOf("Prepended content")).toBeLessThan(capturedBody.indexOf("Existing body"));
  });

  it("should apply 'replace-island' operation: only the island section is updated", async () => {
    const existingBody = "Header\n<!-- gh-aw-island-start:test-workflow -->\nOld island\n<!-- gh-aw-island-end:test-workflow -->\nFooter";
    let capturedBody;

    mockGithub.rest.issues.get.mockResolvedValue({
      data: { number: 100, title: "Test", body: existingBody, html_url: "https://github.com/testowner/testrepo/issues/100" },
    });
    mockGithub.rest.issues.update.mockImplementation(async ({ body }) => {
      capturedBody = body;
      return { data: { number: 100, title: "Test", body, html_url: "https://github.com/testowner/testrepo/issues/100" } };
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ target: "*" });
    await handler({ issue_number: 100, operation: "replace-island", body: "New island content" }, {});

    expect(capturedBody).toContain("Header");
    expect(capturedBody).toContain("Footer");
    expect(capturedBody).toContain("New island content");
    expect(capturedBody).not.toContain("Old island");
    expect(capturedBody).toContain("<!-- gh-aw-island-start:test-workflow -->");
    expect(capturedBody).toContain("<!-- gh-aw-island-end:test-workflow -->");
  });

  it("should update labels via issue intents GraphQL without requiring a runtime feature", async () => {
    let capturedRestBody;

    mockGithub.rest.issues.get.mockResolvedValue({
      data: {
        number: 100,
        node_id: "I_kwDO_testissue",
        title: "Test",
        body: "Existing body",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });
    mockGithub.rest.issues.update.mockImplementation(async ({ body, labels }) => {
      capturedRestBody = { body, labels };
      return {
        data: {
          number: 100,
          node_id: "I_kwDO_testissue",
          title: "Test",
          body,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      };
    });
    mockGithub.graphql.mockImplementation(async (query, variables) => {
      if (query.includes("repository(owner")) {
        return {
          repository: {
            labels: {
              nodes: [
                { id: "LA_bug", name: "bug" },
                { id: "LA_perf", name: "perf" },
              ],
              pageInfo: { hasNextPage: false, endCursor: null },
            },
          },
        };
      }
      if (query.includes("updateIssue(input: { id: $issueId, labels: $labels })")) {
        return {
          updateIssue: {
            issue: {
              id: variables.issueId,
              labels: {
                nodes: [{ name: "bug" }, { name: "perf" }],
              },
            },
          },
        };
      }
      return {};
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ target: "*" });
    const result = await handler(
      {
        issue_number: 100,
        labels: [
          { name: "bug", rationale: "Stack trace matches a known crash path", confidence: "high" },
          { name: "perf", rationale: "Slow query mentioned in repro steps", confidence: "medium", suggest: true },
        ],
      },
      {}
    );

    expect(result.success).toBe(true);
    expect(capturedRestBody).toBeUndefined();
    expect(mockGithub.graphql).toHaveBeenCalledWith(
      expect.stringContaining("labels: $labels"),
      expect.objectContaining({
        issueId: "I_kwDO_testissue",
        labels: [
          {
            labelId: "LA_bug",
            rationale: "Stack trace matches a known crash path",
            confidence: "HIGH",
          },
          {
            labelId: "LA_perf",
            rationale: "Slow query mentioned in repro steps",
            confidence: "MEDIUM",
            suggest: true,
          },
        ],
        headers: { "GraphQL-Features": "update_issue_suggestions" },
      })
    );
  });

  it("should fail before REST update when a label does not exist in the repository", async () => {
    mockGithub.rest.issues.get.mockResolvedValue({
      data: {
        number: 100,
        node_id: "I_kwDO_testissue",
        title: "Test",
        body: "Existing body",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });
    mockGithub.graphql.mockImplementation(async (query, _variables) => {
      if (query.includes("repository(owner")) {
        return {
          repository: {
            labels: {
              nodes: [{ id: "LA_bug", name: "bug" }],
              pageInfo: { hasNextPage: false, endCursor: null },
            },
          },
        };
      }
      return {};
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ target: "*" });
    const result = await handler(
      {
        issue_number: 100,
        title: "New title",
        labels: ["nonexistent-label"],
      },
      {}
    );

    expect(result.success).toBe(false);
    expect(result.error).toMatch(/nonexistent-label/);
    // REST update must NOT have been called — no partial write
    expect(mockGithub.rest.issues.update).not.toHaveBeenCalled();
  });

  it("should update string labels via GraphQL without optional intent metadata", async () => {
    let capturedRestBody;

    mockGithub.rest.issues.get.mockResolvedValue({
      data: {
        number: 100,
        node_id: "I_kwDO_testissue",
        title: "Test",
        body: "Existing body",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });
    mockGithub.rest.issues.update.mockImplementation(async ({ body, labels }) => {
      capturedRestBody = { body, labels };
      return {
        data: {
          number: 100,
          node_id: "I_kwDO_testissue",
          title: "Test",
          body,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      };
    });
    mockGithub.graphql.mockImplementation(async (query, variables) => {
      if (query.includes("repository(owner")) {
        return {
          repository: {
            labels: {
              nodes: [{ id: "LA_bug", name: "bug" }],
              pageInfo: { hasNextPage: false, endCursor: null },
            },
          },
        };
      }
      if (query.includes("updateIssue(input: { id: $issueId, labels: $labels })")) {
        return {
          updateIssue: {
            issue: {
              id: variables.issueId,
              labels: {
                nodes: [{ name: "bug" }],
              },
            },
          },
        };
      }
      return {};
    });

    const { main } = await import("./update_issue.cjs");
    const handler = await main({ target: "*" });
    const result = await handler(
      {
        issue_number: 100,
        labels: ["bug"],
      },
      {}
    );

    expect(result.success).toBe(true);
    expect(capturedRestBody).toBeUndefined();
    expect(mockGithub.graphql).toHaveBeenCalledWith(
      expect.stringContaining("labels: $labels"),
      expect.objectContaining({
        issueId: "I_kwDO_testissue",
        labels: [{ labelId: "LA_bug" }],
        headers: { "GraphQL-Features": "update_issue_suggestions" },
      })
    );
  });
});
