package workflow

import (
	"fmt"
	"sort"
	"strings"

	"github.com/github/gh-aw/pkg/constants"
	"github.com/github/gh-aw/pkg/logger"
	"github.com/github/gh-aw/pkg/sliceutil"
	"github.com/github/gh-aw/pkg/stringutil"
)

var consolidatedSafeOutputsStepsLog = logger.New("workflow:compiler_safe_outputs_steps")

// buildSharedPRCheckoutSteps builds checkout and git-configuration steps for the
// safe_outputs job's create-pull-request / push-to-pull-request-branch operations.
//
// The checkout steps are generated by the SAME CheckoutManager generators the agent job
// uses (GenerateCheckoutAppTokenSteps, GenerateDefaultCheckoutStep,
// GenerateAdditionalCheckoutSteps), so the safe_outputs job lays out every repository on
// disk identically to the agent job. The only safe_outputs-specific differences are:
//   - a per-step `if:` condition gating the steps on whether a create_pull_request /
//     push_to_pull_request_branch output will actually be processed, and
//   - a trailing "Configure Git credentials" step that installs a push-capable token
//     (the agent job never pushes, so it omits this).
//
// Base-branch selection is intentionally NOT done here. The JS handler resolves the base
// branch per target repository at apply time (it runs `git fetch origin <base>` and
// branches from `origin/<base>` in the target repo's directory), so a checkout-time base
// ref is unnecessary. This is the same mechanism the multi-repo path already relied on.
func (c *Compiler) buildSharedPRCheckoutSteps(data *WorkflowData) []string {
	consolidatedSafeOutputsStepsLog.Print("Building shared PR checkout steps (mirroring agent job layout)")

	// Build the same CheckoutManager the agent job builds from the workflow's checkout: config.
	checkoutMgr := NewCheckoutManager(data.CheckoutConfigs)

	// Unlike the agent job, the safe_outputs job performs git fetch/push against the
	// checked-out repositories (create_pull_request, push_to_pull_request_branch), so its
	// checkouts must retain credentials (persist-credentials: true) instead of stripping
	// them. This keeps the push-capable token on disk for the handlers; the trusted
	// safe_outputs handler code (not the untrusted agent) is the only consumer.
	checkoutMgr.SetKeepCredentialsForPush(true)

	// Persist the resolved PR push token (not just the default GITHUB_TOKEN) into
	// .git/config so the retained credential matches the token the handlers use to
	// fetch/push. This keeps a single, correct Authorization header on the wire and
	// removes the need for the handlers to inject a separate http.extraheader. The
	// same token is reused below for the "Configure Git credentials" step so both the
	// persisted checkout credential and the push remote agree on a single token.
	prCheckoutToken, _ := resolvePRCheckoutToken(data.SafeOutputs, checkoutMgr)
	checkoutMgr.SetPushToken(resolveStaticCheckoutToken(data.SafeOutputs, checkoutMgr))

	// The default workspace checkout is skipped below when permissions.contents: none
	// signals a target-only checkout; suppress its app-token minting step too.
	checkoutMgr.SetSkipDefaultCheckout(data.CheckoutSkipDefault)

	// Combined condition: run the checkout/git-config steps only when a create_pull_request
	// or push_to_pull_request_branch output will be processed.
	condition := buildPRCheckoutCondition(data.SafeOutputs)

	var steps []string

	// Mint checkout app tokens (identical to the agent job) when any checkout uses app auth.
	// These must live in the safe_outputs job because the minted token is referenced by the
	// checkout steps via ${{ steps.checkout-app-token-N.outputs.token }} within the same job.
	//
	// Token minting uses resolveCheckoutAppTokenPermissions so explicit target checkouts
	// keep a valid contents: read token even when permissions.contents: none suppresses
	// the default workflow-repository checkout. The suppressed default checkout entry
	// itself mints no token (SetSkipDefaultCheckout above).
	if checkoutMgr.HasAppAuth() {
		steps = append(steps, injectStepCondition(checkoutMgr.GenerateCheckoutAppTokenSteps(c, resolveCheckoutAppTokenPermissions(data)), condition)...)
	}
	if checkoutMgr.HasSafeOutputAppAuth() {
		steps = append(steps, checkoutMgr.GenerateSafeOutputCheckoutAppTokenSteps(c, resolveCheckoutAppTokenPermissions(data))...)
	}

	// Default workspace checkout (identical to the agent job). Skipped when
	// permissions.contents: none signals a target-only checkout (see
	// Compiler.shouldAddCheckoutStep for the equivalent agent-job gating); the
	// hosting repository is then never cloned (or credentialed) in either job.
	if !data.CheckoutSkipDefault {
		steps = append(steps, injectStepCondition(
			checkoutMgr.GenerateDefaultCheckoutStep(c.trialMode, c.trialLogicalRepoSlug, c.getActionPin),
			condition,
		)...)
	}

	// Additional (cross-repo / subdirectory) checkouts (identical to the agent job).
	steps = append(steps, injectStepCondition(
		checkoutMgr.GenerateAdditionalCheckoutSteps(c.getActionPin),
		condition,
	)...)

	// Configure Git credentials so the safe_outputs job can push. The agent job never
	// pushes, so this step has no agent-job equivalent. Reuse the token resolved above so
	// the push remote and the persisted checkout credential use the same token.
	steps = append(steps, checkoutMgr.GenerateConfigureGitCredentialsSteps(prCheckoutToken, condition)...)

	consolidatedSafeOutputsStepsLog.Printf("Built shared PR checkout steps with condition: %s", condition.Render())
	return steps
}

// buildHandlerManagerStep builds a single step that uses the safe output handler manager
// to dispatch messages to appropriate handlers. This replaces multiple individual steps
// with a single dispatcher step that processes all safe output types.
func (c *Compiler) buildHandlerManagerStep(data *WorkflowData) ([]string, error) {
	consolidatedSafeOutputsStepsLog.Print("Building handler manager step")

	var steps []string

	steps = append(steps, c.addAppTokenMintingSteps(data)...)

	// Step name and metadata
	steps = append(steps, "      - name: Process Safe Outputs\n")
	steps = append(steps, "        id: process_safe_outputs\n")
	steps = append(steps, fmt.Sprintf("        uses: %s\n", getCachedActionPin("actions/github-script", data)))

	// Environment variables
	steps = append(steps, "        env:\n")
	if err := c.addSafeOutputCoreEnvVars(&steps, data); err != nil {
		return nil, err
	}
	c.addSafeOutputTokenEnvVars(&steps, data)

	// With section for github-token
	// Use the standard safe-outputs token for the shared github-script client.
	// Project operations use GH_AW_PROJECT_GITHUB_TOKEN from env with dedicated handler logic.
	steps = append(steps, "        with:\n")
	// Token precedence for the handler manager step:
	//   1. Safe-outputs level token (so.GitHubToken)
	//   2. Magic secret fallback via resolveSafeOutputGitHubToken()
	//
	// Note: We do NOT fall back to per-output tokens (add-comment, create-issue, etc.)
	// because those are specific to their operations. The handler manager needs a
	// general-purpose token for the github-script client.
	configToken := ""
	if data.SafeOutputs != nil && data.SafeOutputs.GitHubToken != "" {
		configToken = data.SafeOutputs.GitHubToken
	}
	c.addSafeOutputGitHubTokenForConfig(&steps, data, configToken)

	steps = append(steps, "          script: |\n")
	steps = append(steps, generateGitHubScriptWithRequire("process_safe_outputs.cjs"))

	return steps, nil
}

// addAppTokenMintingSteps adds per-handler and dispatch-repository GitHub App token minting
// steps that must precede the handler manager step. For each registered handler that has a
// per-handler github-app configured, a dedicated token step is minted whose permissions are
// scoped to only that handler's needs (principle of least privilege).
func (c *Compiler) addAppTokenMintingSteps(data *WorkflowData) []string {
	if data.SafeOutputs == nil {
		return nil
	}

	var steps []string

	// Per-handler GitHub App tokens: each registered handler may declare its own app.
	for _, handler := range safeOutputHandlers {
		if handler.StructField == "" {
			continue
		}
		handlerApp := getHandlerGitHubApp(data.SafeOutputs, handler.StructField)
		if handlerApp == nil || handler.PermissionBuilder == nil {
			continue
		}
		handlerPermissions := handler.PermissionBuilder(data.SafeOutputs)
		if handlerPermissions == nil {
			continue
		}
		stepID := handler.Key + "-app-token"
		consolidatedSafeOutputsStepsLog.Printf("Adding per-handler GitHub App token minting step for %s", handler.Key)
		steps = append(steps, c.buildGitHubAppTokenMintStepWithMeta(
			handlerApp,
			handlerPermissions,
			"",
			"",
			fmt.Sprintf("Generate GitHub App token (%s)", handler.Key),
			stepID,
		)...)
	}
	if commentMemory := data.CommentMemoryConfig; commentMemory != nil && commentMemory.GitHubApp != nil &&
		!isHandlerStaged(templatableBoolIsTrue(data.SafeOutputs.Staged), commentMemory.Staged) {
		steps = append(steps, c.buildGitHubAppTokenMintStepWithMeta(
			commentMemory.GitHubApp,
			NewPermissionsIssuesWrite(),
			"",
			"",
			"Generate GitHub App token (comment-memory)",
			"comment-memory-app-token",
		)...)
	}

	// Dispatch-repository tool tokens: each non-staged tool with a github-app gets a token step.
	if data.SafeOutputs.DispatchRepository != nil && len(data.SafeOutputs.DispatchRepository.Tools) > 0 {
		toolKeys := make([]string, 0, len(data.SafeOutputs.DispatchRepository.Tools))
		for toolKey := range data.SafeOutputs.DispatchRepository.Tools {
			toolKeys = append(toolKeys, toolKey)
		}
		sort.Strings(toolKeys)
		globalStaged := templatableBoolIsTrue(data.SafeOutputs.Staged)
		for _, toolKey := range toolKeys {
			tool := data.SafeOutputs.DispatchRepository.Tools[toolKey]
			if tool == nil || tool.GitHubApp == nil || isHandlerStaged(globalStaged, tool.Staged) {
				continue
			}
			stepID := dispatchRepositoryToolAppTokenStepID(toolKey)
			consolidatedSafeOutputsStepsLog.Printf("Adding dispatch-repository GitHub App token minting step for %s", toolKey)
			steps = append(steps, c.buildGitHubAppTokenMintStepWithMeta(
				tool.GitHubApp,
				NewPermissionsContentsWrite(),
				"",
				"",
				fmt.Sprintf("Generate GitHub App token (dispatch-repository %s)", toolKey),
				stepID,
			)...)
		}
	}

	return steps
}

// buildSafeOutputItemsManifestUploadStep builds the step that uploads the safe output
// items manifest and temporary ID map as a separate artifact.
func buildSafeOutputItemsManifestUploadStep(prefix string, pinAction func(string) string) []string {
	return []string{
		"      - name: Upload Safe Outputs Items\n",
		"        if: always()\n",
		fmt.Sprintf("        uses: %s\n", pinAction("actions/upload-artifact")),
		"        with:\n",
		fmt.Sprintf("          name: %s%s\n", prefix, constants.SafeOutputItemsArtifactName),
		"          path: |\n",
		"            /tmp/gh-aw/safe-output-items.jsonl\n",
		fmt.Sprintf("            /tmp/gh-aw/%s\n", constants.TemporaryIdMapFilename),
		fmt.Sprintf("            /tmp/gh-aw/%s\n", constants.SafeOutputErrorsFilename),
		"          if-no-files-found: ignore\n",
	}
}

// buildSarifArtifactUploadStep builds the step that uploads the SARIF file generated by
// the create_code_scanning_alert handler as a GitHub Actions artifact.
func buildSarifArtifactUploadStep(prefix string, pinAction func(string) string) []string {
	return []string{
		"      - name: Upload SARIF artifact\n",
		"        if: steps.process_safe_outputs.outputs.sarif_file != ''\n",
		fmt.Sprintf("        uses: %s\n", pinAction("actions/upload-artifact")),
		"        with:\n",
		fmt.Sprintf("          name: %s%s\n", prefix, constants.SarifArtifactName),
		"          path: ${{ steps.process_safe_outputs.outputs.sarif_file }}\n",
		"          if-no-files-found: error\n",
		"          retention-days: 1\n",
	}
}

// scriptNameToHandlerName converts a script name like "post-slack-message" to a
// JavaScript function name like "handlePostSlackMessage".
func scriptNameToHandlerName(scriptName string) string {
	parts := strings.FieldsFunc(scriptName, func(r rune) bool {
		return r == '-' || r == '_'
	})
	var sb strings.Builder
	sb.WriteString("handle")
	for _, part := range parts {
		if part != "" {
			sb.WriteString(strings.ToUpper(part[:1]) + part[1:])
		}
	}
	if sb.Len() == len("handle") {
		if scriptName == "" {
			sb.WriteString("Unknown")
		} else {
			sb.WriteString(strings.ToUpper(scriptName[:1]) + scriptName[1:])
		}
	}
	return sb.String()
}

// generateSafeOutputScriptContent generates a complete JavaScript module for a custom safe-output
// script handler.
func generateSafeOutputScriptContent(scriptName string, scriptConfig *SafeScriptConfig) string {
	var sb strings.Builder
	sb.WriteString("// @ts-check\n")
	sb.WriteString("/// <reference types=\"./safe-output-script\" />\n")
	sb.WriteString("// Auto-generated safe-output script handler: " + scriptName + "\n\n")
	sb.WriteString("const { sanitizeContent } = require(\"./sanitize_content.cjs\");\n\n")
	sb.WriteString("/** @type {import('./types/safe-output-script').SafeOutputScriptMain} */\n")
	sb.WriteString("async function main(config = {}) {\n")

	if len(scriptConfig.Inputs) > 0 {
		inputNames := make([]string, 0, len(scriptConfig.Inputs))
		for name := range scriptConfig.Inputs {
			safeName := stringutil.SanitizeParameterName(name)
			if safeName != name {
				inputNames = append(inputNames, name+": "+safeName)
			} else {
				inputNames = append(inputNames, name)
			}
		}
		sort.Strings(inputNames)
		sb.WriteString("  const { " + strings.Join(inputNames, ", ") + " } = config;\n")
	}

	handlerName := scriptNameToHandlerName(scriptName)
	sb.WriteString("  return async function " + handlerName + "(item, resolvedTemporaryIds, temporaryIdMap) {\n")
	for line := range strings.SplitSeq(scriptConfig.Script, "\n") {
		sb.WriteString("    " + line + "\n")
	}
	sb.WriteString("  };\n")
	sb.WriteString("}\n")
	sb.WriteString("module.exports = { main };\n")
	return sb.String()
}

// buildCustomScriptFilesStep generates a run step that writes inline safe-output script files
// to the setup action destination folder so they can be required by the handler manager.
func buildCustomScriptFilesStep(scripts map[string]*SafeScriptConfig) ([]string, error) {
	if len(scripts) == 0 {
		return nil, nil
	}

	scriptNames := sliceutil.SortedKeys(scripts)
	var steps []string
	steps = append(steps, "      - name: Configure Safe Output Scripts\n")
	steps = append(steps, "        run: |\n")

	for _, scriptName := range scriptNames {
		scriptConfig := scripts[scriptName]
		normalizedName := stringutil.NormalizeSafeOutputIdentifier(scriptName)
		filename := safeOutputScriptFilename(normalizedName)
		filePath := SetupActionDestinationShell + "/" + filename
		scriptContent := generateSafeOutputScriptContent(scriptName, scriptConfig)
		delimiter := GenerateHeredocDelimiterFromContent("SAFE_OUTPUT_SCRIPT_"+strings.ToUpper(normalizedName), scriptContent)

		if err := ValidateHeredocContent(scriptContent, delimiter); err != nil {
			return nil, fmt.Errorf("safe-output script %q: %w", scriptName, err)
		}

		steps = append(steps, fmt.Sprintf("          cat > \"%s\" << '%s'\n", filePath, delimiter)) //nolint:generatedyamlheredoc // Legacy safe-output script rendering remains to be migrated.
		for line := range strings.SplitSeq(scriptContent, "\n") {
			steps = append(steps, "          "+line+"\n")
		}
		steps = append(steps, "          "+delimiter+"\n")
	}

	return steps, nil
}

// addSafeOutputCoreEnvVars appends the core environment variables required by the handler
// manager step: the agent output reference, allowed-domains configuration, URL policy,
// GitHub server/API URLs, custom handler registration maps, and the delegated per-handler
// config env vars.
func (c *Compiler) addSafeOutputCoreEnvVars(steps *[]string, data *WorkflowData) error {
	*steps = append(*steps, "          GH_AW_AGENT_OUTPUT: ${{ steps.setup-agent-output-env.outputs.GH_AW_AGENT_OUTPUT }}\n")
	*steps = append(*steps, "          GH_AW_COMMENT_ID: ${{ needs.activation.outputs.comment_id }}\n")

	// Add allowed domains configuration for URL sanitization in safe output handlers.
	// Without this, sanitizeContent() in safe_output_handler_manager.cjs only allows
	// default GitHub domains, causing user-configured allowed domains to be redacted.
	var domainsStr string
	if data.SafeOutputs != nil && len(data.SafeOutputs.AllowedDomains) > 0 {
		// allowed-domains: additional domains unioned with engine/network base set; supports ecosystem identifiers
		expanded, err := c.computeExpandedAllowedDomainsForSanitization(data)
		if err != nil {
			return err
		}
		domainsStr = expanded
	} else {
		computed, err := c.computeAllowedDomainsForSanitization(data)
		if err != nil {
			return err
		}
		domainsStr = computed
	}
	if domainsStr != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_ALLOWED_DOMAINS: %q\n", domainsStr))
	}
	if data.SafeOutputs != nil && data.SafeOutputs.URLs != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUTS_URLS: %q\n", data.SafeOutputs.URLs))
	}
	// Pass GitHub server/API URLs so buildAllowedDomains() can add GHES domains dynamically
	*steps = append(*steps, "          GITHUB_SERVER_URL: ${{ github.server_url }}\n")
	*steps = append(*steps, "          GITHUB_API_URL: ${{ github.api_url }}\n")

	// Note: The project handler manager has been removed.
	// All project-related operations are now handled by the unified handler.

	// Add GH_AW_SAFE_OUTPUT_JOBS so the handler manager knows which message types are
	// handled by custom safe-output job steps and should be silently skipped rather than
	// reported as "No handler loaded for message type '...'".
	if customJobsJSON := buildCustomSafeOutputJobsJSON(data); customJobsJSON != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUT_JOBS: %q\n", customJobsJSON))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_SAFE_OUTPUT_JOBS env var for custom safe job types")
	}

	// Add GH_AW_SAFE_OUTPUT_SCRIPTS so the handler manager can load inline script handlers.
	// The env var maps normalized script names to their .cjs filenames in the actions folder.
	if customScriptsJSON := buildCustomSafeOutputScriptsJSON(data); customScriptsJSON != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUT_SCRIPTS: %q\n", customScriptsJSON))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_SAFE_OUTPUT_SCRIPTS env var for custom script handlers")
	}

	// Add GH_AW_SAFE_OUTPUT_ACTIONS so the handler manager can load custom action handlers.
	// The env var maps normalized action names to themselves (reserved for future extensibility).
	if customActionsJSON := buildCustomSafeOutputActionsJSON(data); customActionsJSON != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUT_ACTIONS: %q\n", customActionsJSON))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_SAFE_OUTPUT_ACTIONS env var for custom action handlers")
	}

	// Delegated helpers: custom env vars, handler config JSON, and per-handler config env vars.
	c.addCustomSafeOutputEnvVars(steps, data)
	c.addHandlerManagerConfigEnvVar(steps, data)
	c.addAllSafeOutputConfigEnvVars(steps, data)

	return nil
}

// addSafeOutputTokenEnvVars appends token-related environment variables required by the
// handler manager step: the CI-trigger token, project URL/token, assign-to-agent token,
// agent-session token, and the optional GITHUB_TOKEN override for cross-repo PR operations.
func (c *Compiler) addSafeOutputTokenEnvVars(steps *[]string, data *WorkflowData) {
	// Add extra empty commit token if create-pull-request or push-to-pull-request-branch is configured.
	// This token is used to push an empty commit after code changes to trigger CI events,
	// working around the GITHUB_TOKEN limitation where events don't trigger other workflows.
	// Only emit this env var when one of these safe outputs is actually configured.
	if usesPatchesAndCheckouts(data.SafeOutputs) {
		var ciTriggerToken string
		if data.SafeOutputs.CreatePullRequests != nil && data.SafeOutputs.CreatePullRequests.GithubTokenForExtraEmptyCommit != "" {
			ciTriggerToken = data.SafeOutputs.CreatePullRequests.GithubTokenForExtraEmptyCommit
		} else if data.SafeOutputs.PushToPullRequestBranch != nil && data.SafeOutputs.PushToPullRequestBranch.GithubTokenForExtraEmptyCommit != "" {
			ciTriggerToken = data.SafeOutputs.PushToPullRequestBranch.GithubTokenForExtraEmptyCommit
		}

		switch ciTriggerToken {
		case "app":
			*steps = append(*steps, "          GH_AW_CI_TRIGGER_TOKEN: ${{ steps.safe-outputs-app-token.outputs.token || '' }}\n")
			consolidatedSafeOutputsStepsLog.Print("Extra empty commit using GitHub App token")
		default:
			// Use the magic GH_AW_CI_TRIGGER_TOKEN secret (default behavior when not explicitly configured)
			*steps = append(*steps, fmt.Sprintf("          GH_AW_CI_TRIGGER_TOKEN: %s\n", getEffectiveCITriggerGitHubToken(ciTriggerToken)))
			consolidatedSafeOutputsStepsLog.Print("Extra empty commit using GH_AW_CI_TRIGGER_TOKEN")
		}
	}

	// Add GH_AW_PROJECT_URL and GH_AW_PROJECT_GITHUB_TOKEN environment variables for project operations.
	// These are set from the project URL and token configured in any project-related safe-output:
	// update-project, create-project-status-update, or create-project.
	// Note: If multiple project configs are present, we prefer update-project > create-project-status-update > create-project.
	projectURL, projectToken := resolveProjectURLAndToken(data.SafeOutputs)
	if projectURL != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_PROJECT_URL: %q\n", projectURL))
	}
	if projectToken != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_PROJECT_GITHUB_TOKEN: %s\n", projectToken))
	}

	// Add GH_AW_ASSIGN_TO_AGENT_TOKEN when assign-to-agent is configured OR when create-issue
	// or create-pull-request is configured with copilot in assignees. All handlers create a
	// dedicated Octokit using this token (agent token preference chain), which is required
	// because the Copilot assignment API only accepts PATs (not GitHub App tokens).
	if data.SafeOutputs != nil && data.SafeOutputs.AssignToAgent != nil {
		agentTokenStr := getEffectiveCopilotCodingAgentGitHubToken(data.SafeOutputs.AssignToAgent.GitHubToken)
		//nolint:gosec // G101: False positive - this is a GitHub Actions expression template, not a hardcoded credential
		*steps = append(*steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", agentTokenStr))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for assign-to-agent handler")
	} else if data.SafeOutputs != nil && data.SafeOutputs.CreateIssues != nil && hasCopilotAssignee(data.SafeOutputs.CreateIssues.Assignees) {
		agentTokenStr := getEffectiveCopilotCodingAgentGitHubToken(data.SafeOutputs.CreateIssues.GitHubToken)
		//nolint:gosec // G101: False positive - this is a GitHub Actions expression template, not a hardcoded credential
		*steps = append(*steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", agentTokenStr))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for create-issue copilot assignment handler")
	} else if data.SafeOutputs != nil && data.SafeOutputs.CreatePullRequests != nil && hasCopilotAssignee(data.SafeOutputs.CreatePullRequests.Assignees) {
		agentTokenStr := getEffectiveCopilotCodingAgentGitHubToken(data.SafeOutputs.CreatePullRequests.GitHubToken)
		//nolint:gosec // G101: False positive - this is a GitHub Actions expression template, not a hardcoded credential
		*steps = append(*steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", agentTokenStr))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for create-pull-request copilot assignment handler")
	}

	// Add GH_AW_AGENT_SESSION_TOKEN when create-agent-session is configured.
	// The create_agent_session handler passes this token as GH_TOKEN to the gh CLI
	// (agent token preference chain), which is required because the default GITHUB_TOKEN
	// does not have permission to create agent sessions via gh agent-task create.
	if data.SafeOutputs != nil && data.SafeOutputs.CreateAgentSessions != nil {
		agentSessionTokenStr := getEffectiveCopilotCodingAgentGitHubToken(data.SafeOutputs.CreateAgentSessions.GitHubToken)
		//nolint:gosec // G101: False positive - this is a GitHub Actions expression template, not a hardcoded credential
		*steps = append(*steps, fmt.Sprintf("          GH_AW_AGENT_SESSION_TOKEN: %s\n", agentSessionTokenStr))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_AGENT_SESSION_TOKEN env var for create-agent-session handler")
	}

	// When create-pull-request or push-to-pull-request-branch is configured with a custom token
	// (including GitHub App), expose that token as GITHUB_TOKEN so that git CLI operations in
	// the JavaScript handlers can authenticate. The create_pull_request.cjs handler reads
	// process.env.GITHUB_TOKEN to enable dynamic repo checkout for multi-repo/cross-repo
	// scenarios (allowed-repos). Without this, the handler falls back to the default
	// repo-scoped token which lacks access to other repos.
	if usesPatchesAndCheckouts(data.SafeOutputs) {
		gitToken, isCustom := resolvePRCheckoutToken(data.SafeOutputs, NewCheckoutManager(data.CheckoutConfigs))
		// Only override GITHUB_TOKEN when a custom token (app or PAT) is explicitly configured.
		// When no custom token is set, the default repo-scoped GITHUB_TOKEN from GitHub Actions
		// is already in the environment and overriding it with the same default is unnecessary.
		if isCustom {
			//nolint:gosec // G101: False positive - this is a GitHub Actions expression template, not a hardcoded credential
			*steps = append(*steps, fmt.Sprintf("          GITHUB_TOKEN: %s\n", gitToken))
			consolidatedSafeOutputsStepsLog.Printf("Adding GITHUB_TOKEN env var for cross-repo git CLI operations")
		}
	}
}
