// This file provides validation for custom concurrency group expressions.
//
// # Concurrency Group Expression Validation
//
// This file validates that custom concurrency group expressions specified by users
// have correct syntax and can be safely compiled into GitHub Actions workflows.
//
// # Validation Functions
//
//   - validateConcurrencyGroupExpression() - Validates syntax of a single group expression
//
// # Validation Coverage
//
// The validation detects common syntactic errors at compile time:
//   - Unbalanced ${{ }} braces
//   - Missing closing braces
//   - Malformed GitHub Actions expressions
//   - Invalid logical operators placement
//   - Unclosed parentheses or quotes
//
// # When to Add Validation Here
//
// Add validation to this file when:
//   - Adding new concurrency group syntax checks
//   - Detecting new types of expression syntax errors
//   - Improving error messages for concurrency configuration

package workflow

import (
	"regexp"
	"strings"

	"github.com/github/gh-aw/pkg/logger"
)

var concurrencyValidationLog = logger.New("workflow:concurrency_validation")

var (
	concurrencyGroupPattern                = regexp.MustCompile(`(?m)^\s*group:\s*["']?([^"'\n]+?)["']?\s*$`)
	concurrencyQueueMaxPattern             = regexp.MustCompile(`(?m)^\s*queue:\s*["']?max["']?\s*$`)
	concurrencyCancelInProgressTruePattern = regexp.MustCompile(`(?m)^\s*cancel-in-progress:\s*true\s*$`)
)

// validateConcurrencyGroupExpression validates the syntax of a custom concurrency group expression.
// It checks for common syntactic errors that would cause runtime failures:
//   - Unbalanced ${{ }} braces
//   - Missing closing braces
//   - Malformed GitHub Actions expressions
//   - Invalid operator placement
//
// Returns an error if validation fails, nil otherwise.
func validateConcurrencyGroupExpression(group string) error {
	if strings.TrimSpace(group) == "" {
		return NewValidationError(
			"concurrency",
			"empty concurrency group expression",
			"the concurrency group expression is empty or contains only whitespace",
			"Provide a non-empty concurrency group name or expression. Example: 'my-workflow-${{ github.ref }}'",
		)
	}

	concurrencyValidationLog.Printf("Validating concurrency group expression: %s", group)

	// Check for balanced ${{ }} braces
	if err := validateBalancedBraces(group); err != nil {
		return err
	}

	// Extract and validate each GitHub Actions expression within ${{ }}
	if err := validateExpressionSyntax(group); err != nil {
		return err
	}

	concurrencyValidationLog.Print("Concurrency group expression validation passed")
	return nil
}

// extractConcurrencyGroupFromYAML extracts the group value from a YAML-formatted concurrency string.
// The input is expected to be in the format generated by the compiler:
//
//	concurrency: "group-name"  # string format
//
// or
//
//	concurrency:
//	  group: "group-name"      # object format
//	  cancel-in-progress: true  # optional
//
// Returns the group value string or empty string if not found.
//
// Note: This function uses a regex pattern that stops at the first quote or newline character.
// Group values containing embedded quotes or newlines will be truncated at that point. However,
// such values are rare in concurrency group expressions, and any resulting syntax errors will be
// caught by the subsequent expression validation.
func extractConcurrencyGroupFromYAML(concurrencyYAML string) string {
	concurrencyValidationLog.Printf("Extracting concurrency group from YAML (%d bytes)", len(concurrencyYAML))
	// First, check if it's object format with explicit "group:" field
	// Pattern: group: "value" or group: 'value' or group: value (at start of line or after spaces)
	matches := concurrencyGroupPattern.FindStringSubmatch(concurrencyYAML)
	if len(matches) > 1 {
		concurrencyValidationLog.Printf("Extracted concurrency group from object format: %q", strings.TrimSpace(matches[1]))
		return strings.TrimSpace(matches[1])
	}

	// If no explicit "group:" field, it might be string format: concurrency: "value"
	// Pattern: concurrency: "value" or concurrency: 'value' or concurrency: value
	// Must be on the first line (not indented, not preceded by other content)
	lines := strings.Split(concurrencyYAML, "\n")
	if len(lines) > 0 {
		firstLine := strings.TrimSpace(lines[0])
		// Only match if it starts with "concurrency:"
		if after, ok := strings.CutPrefix(firstLine, "concurrency:"); ok {
			value := strings.TrimSpace(after)
			// Remove quotes if present
			value = strings.Trim(value, `"'`)
			concurrencyValidationLog.Printf("Extracted concurrency group from string format: %q", value)
			return value
		}
	}

	concurrencyValidationLog.Print("No concurrency group found in YAML")
	return ""
}

// validateConcurrencyQueueConfiguration validates queue/cancel-in-progress compatibility.
// GitHub Actions rejects queue: max when cancel-in-progress: true is also set.
func validateConcurrencyQueueConfiguration(concurrencyYAML string) error {
	if strings.TrimSpace(concurrencyYAML) == "" {
		return nil
	}

	hasQueueMax := concurrencyQueueMaxPattern.MatchString(concurrencyYAML)
	hasCancelInProgressTrue := concurrencyCancelInProgressTruePattern.MatchString(concurrencyYAML)
	if hasQueueMax || hasCancelInProgressTrue {
		concurrencyValidationLog.Printf(
			"Concurrency queue/cancel match state: queue:max=%t cancel-in-progress:true=%t",
			hasQueueMax,
			hasCancelInProgressTrue,
		)
	}

	if hasQueueMax && hasCancelInProgressTrue {
		return NewValidationError(
			"concurrency",
			"invalid concurrency queue configuration",
			"queue: max cannot be combined with cancel-in-progress: true",
			"Set queue to single (or omit queue) when cancel-in-progress is true, or set cancel-in-progress to false when using queue: max.",
		)
	}

	return nil
}
