// This file provides validation for workflow lock files.
//
// # Lock File Validation
//
// This file validates lock files at two levels:
//   - Schema compatibility: ensures the lock file's schema version is supported by the
//     current build of gh-aw, providing actionable error messages when a lock file
//     was generated by an incompatible version.
//   - Action SHA freshness: checks whether pinned GitHub Actions SHAs are up to date
//     and emits warnings when newer SHAs are available.
//
// # Validation Functions
//
//   - ValidateLockSchemaCompatibility() - Validates lock file schema version
//   - ValidateActionSHAsInLockFile()    - Validates action SHAs and emits update warnings
//
// # When to Add Validation Here
//
// Add validation to this file when:
//   - Adding new lock file format constraints
//   - Adding migration validation for schema upgrades
//   - Adding user-facing orchestration that validates lock file content

package workflow

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/github/gh-aw/pkg/console"
)

// ValidateLockSchemaCompatibility validates that a lock file's schema is compatible.
// Returns an error with actionable guidance if incompatible.
func ValidateLockSchemaCompatibility(content string, lockFilePath string) error {
	metadata, isLegacy, err := ExtractMetadataFromLockFile(content)
	if err != nil {
		return fmt.Errorf("failed to extract metadata from %s: %w", lockFilePath, err)
	}

	// Legacy files (no schema version) are supported for backward compatibility
	if isLegacy {
		lockSchemaLog.Printf("Legacy lock file accepted: %s", lockFilePath)
		return nil
	}

	// Missing metadata entirely is suspicious
	if metadata == nil {
		return fmt.Errorf("lock file %s is missing required metadata. This file may be corrupted or manually edited.\n\nTo fix this, recompile the workflow:\n  gh aw compile %s",
			lockFilePath,
			strings.TrimSuffix(lockFilePath, ".lock.yml")+".md")
	}

	// Check schema compatibility
	if !IsSchemaVersionSupported(metadata.SchemaVersion) {
		// Future version detected
		return fmt.Errorf("lock file %s uses unsupported schema version '%s'.\n\nThis file was generated by a newer version of gh-aw that uses incompatible features.\n\nSupported versions: %s\n\nTo fix this:\n  1. Upgrade gh-aw: gh extension upgrade gh-aw\n  2. Or downgrade the lock file by editing the source .md file and recompiling:\n     gh aw compile %s",
			lockFilePath,
			metadata.SchemaVersion,
			formatSupportedVersions(),
			strings.TrimSuffix(lockFilePath, ".lock.yml")+".md")
	}

	lockSchemaLog.Printf("Lock file schema validated: %s (version=%s)", lockFilePath, metadata.SchemaVersion)
	return nil
}

// ValidateActionSHAsInLockFile validates action SHAs in a lock file and emits warnings
func ValidateActionSHAsInLockFile(ctx context.Context, lockFilePath string, cache *ActionCache, verbose bool) error {
	actionSHACheckerLog.Printf("Validating action SHAs in: %s", lockFilePath)

	// Extract actions from lock file
	actions, err := ExtractActionsFromLockFile(lockFilePath)
	if err != nil {
		return fmt.Errorf("failed to extract actions: %w", err)
	}

	if len(actions) == 0 {
		actionSHACheckerLog.Print("No pinned actions found in lock file")
		if verbose {
			fmt.Fprintln(os.Stderr, console.FormatInfoMessage("No pinned actions to validate"))
		}
		return nil
	}

	// Create resolver for checking latest SHAs
	resolver := NewActionResolver(cache)

	// Check for updates
	checks := CheckActionSHAUpdates(ctx, actions, resolver)

	// Count and report updates
	updateCount := 0
	for _, check := range checks {
		if check.NeedsUpdate {
			updateCount++
			// Emit warning (FormatWarningMessage adds the warning emoji)
			warningMsg := fmt.Sprintf("%s@%s has a newer SHA available: %s → %s",
				check.Action.Repo,
				check.Action.Version,
				check.Action.SHA[:7],
				check.LatestSHA[:7])
			fmt.Fprintln(os.Stderr, console.FormatWarningMessage(warningMsg))

			// Show full SHA in verbose mode
			if verbose {
				fmt.Fprintf(os.Stderr, "    Current: %s\n", check.Action.SHA)
				fmt.Fprintf(os.Stderr, "    Latest:  %s\n", check.LatestSHA)
			}
		}
	}

	if updateCount > 0 {
		actionSHACheckerLog.Printf("Found %d actions that need updating", updateCount)
		// Save the cache with updated SHAs so the next compilation will use them
		if err := cache.Save(); err != nil {
			actionSHACheckerLog.Printf("Warning: failed to save action cache: %v", err)
		} else {
			actionSHACheckerLog.Print("Saved updated action cache")
		}
		// Provide suggestion to fix the issue
		fmt.Fprintln(os.Stderr, console.FormatInfoMessage("To apply updated action SHAs, recompile with: gh aw compile"))
		if verbose {
			fmt.Fprintln(os.Stderr, console.FormatInfoMessage(fmt.Sprintf("Found %d action(s) with available updates", updateCount)))
		}
	} else {
		actionSHACheckerLog.Print("All actions are up to date")
	}

	return nil
}
