package workflow

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/github/gh-aw/pkg/console"
	"github.com/github/gh-aw/pkg/constants"
	"github.com/github/gh-aw/pkg/logger"
	"github.com/github/gh-aw/pkg/parser"
	"github.com/github/gh-aw/pkg/stringutil"
	"github.com/goccy/go-yaml"
)

var resolveLog = logger.New("workflow:resolve")

// ResolveWorkflowName converts an agentic workflow ID to the GitHub Actions workflow name.
// It normalizes the input by removing .md and .lock.yml extensions, then finds the
// corresponding workflow files and extracts the actual workflow name from the lock.yml file.
//
// The agentic workflow ID is the basename of the markdown file without the .md extension.
// The GitHub Actions workflow name is extracted from the "name:" field in the corresponding .lock.yml file.
//
// Examples:
//   - "weekly-research" -> "Weekly Research" (from weekly-research.lock.yml name field)
//   - "weekly-research.md" -> "Weekly Research" (from weekly-research.lock.yml name field)
//   - "weekly-research.lock.yml" -> "Weekly Research" (from weekly-research.lock.yml name field)
func ResolveWorkflowName(workflowInput string) (string, error) {
	if workflowInput == "" {
		return "", nil
	}

	resolveLog.Printf("Resolving workflow name for input: %s", workflowInput)

	// Normalize the workflow name by removing extensions
	normalizedName := stringutil.NormalizeWorkflowName(workflowInput)
	resolveLog.Printf("Normalized workflow name: %s", normalizedName)

	// Get the workflows directory
	workflowsDir := constants.GetWorkflowDir()

	// Check if the agentic workflow markdown file exists
	mdFile := filepath.Join(workflowsDir, normalizedName+".md")
	if _, err := os.Stat(mdFile); err != nil {
		resolveLog.Printf("Markdown file not found: %s", mdFile)
		suggestions := []string{
			fmt.Sprintf("Run '%s status' to see all available workflows", constants.CLIExtensionPrefix),
			fmt.Sprintf("Create a new workflow with '%s new %s'", constants.CLIExtensionPrefix, normalizedName),
			"Check for typos in the workflow name",
		}
		return "", errors.New(console.FormatErrorWithSuggestions(
			fmt.Sprintf("agentic workflow '%s' not found (expected file: %s)", normalizedName, mdFile),
			suggestions,
		))
	}

	// The corresponding lock file name is what GitHub Actions uses as the workflow name
	lockFileName := normalizedName + ".lock.yml"
	lockFile := filepath.Join(workflowsDir, lockFileName)

	// Check if the lock file exists (should be generated by compile)
	if _, err := os.Stat(lockFile); err != nil {
		suggestions := []string{
			fmt.Sprintf("Run '%s compile' to compile the workflow", constants.CLIExtensionPrefix),
			fmt.Sprintf("Run '%s compile %s' to compile this specific workflow", constants.CLIExtensionPrefix, normalizedName),
		}
		return "", errors.New(console.FormatErrorWithSuggestions(
			fmt.Sprintf("compiled workflow '%s' not found (expected file: %s)", normalizedName, lockFile),
			suggestions,
		))
	}

	// Read and parse the lock file to extract the workflow name
	content, err := os.ReadFile(lockFile)
	if err != nil {
		return "", fmt.Errorf("failed to read lock file '%s': %w", lockFile, err)
	}

	// Parse YAML to extract the name field
	var workflow struct {
		Name string `yaml:"name"`
	}

	if err := yaml.Unmarshal(content, &workflow); err != nil {
		return "", fmt.Errorf("failed to parse YAML from lock file '%s': %w", lockFile, err)
	}

	if workflow.Name == "" {
		resolveLog.Printf("Workflow name field missing in lock file: %s", lockFile)
		suggestions := []string{
			fmt.Sprintf("Run '%s compile %s' to recompile the workflow", constants.CLIExtensionPrefix, normalizedName),
			"Check if the workflow file has a valid 'name' field in the frontmatter",
		}
		return "", errors.New(console.FormatErrorWithSuggestions(
			fmt.Sprintf("workflow name not found in lock file '%s'", lockFile),
			suggestions,
		))
	}

	resolveLog.Printf("Successfully resolved workflow name: %s", workflow.Name)
	return workflow.Name, nil
}

// WorkflowNameMatch represents a matched workflow with its ID and display name
type WorkflowNameMatch struct {
	WorkflowID   string // The workflow ID (filename without .md)
	DisplayName  string // The GitHub Actions workflow name from the lock file
	MatchedInput string // The input that was used to find this match
}

// FindWorkflowName attempts to find a workflow using flexible matching strategies.
// It accepts both workflow IDs (kebab-case filename without .md) and display names
// (GitHub Actions workflow name from frontmatter).
//
// Matching strategies (in order):
//  1. Try to resolve as workflow ID using ResolveWorkflowName
//  2. Try exact match with workflow ID (case-sensitive)
//  3. Try case-insensitive match with workflow ID
//  4. Try exact match with display name (case-sensitive)
//  5. Try case-insensitive match with display name
//
// Returns the matched workflow's display name (GitHub Actions workflow name) on success.
// Returns an error with suggestions if no match is found.
//
// Examples:
//   - "ci-failure-doctor" -> "CI Failure Doctor" (workflow ID match)
//   - "CI-FAILURE-DOCTOR" -> "CI Failure Doctor" (case-insensitive workflow ID match)
//   - "CI Failure Doctor" -> "CI Failure Doctor" (display name match)
//   - "ci failure doctor" -> "CI Failure Doctor" (case-insensitive display name match)
func FindWorkflowName(input string) (string, error) {
	if input == "" {
		return "", nil
	}

	resolveLog.Printf("Finding workflow with flexible matching: %s", input)

	// Strategy 1: Try to resolve as workflow ID
	// This handles the normal case where user provides a workflow ID
	displayName, err := ResolveWorkflowName(input)
	if err == nil && displayName != "" {
		resolveLog.Printf("Found workflow via ResolveWorkflowName: %s -> %s", input, displayName)
		return displayName, nil
	}

	// If ResolveWorkflowName failed, try other matching strategies
	// First, get all available workflows
	workflows, err := GetAllWorkflows()
	if err != nil {
		return "", fmt.Errorf("failed to get workflows: %w", err)
	}

	if len(workflows) == 0 {
		return "", errors.New("no workflows found in .github/workflows directory")
	}

	// Normalize input for matching
	normalizedInput := stringutil.NormalizeWorkflowName(input)
	// Strategy 2: Try exact match with workflow ID (case-sensitive)
	for _, wf := range workflows {
		if wf.WorkflowID == input || wf.WorkflowID == normalizedInput {
			resolveLog.Printf("Found exact workflow ID match: %s -> %s", input, wf.DisplayName)
			return wf.DisplayName, nil
		}
	}

	// Strategy 3: Try case-insensitive match with workflow ID
	for _, wf := range workflows {
		if strings.EqualFold(wf.WorkflowID, input) || strings.EqualFold(wf.WorkflowID, normalizedInput) {
			resolveLog.Printf("Found case-insensitive workflow ID match: %s -> %s", input, wf.DisplayName)
			return wf.DisplayName, nil
		}
	}

	// Strategy 4: Try exact match with display name (case-sensitive)
	for _, wf := range workflows {
		if wf.DisplayName == input {
			resolveLog.Printf("Found exact display name match: %s", input)
			return wf.DisplayName, nil
		}
	}

	// Strategy 5: Try case-insensitive match with display name
	for _, wf := range workflows {
		if strings.EqualFold(wf.DisplayName, input) {
			resolveLog.Printf("Found case-insensitive display name match: %s -> %s", input, wf.DisplayName)
			return wf.DisplayName, nil
		}
	}

	// No match found - return error with suggestions
	resolveLog.Printf("No workflow match found for: %s", input)
	return "", fmt.Errorf("workflow '%s' not found", input)
}

// GetWorkflowLockFileName returns the lock file name (e.g. "smoke-copilot.lock.yml")
// for the given workflow input. It accepts a workflow ID (e.g. "smoke-copilot"),
// a file name with any supported extension (e.g. "smoke-copilot.md"), or a display
// name (e.g. "Smoke Copilot"). Returns an error if no matching workflow is found.
func GetWorkflowLockFileName(input string) (string, error) {
	if input == "" {
		return "", nil
	}

	// Strategy 1: Normalize and check if the lock file exists directly.
	// This handles workflow IDs and filenames with .md or .lock.yml extensions.
	workflowsDir := constants.GetWorkflowDir()
	normalizedName := stringutil.NormalizeWorkflowName(input)
	lockFile := filepath.Join(workflowsDir, normalizedName+".lock.yml")
	if _, err := os.Stat(lockFile); err == nil {
		return normalizedName + ".lock.yml", nil
	}

	// Strategy 2: Match by display name (case-insensitive) via GetAllWorkflows.
	// This handles inputs like "Smoke Copilot" that normalize to non-existent filenames.
	workflows, err := GetAllWorkflows()
	if err != nil {
		return "", fmt.Errorf("failed to get workflows: %w", err)
	}

	for _, wf := range workflows {
		if strings.EqualFold(wf.DisplayName, input) {
			return wf.WorkflowID + ".lock.yml", nil
		}
	}

	return "", fmt.Errorf("workflow lock file not found for '%s'", input)
}

// GetAllWorkflows returns all available workflows with their IDs and display names
func GetAllWorkflows() ([]WorkflowNameMatch, error) {
	workflowsDir := constants.GetWorkflowDir()

	// Get all .lock.yml files
	lockFiles, err := filepath.Glob(filepath.Join(workflowsDir, "*.lock.yml"))
	if err != nil {
		return nil, fmt.Errorf("failed to glob .lock.yml files: %w", err)
	}

	var workflows []WorkflowNameMatch
	for _, lockFile := range lockFiles {
		// Extract workflow ID from filename
		base := filepath.Base(lockFile)
		workflowID := strings.TrimSuffix(base, ".lock.yml")

		// Extract only the top-level `name:` field. Lock files are large generated
		// GitHub Actions YAML (hundreds of KB each); fully parsing every file just to
		// read one field is very slow (seconds across a repo with many workflows), so
		// we scan for the first column-0 `name:` line and parse only that.
		name, err := extractLockFileWorkflowName(lockFile)
		if err != nil {
			resolveLog.Printf("Failed to read workflow name from lock file %s: %v", lockFile, err)
			continue
		}

		if name == "" {
			resolveLog.Printf("Workflow name field missing in lock file: %s", lockFile)
			continue
		}

		workflows = append(workflows, WorkflowNameMatch{
			WorkflowID:  workflowID,
			DisplayName: name,
		})
	}

	return workflows, nil
}

// extractLockFileWorkflowName returns the top-level workflow `name:` value from a
// generated lock file without parsing the entire (potentially very large) YAML
// document. It scans line-by-line for the first column-0 `name:` key — which in
// generated lock files is always the workflow name — and unmarshals just that single
// line so YAML scalar semantics (quoting, escapes) are preserved. Scanning stops as
// soon as the name is found.
func extractLockFileWorkflowName(lockFile string) (string, error) {
	f, err := os.Open(lockFile)
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	// Lock file `name:` lines are short, but allow generous headroom for long names.
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		// Only a column-0 (unindented, non-comment) `name:` key is the workflow name;
		// nested `name:` keys under jobs/steps are always indented.
		if !strings.HasPrefix(line, "name:") {
			continue
		}
		var wf struct {
			Name string `yaml:"name"`
		}
		if err := yaml.Unmarshal([]byte(line), &wf); err != nil {
			return "", err
		}
		return wf.Name, nil
	}
	if err := scanner.Err(); err != nil {
		return "", err
	}
	return "", nil
}

// IsIntentionalFailure reports whether the workflow identified by workflowPath is tagged
// with intentional-failure: true in its frontmatter.  workflowPath may be:
//   - a .lock.yml path   (e.g. ".github/workflows/daily-credit-limit-test.lock.yml")
//   - a .md path         (e.g. ".github/workflows/daily-credit-limit-test.md")
//   - a bare workflow ID (e.g. "daily-credit-limit-test")
//
// Returns false whenever the file cannot be read or parsed (fail-open: unknown workflows
// are not excluded from health rollups).
func IsIntentionalFailure(workflowPath string) bool {
	if workflowPath == "" {
		return false
	}

	// Derive the markdown file path.
	var mdPath string
	switch {
	case strings.HasSuffix(workflowPath, ".lock.yml"):
		mdPath = strings.TrimSuffix(workflowPath, ".lock.yml") + ".md"
	case strings.HasSuffix(workflowPath, ".md"):
		mdPath = workflowPath
	default:
		// Treat as a bare workflow ID.
		normalizedName := stringutil.NormalizeWorkflowName(workflowPath)
		mdPath = filepath.Join(constants.GetWorkflowDir(), normalizedName+".md")
	}

	content, err := os.ReadFile(mdPath)
	if err != nil {
		// File not available locally (e.g. running against a remote repo).
		return false
	}

	result, err := parser.ExtractFrontmatterFromContent(string(content))
	if err != nil || result == nil {
		return false
	}

	featuresRaw, ok := result.Frontmatter["features"]
	if !ok {
		return false
	}
	features, ok := featuresRaw.(map[string]any)
	if !ok {
		return false
	}
	val, ok := features["intentional-failure"]
	if !ok {
		return false
	}

	b, ok := val.(bool)
	return ok && b
}
