package workflow

import "github.com/github/gh-aw/pkg/logger"

var handlerRegistryLog = logger.New("workflow:safe_outputs_handler_registry")

// resolveHandlerGitHubToken returns the effective GitHub token expression for a handler.
// When app is non-nil (a per-handler github-app is configured), the compiler has already
// minted a dedicated token step whose ID is "{handlerKey}-app-token"; this function returns
// the expression that references that step's output. Otherwise it falls back to the explicit
// github-token, if any.
//
// The step referenced here is generated by the general per-handler loop in
// buildHandlerManagerStep, which iterates safeOutputHandlers and mints a token for each
// handler whose BaseSafeOutputConfig.GitHubApp is set.
func resolveHandlerGitHubToken(app *GitHubAppConfig, handlerKey, fallbackToken string) string {
	if app != nil && handlerSupportsPerHandlerGitHubAppToken(handlerKey) {
		handlerRegistryLog.Printf("Using per-handler GitHub App token for %s", handlerKey)
		return resolveHandlerGitHubTokenWithStepID(app, handlerKey+"-app-token", fallbackToken)
	}
	return fallbackToken
}

// resolveApproveWorkflowRunGitHubToken returns an explicitly configured token for
// workflow-run approval. GitHub's default Actions token cannot approve fork PR
// workflow runs, so this handler must never fall back to it.
func resolveApproveWorkflowRunGitHubToken(cfg *SafeOutputsConfig, config *ApproveWorkflowRunConfig) string {
	if token := resolveHandlerGitHubToken(config.GitHubApp, "approve-workflow-run", config.GitHubToken); token != "" {
		return token
	}
	if cfg.GitHubApp != nil {
		return "${{ steps.safe-outputs-app-token.outputs.token }}"
	}
	return cfg.GitHubToken
}

func resolveHandlerGitHubTokenWithStepID(app *GitHubAppConfig, stepID, fallbackToken string) string {
	if app != nil && stepID != "" {
		//nolint:gosec // G101: False positive - this is a GitHub Actions expression template, not a hardcoded credential
		return "${{ steps." + stepID + ".outputs.token }}"
	}
	return fallbackToken
}

func handlerSupportsPerHandlerGitHubAppToken(handlerKey string) bool {
	handler, ok := getSafeOutputHandlerByKey(handlerKey)
	supported := ok && handler.PermissionBuilder != nil
	if !supported {
		handlerRegistryLog.Printf("Handler %s does not support per-handler GitHub App tokens (registered=%v)", handlerKey, ok)
	}
	return supported
}

// handlerRegistry maps handler names to their builder functions.
// Each entry is keyed by the handler name used in GH_AW_SAFE_OUTPUTS_HANDLER_CONFIG
// and returns a config map (nil means the handler is disabled).
var handlerRegistry = mergeHandlerMaps(
	issueHandlerRegistry,
	discussionHandlerRegistry,
	pullRequestHandlerRegistry,
	workflowHandlerRegistry,
	projectHandlerRegistry,
	assignmentHandlerRegistry,
	commentHandlerRegistry,
	jiraHandlerRegistry,
	linearHandlerRegistry,
	releaseHandlerRegistry,
	diagnosticHandlerRegistry,
	azureDevOpsWorkItemHandlerRegistry,
)

func mergeHandlerMaps(registries ...map[string]handlerBuilder) map[string]handlerBuilder {
	merged := make(map[string]handlerBuilder)
	for _, registry := range registries {
		for key, builder := range registry {
			if _, exists := merged[key]; exists {
				handlerRegistryLog.Printf("Duplicate safe outputs handler registry key %q; keeping first builder", key)
				continue
			}
			merged[key] = builder
		}
	}
	return merged
}
