//go:build !integration

package cli

import (
	"strings"
	"testing"

	"github.com/github/gh-aw/pkg/parser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// extractSafeOutputKeys parses a YAML snippet that begins with "safe-outputs:" and
// returns the list of safe-output type keys that appear at exactly 2 spaces of
// indentation. Lines indented more deeply are sub-keys of the active entry and are
// skipped; comment-only lines and the section header itself are also skipped.
func extractSafeOutputKeys(section string) []string {
	var keys []string
	for line := range strings.SplitSeq(section, "\n") {
		// Only examine lines with exactly 2 leading spaces (type-key level).
		// Sub-keys (e.g. "    max: 5") have 4+ spaces and are skipped.
		if !strings.HasPrefix(line, "  ") || strings.HasPrefix(line, "   ") {
			continue
		}
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}

		// Strip a leading comment marker so both active and commented keys are checked.
		candidate := strings.TrimPrefix(trimmed, "# ")

		// Extract the key name (the part before the colon).
		key, _, found := strings.Cut(candidate, ":")
		if !found {
			continue
		}
		key = strings.TrimSpace(key)
		if key == "" {
			continue
		}
		keys = append(keys, key)
	}
	return keys
}

// TestBuildSafeOutputsSection validates that buildSafeOutputsSection generates
// safe-output names that are all valid according to the JSON schema.
func TestBuildSafeOutputsSection(t *testing.T) {
	t.Parallel()
	section := buildSafeOutputsSection()

	require.NotEmpty(t, section, "buildSafeOutputsSection should return non-empty content")
	assert.Contains(t, section, "safe-outputs:", "Section should contain safe-outputs key")
	assert.Contains(t, section, "create-issue:", "Section should include create-issue as active example")

	// Get valid schema keys to check against
	validKeys, err := parser.GetSafeOutputTypeKeys()
	require.NoError(t, err, "GetSafeOutputTypeKeys should not return error")
	require.NotEmpty(t, validKeys, "Schema should have safe output type keys")

	validKeySet := make(map[string]bool, len(validKeys))
	for _, k := range validKeys {
		validKeySet[k] = true
	}

	for _, key := range extractSafeOutputKeys(section) {
		assert.True(t, validKeySet[key],
			"safe-output name %q used in 'new' template is not a valid schema key", key)
	}
}

// TestCreateWorkflowTemplateContainsOnlyValidSafeOutputs validates that the workflow
// template generated by the 'new' command only references safe-output names that are
// defined in the JSON schema.
func TestCreateWorkflowTemplateContainsOnlyValidSafeOutputs(t *testing.T) {
	t.Parallel()
	template := createWorkflowTemplate("test-workflow", "")

	validKeys, err := parser.GetSafeOutputTypeKeys()
	require.NoError(t, err, "GetSafeOutputTypeKeys should not return error")

	validKeySet := make(map[string]bool, len(validKeys))
	for _, k := range validKeys {
		validKeySet[k] = true
	}

	// Isolate the safe-outputs section of the template.
	inSafeOutputs := false
	var safeOutputsLines []string
	for line := range strings.SplitSeq(template, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "safe-outputs:" {
			inSafeOutputs = true
			safeOutputsLines = append(safeOutputsLines, line)
			continue
		}
		if inSafeOutputs && (trimmed == "---" || (len(line) > 0 && line[0] != ' ' && !strings.HasPrefix(line, "#"))) {
			break
		}
		if inSafeOutputs {
			safeOutputsLines = append(safeOutputsLines, line)
		}
	}

	for _, key := range extractSafeOutputKeys(strings.Join(safeOutputsLines, "\n")) {
		assert.True(t, validKeySet[key],
			"safe-output name %q in 'new' template is not a valid schema key", key)
	}
}
