//go:build !integration

package cli

import (
	"testing"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewCompletionCommand(t *testing.T) {
	t.Parallel()
	cmd := NewCompletionCommand()

	assert.Equal(t, "completion", cmd.Name())
	assert.Equal(t, "Generate shell completion scripts for gh aw commands", cmd.Short)
	assert.Contains(t, cmd.Long, "Tab completion provides")
	assert.Equal(t, []string{"bash", "zsh", "fish", "powershell"}, cmd.ValidArgs)
}

func TestCompletionCommand_Bash(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "bash"})
	err := rootCmd.Execute()

	// Just verify no error - the actual script is generated by Cobra
	require.NoError(t, err, "Bash completion generation should not error")
}

func TestCompletionCommand_Zsh(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "zsh"})
	err := rootCmd.Execute()

	// Just verify no error - the actual script is generated by Cobra
	require.NoError(t, err, "Zsh completion generation should not error")
}

func TestCompletionCommand_Fish(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "fish"})
	err := rootCmd.Execute()

	// Just verify no error - the actual script is generated by Cobra
	require.NoError(t, err, "Fish completion generation should not error")
}

func TestCompletionCommand_PowerShell(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "powershell"})
	err := rootCmd.Execute()

	// Just verify no error - the actual script is generated by Cobra
	require.NoError(t, err, "PowerShell completion generation should not error")
}

func TestCompletionCommand_InvalidShell(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "invalid"})
	err := rootCmd.Execute()

	require.Error(t, err)
	require.ErrorContains(t, err, "invalid argument")
}

func TestCompletionCommand_NoArgs(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion"})
	err := rootCmd.Execute()

	require.Error(t, err)
	require.ErrorContains(t, err, "accepts 1 arg(s)")
}

func TestCompletionCommand_InstallSubcommand(t *testing.T) {
	t.Parallel()
	cmd := NewCompletionCommand()

	// Verify install subcommand exists
	installCmd := findSubcommand(cmd, "install")
	require.NotNil(t, installCmd, "install subcommand should exist")

	assert.Equal(t, "install", installCmd.Name())
	assert.Equal(t, "Install shell completion for the detected shell", installCmd.Short)
	assert.Contains(t, installCmd.Long, "Automatically install shell completion")
}

func TestCompletionCommand_UninstallSubcommand(t *testing.T) {
	t.Parallel()
	cmd := NewCompletionCommand()

	// Verify uninstall subcommand exists
	uninstallCmd := findSubcommand(cmd, "uninstall")
	require.NotNil(t, uninstallCmd, "uninstall subcommand should exist")

	assert.Equal(t, "uninstall", uninstallCmd.Name())
	assert.Equal(t, "Uninstall shell completion for the detected shell", uninstallCmd.Short)
	assert.Contains(t, uninstallCmd.Long, "Automatically uninstall shell completion")
}

func TestCompletionCommand_LongHelp(t *testing.T) {
	t.Parallel()
	cmd := NewCompletionCommand()

	assert.Contains(t, cmd.Long, "Tab completion provides")
	assert.Contains(t, cmd.Long, "Command name completion")
	assert.Contains(t, cmd.Long, "Workflow name completion")
	assert.Contains(t, cmd.Long, "Engine name completion")
	assert.Contains(t, cmd.Long, "bash, zsh, fish, PowerShell")
}

func TestCompletionCommand_Examples(t *testing.T) {
	t.Parallel()
	cmd := NewCompletionCommand()

	// Verify examples are present for all shells
	assert.Contains(t, cmd.Example, "gh aw completion install")
	assert.Contains(t, cmd.Example, "gh aw completion bash")
	assert.Contains(t, cmd.Example, "gh aw completion zsh")
	assert.Contains(t, cmd.Example, "gh aw completion fish")
	assert.Contains(t, cmd.Example, "gh aw completion powershell")
}

func TestCompletionCommand_ValidArgs(t *testing.T) {
	t.Parallel()
	cmd := NewCompletionCommand()

	expectedArgs := []string{"bash", "zsh", "fish", "powershell"}
	assert.Equal(t, expectedArgs, cmd.ValidArgs)
}

// Helper function to find a subcommand by name
func findSubcommand(cmd *cobra.Command, name string) *cobra.Command {
	for _, subCmd := range cmd.Commands() {
		if subCmd.Name() == name {
			return subCmd
		}
	}
	return nil
}

// TestCompletionCommand_BashScriptFormat verifies bash completion can be generated
func TestCompletionCommand_BashScriptFormat(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "bash"})
	err := rootCmd.Execute()

	// Just verify no error - the actual script format is tested by Cobra
	require.NoError(t, err, "Bash completion generation should not error")
}

// TestCompletionCommand_ZshScriptFormat verifies zsh completion can be generated
func TestCompletionCommand_ZshScriptFormat(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "zsh"})
	err := rootCmd.Execute()

	// Just verify no error - the actual script format is tested by Cobra
	require.NoError(t, err, "Zsh completion generation should not error")
}

// TestCompletionCommand_FishScriptFormat verifies fish completion can be generated
func TestCompletionCommand_FishScriptFormat(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "fish"})
	err := rootCmd.Execute()

	// Just verify no error - the actual script format is tested by Cobra
	require.NoError(t, err, "Fish completion generation should not error")
}

// TestCompletionCommand_PowerShellScriptFormat verifies PowerShell completion can be generated
func TestCompletionCommand_PowerShellScriptFormat(t *testing.T) {
	t.Parallel()
	rootCmd := &cobra.Command{Use: "gh"}
	completionCmd := NewCompletionCommand()
	rootCmd.AddCommand(completionCmd)

	rootCmd.SetArgs([]string{"completion", "powershell"})
	err := rootCmd.Execute()

	// Just verify no error - the actual script format is tested by Cobra
	require.NoError(t, err, "PowerShell completion generation should not error")
}
