package cli

import (
	"bufio"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/github/gh-aw/pkg/constants"
	"github.com/github/gh-aw/pkg/fileutil"
	"github.com/github/gh-aw/pkg/logger"
)

var firewallPolicyLog = logger.New("cli:firewall_policy")

// PolicyManifest represents the policy-manifest.json file generated by AWF.
// It describes the firewall policy rules and configuration used during a workflow run.
type PolicyManifest struct {
	Version           int                  `json:"version"`
	GeneratedAt       string               `json:"generatedAt"`
	Rules             []FirewallPolicyRule `json:"rules"`
	DangerousPorts    []int                `json:"dangerousPorts,omitempty"`
	DNSServers        []string             `json:"dnsServers,omitempty"`
	SSLBumpEnabled    bool                 `json:"sslBumpEnabled"`
	DLPEnabled        bool                 `json:"dlpEnabled"`
	HostAccessEnabled bool                 `json:"hostAccessEnabled"`
	AllowHostPorts    *string              `json:"allowHostPorts"` // nullable → pointer
}

// FirewallPolicyRule represents a single firewall policy rule from the manifest.
type FirewallPolicyRule struct {
	ID          string   `json:"id"`
	Order       int      `json:"order"`
	Action      string   `json:"action"` // "allow" or "deny"
	ACLName     string   `json:"aclName"`
	Protocol    string   `json:"protocol"` // "both", "http", "https"
	Domains     []string `json:"domains"`
	Description string   `json:"description"`
}

// AuditLogEntry represents a single entry from audit.jsonl.
// This is the JSONL format written by the AWF audit subsystem.
// Each record includes a _schema field (e.g. "audit/v0.26.0") that identifies the
// record type and AWF version for forward-compatible consumers.
type AuditLogEntry struct {
	Schema    string  `json:"_schema,omitempty"` // Self-describing record type, e.g. "audit/v0.26.0"
	Timestamp float64 `json:"ts"`
	Client    string  `json:"client,omitempty"`
	Host      string  `json:"host"`
	Dest      string  `json:"dest,omitempty"`
	Method    string  `json:"method,omitempty"`
	Status    int     `json:"status"`
	Decision  string  `json:"decision,omitempty"`
	URL       string  `json:"url,omitempty"`
}

// EnrichedRequest represents a firewall request enriched with policy rule attribution.
type EnrichedRequest struct {
	Timestamp float64 `json:"ts"`
	Host      string  `json:"host"`
	Status    int     `json:"status"`
	RuleID    string  `json:"rule_id"`
	Action    string  `json:"action"` // "allow" or "deny"
	Reason    string  `json:"reason,omitempty"`
}

// RuleHitStats tracks hit counts per policy rule.
type RuleHitStats struct {
	Rule FirewallPolicyRule `json:"rule"`
	Hits int                `json:"hits"`
}

// PolicyAnalysis contains the enriched policy analysis results.
type PolicyAnalysis struct {
	PolicySummary  string            `json:"policy_summary"`
	RuleHits       []RuleHitStats    `json:"rule_hits"`
	DeniedRequests []EnrichedRequest `json:"denied_requests,omitempty"`
	TotalRequests  int               `json:"total_requests"`
	AllowedCount   int               `json:"allowed_count"`
	DeniedCount    int               `json:"denied_count"`
	UniqueDomains  int               `json:"unique_domains"`
}

// loadPolicyManifest loads and parses a policy-manifest.json file.
func loadPolicyManifest(manifestPath string) (*PolicyManifest, error) {
	firewallPolicyLog.Printf("Loading policy manifest: %s", manifestPath)

	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read policy manifest: %w", err)
	}

	var manifest PolicyManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, fmt.Errorf("failed to parse policy manifest: %w", err)
	}

	// Sort rules by order for deterministic matching
	slices.SortFunc(manifest.Rules, func(a, b FirewallPolicyRule) int {
		if a.Order < b.Order {
			return -1
		}
		if a.Order > b.Order {
			return 1
		}
		return 0
	})

	firewallPolicyLog.Printf("Loaded policy manifest: version=%d, rules=%d, ssl_bump=%v, dlp=%v",
		manifest.Version, len(manifest.Rules), manifest.SSLBumpEnabled, manifest.DLPEnabled)

	return &manifest, nil
}

// parseAuditJSONL parses an audit.jsonl file and returns a slice of audit log entries.
func parseAuditJSONL(jsonlPath string) ([]AuditLogEntry, error) {
	firewallPolicyLog.Printf("Parsing audit JSONL: %s", jsonlPath)

	file, err := os.Open(jsonlPath)
	if err != nil {
		return nil, fmt.Errorf("failed to open audit JSONL: %w", err)
	}
	defer file.Close()

	var entries []AuditLogEntry
	scanner := bufio.NewScanner(file)
	// Set larger buffer for potentially long lines
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		var entry AuditLogEntry
		if err := json.Unmarshal([]byte(line), &entry); err != nil {
			firewallPolicyLog.Printf("Skipping malformed JSONL line %d: %v", lineNum, err)
			continue
		}
		entries = append(entries, entry)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading audit JSONL: %w", err)
	}

	firewallPolicyLog.Printf("Parsed %d audit log entries from %d lines", len(entries), lineNum)
	return entries, nil
}

// domainMatchesRule checks if a domain matches a policy rule.
// Domain matching follows AWF conventions:
//   - ".github.com" matches both "github.com" and "*.github.com" (e.g., "api.github.com")
//   - "github.com" matches only exactly "github.com"
//   - Regex patterns (detected via aclName containing "regex" or regex metacharacters) are
//     compiled and matched against the domain.
func domainMatchesRule(host string, rule FirewallPolicyRule) bool {
	// Strip port from host if present
	domain := host
	if idx := strings.LastIndex(host, ":"); idx != -1 {
		domain = host[:idx]
	}
	domain = strings.ToLower(domain)

	// Detect regex-based rules: aclName contains "regex" or domains contain regex metacharacters
	isRegex := strings.Contains(strings.ToLower(rule.ACLName), "regex")
	if !isRegex {
		isRegex = slices.ContainsFunc(rule.Domains, containsRegexMeta)
	}

	if isRegex {
		return domainMatchesRegex(domain, rule.Domains)
	}

	for _, pattern := range rule.Domains {
		pattern = strings.ToLower(pattern)

		if strings.HasPrefix(pattern, ".") {
			// ".github.com" matches "github.com" and "*.github.com"
			baseDomain := pattern[1:] // Remove leading dot
			if domain == baseDomain || strings.HasSuffix(domain, pattern) {
				return true
			}
		} else {
			// Exact match
			if domain == pattern {
				return true
			}
		}
	}
	return false
}

// containsRegexMeta checks if a string contains regex metacharacters.
func containsRegexMeta(s string) bool {
	for _, c := range s {
		switch c {
		case '^', '$', '*', '+', '?', '(', ')', '[', ']', '{', '}', '|', '\\':
			return true
		}
	}
	return false
}

// domainMatchesRegex checks if a domain matches any regex pattern in the list.
func domainMatchesRegex(domain string, patterns []string) bool {
	for _, pattern := range patterns {
		//nolint:regexpdynamicpattern // Invalid user-provided patterns are logged and skipped.
		re, err := regexp.Compile(pattern)
		if err != nil {
			firewallPolicyLog.Printf("Invalid regex pattern %q: %v", pattern, err)
			continue
		}
		if re.MatchString(domain) {
			return true
		}
	}
	return false
}

// isEntryHTTPS determines if an audit log entry represents an HTTPS request.
// CONNECT method is the standard signal for HTTPS tunneling.
func isEntryHTTPS(entry AuditLogEntry) bool {
	return strings.EqualFold(entry.Method, "CONNECT")
}

// isEntryAllowed determines the observed outcome of a request.
// This mirrors the classification logic used by the firewall log parser.
func isEntryAllowed(entry AuditLogEntry) bool {
	status := entry.Status
	if status == http.StatusOK || status == http.StatusPartialContent || status == http.StatusNotModified {
		return true
	}
	if status == http.StatusForbidden || status == http.StatusProxyAuthRequired {
		return false
	}
	decision := entry.Decision
	if strings.Contains(decision, "TCP_TUNNEL") ||
		strings.Contains(decision, "TCP_HIT") ||
		strings.Contains(decision, "TCP_MISS") {
		return true
	}
	if strings.Contains(decision, "NONE_NONE") ||
		strings.Contains(decision, "TCP_DENIED") {
		return false
	}
	return false
}

// protocolMatches checks if a rule's protocol constraint matches the request.
// "both" matches everything; "https" matches only HTTPS; "http" matches only HTTP.
func protocolMatches(rule FirewallPolicyRule, isHTTPS bool) bool {
	switch strings.ToLower(rule.Protocol) {
	case "https":
		return isHTTPS
	case "http":
		return !isHTTPS
	default:
		// "both" or empty — matches everything
		return true
	}
}

// findMatchingRule finds the first matching policy rule for a given audit entry.
// Rules are evaluated in order; the first matching rule wins.
//
// This ports the TS audit-enricher.ts logic:
//  1. aclName === "all" rules match any domain (used for default deny rules)
//  2. Protocol matching: HTTPS-only rules won't match HTTP requests, and vice versa
//  3. Observed-decision validation: a rule only "matches" if its action matches the
//     observed outcome (allow rule only credited for allowed traffic, deny for denied)
func findMatchingRule(entry AuditLogEntry, rules []FirewallPolicyRule) *FirewallPolicyRule {
	isHTTPS := isEntryHTTPS(entry)
	expectedAction := "deny"
	if isEntryAllowed(entry) {
		expectedAction = "allow"
	}
	firewallPolicyLog.Printf("Finding matching rule for host=%s, expected_action=%s, rules=%d", entry.Host, expectedAction, len(rules))

	for i := range rules {
		rule := &rules[i]

		// Protocol check
		if !protocolMatches(*rule, isHTTPS) {
			continue
		}

		// aclName "all" is a catch-all rule (typically the default deny)
		if rule.ACLName == "all" {
			if rule.Action == expectedAction {
				firewallPolicyLog.Printf("Matched catch-all rule (action=%s) for host=%s", rule.Action, entry.Host)
				return rule
			}
			continue
		}

		// Domain match
		if domainMatchesRule(entry.Host, *rule) {
			if rule.Action == expectedAction {
				firewallPolicyLog.Printf("Matched rule %s (action=%s) for host=%s", rule.ACLName, rule.Action, entry.Host)
				return rule
			}
		}
	}
	firewallPolicyLog.Printf("No matching rule found for host=%s", entry.Host)
	return nil
}

// enrichWithPolicyRules enriches audit log entries with policy rule attribution.
func enrichWithPolicyRules(entries []AuditLogEntry, manifest *PolicyManifest) *PolicyAnalysis {
	firewallPolicyLog.Printf("Enriching %d entries with %d policy rules", len(entries), len(manifest.Rules))

	ruleHitMap := make(map[string]int)
	var deniedRequests []EnrichedRequest
	uniqueDomains := make(map[string]struct {
	})
	allowedCount := 0
	deniedCount := 0

	for _, entry := range entries {
		host := entry.Host
		if host == "" || host == "-" {
			continue
		}

		// Skip benign Squid operational entries (matches TS computeRuleStats filter)
		if entry.URL == "error:transaction-end-before-headers" {
			continue
		}

		// Strip port for domain tracking and normalize case
		domain := host
		if idx := strings.LastIndex(host, ":"); idx != -1 {
			domain = host[:idx]
		}
		uniqueDomains[strings.ToLower(domain)] = struct {
		}{}

		rule := findMatchingRule(entry, manifest.Rules)

		var enriched EnrichedRequest
		enriched.Timestamp = entry.Timestamp
		enriched.Host = host
		enriched.Status = entry.Status

		if rule != nil {
			enriched.RuleID = rule.ID
			enriched.Action = rule.Action
			ruleHitMap[rule.ID]++

			if rule.Action == "deny" {
				enriched.Reason = rule.Description
				deniedRequests = append(deniedRequests, enriched)
				deniedCount++
			} else {
				allowedCount++
			}
		} else {
			// No matching rule — derive outcome from observed entry decision
			if isEntryAllowed(entry) {
				enriched.RuleID = "(unattributed-allow)"
				enriched.Action = "allow"
				enriched.Reason = "Allowed (rule not identified)"
				allowedCount++
			} else {
				enriched.RuleID = "(implicit-deny)"
				enriched.Action = "deny"
				enriched.Reason = "No matching policy rule"
				deniedRequests = append(deniedRequests, enriched)
				deniedCount++
			}
		}
	}

	// Build rule hits table, preserving rule order
	var ruleHits []RuleHitStats
	for _, rule := range manifest.Rules {
		hits := ruleHitMap[rule.ID]
		ruleHits = append(ruleHits, RuleHitStats{
			Rule: rule,
			Hits: hits,
		})
	}

	// Build policy summary string
	sslBump := "disabled"
	if manifest.SSLBumpEnabled {
		sslBump = "enabled"
	}
	dlp := "disabled"
	if manifest.DLPEnabled {
		dlp = "enabled"
	}
	policySummary := fmt.Sprintf("%d rules, SSL Bump %s, DLP %s", len(manifest.Rules), sslBump, dlp)

	totalProcessed := allowedCount + deniedCount

	firewallPolicyLog.Printf("Enrichment complete: total=%d, allowed=%d, denied=%d, unique_domains=%d",
		totalProcessed, allowedCount, deniedCount, len(uniqueDomains))

	return &PolicyAnalysis{
		PolicySummary:  policySummary,
		RuleHits:       ruleHits,
		DeniedRequests: deniedRequests,
		TotalRequests:  totalProcessed,
		AllowedCount:   allowedCount,
		DeniedCount:    deniedCount,
		UniqueDomains:  len(uniqueDomains),
	}
}

// detectFirewallAuditArtifacts looks for policy-manifest.json and audit.jsonl in the run directory.
// Returns the paths if found, or empty strings if not present.
//
// Search order:
//  1. sandbox/firewall/audit/ — primary path after flattenUnifiedArtifact strips the /tmp/gh-aw/ prefix
//  2. agent/sandbox/firewall/audit/ — non-flattened unified agent artifact (new structure)
//  3. agent/tmp/gh-aw/sandbox/firewall/audit/ — non-flattened unified agent artifact (old structure)
//  4. firewall-audit*/ — legacy separate firewall-audit-logs artifact (backward compat)
func detectFirewallAuditArtifacts(runDir string) (manifestPath, auditJSONLPath string, err error) {
	firewallPolicyLog.Printf("Detecting firewall audit artifacts in: %s", runDir)

	// checkDir probes dir for policy-manifest.json and audit.jsonl, populating the
	// return variables for any files not yet found. Returns true when both are found.
	checkDir := func(dir, label string) bool {
		if manifestPath == "" {
			candidate := filepath.Join(dir, "policy-manifest.json")
			if fileutil.FileExists(candidate) {
				manifestPath = candidate
				firewallPolicyLog.Printf("Found policy manifest in %s: %s", label, manifestPath)
			}
		}
		if auditJSONLPath == "" {
			candidate := filepath.Join(dir, "audit.jsonl")
			if fileutil.FileExists(candidate) {
				auditJSONLPath = candidate
				firewallPolicyLog.Printf("Found audit JSONL in %s: %s", label, auditJSONLPath)
			}
		}
		return manifestPath != "" && auditJSONLPath != ""
	}

	// 1. Primary path: sandbox/firewall/audit/ after flattenUnifiedArtifact
	if checkDir(filepath.Join(runDir, "sandbox", "firewall", "audit"), "sandbox/firewall/audit") {
		return
	}

	// 2 & 3. Non-flattened unified agent artifact (before flattenUnifiedArtifact is called,
	// e.g., when the audit command is run on a directory populated via `gh run download`).
	// Handles "agent", "agent-artifacts", and workflow_call prefixed names (e.g. "hash-agent").
	if agentDir := findArtifactDir(runDir, "agent", "agent-artifacts"); agentDir != "" {
		// Guard: findArtifactDir checks existence but not type; skip if it resolved to a file.
		if info, err := os.Stat(agentDir); err != nil || !info.IsDir() {
			firewallPolicyLog.Printf("Skipping agent artifact path (not a directory): %s", agentDir)
		} else {
			agentBase := filepath.Base(agentDir)
			// New artifact structure (actions/upload-artifact v4+, /tmp/gh-aw/ prefix stripped):
			//   <agentDir>/sandbox/firewall/audit/
			if !checkDir(filepath.Join(agentDir, "sandbox", "firewall", "audit"), agentBase+"/sandbox/firewall/audit") {
				// Old artifact structure (/tmp/gh-aw/ prefix preserved inside the artifact):
				//   <agentDir>/tmp/gh-aw/sandbox/firewall/audit/
				checkDir(filepath.Join(agentDir, "tmp", "gh-aw", "sandbox", "firewall", "audit"), agentBase+constants.AWFAuditDir.String())
			}
			if manifestPath != "" && auditJSONLPath != "" {
				return manifestPath, auditJSONLPath, nil
			}
		}
	}

	// 4. Legacy separate firewall-audit-logs artifact (backward compat for older runs that
	// uploaded the audit directory as a standalone artifact named firewall-audit-logs).
	entries, readErr := os.ReadDir(runDir)
	if readErr != nil {
		err = fmt.Errorf("detectFirewallAuditArtifacts: reading run dir %s: %w", runDir, readErr)
		return
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, "firewall-audit") {
			checkDir(filepath.Join(runDir, name), name)
		}
	}

	return manifestPath, auditJSONLPath, nil
}

// analyzeFirewallPolicy loads policy manifest and audit JSONL, then enriches with rule attribution.
// Returns nil if no policy artifacts are found (graceful fallback to basic analysis).
func analyzeFirewallPolicy(runDir string, verbose bool) (*PolicyAnalysis, error) {
	manifestPath, auditJSONLPath, err := detectFirewallAuditArtifacts(runDir)
	if err != nil {
		return nil, fmt.Errorf("failed to detect firewall audit artifacts: %w", err)
	}

	if manifestPath == "" {
		firewallPolicyLog.Print("No policy manifest found, skipping policy analysis")
		return nil, nil
	}

	manifest, err := loadPolicyManifest(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("failed to load policy manifest: %w", err)
	}

	if auditJSONLPath == "" {
		// We have a manifest but no audit log — return policy summary without request enrichment
		firewallPolicyLog.Print("No audit JSONL found, returning manifest-only analysis")
		sslBump := "disabled"
		if manifest.SSLBumpEnabled {
			sslBump = "enabled"
		}
		dlp := "disabled"
		if manifest.DLPEnabled {
			dlp = "enabled"
		}

		return &PolicyAnalysis{
			PolicySummary: fmt.Sprintf("%d rules, SSL Bump %s, DLP %s", len(manifest.Rules), sslBump, dlp),
			RuleHits:      make([]RuleHitStats, 0),
		}, nil
	}

	entries, err := parseAuditJSONL(auditJSONLPath)
	if err != nil {
		return nil, fmt.Errorf("failed to parse audit JSONL: %w", err)
	}

	return enrichWithPolicyRules(entries, manifest), nil
}
