//go:build integration

package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/github/gh-aw/pkg/testutil"
)

// TestFirewallLogIntegration tests the complete firewall log analysis pipeline
func TestFirewallLogIntegration(t *testing.T) {
	t.Parallel()
	// Create a temporary directory for the test
	tempDir := testutil.TempDir(t, "test-*")
	runDir := filepath.Join(tempDir, "run-12345")
	err := os.MkdirAll(runDir, 0755)
	if err != nil {
		t.Fatalf("Failed to create run directory: %v", err)
	}

	// Create a subdirectory for firewall logs
	firewallLogsDir := filepath.Join(runDir, "firewall-logs")
	err = os.MkdirAll(firewallLogsDir, 0755)
	if err != nil {
		t.Fatalf("Failed to create firewall-logs directory: %v", err)
	}

	// Create realistic firewall log content based on the referenced run
	// https://github.com/github/gh-aw/actions/runs/18795259023
	realWorldLogContent := `# Firewall Access Log
# Generated by GitHub Agentic Workflows
1761332530.474 172.30.0.20:35288 api.enterprise.githubcopilot.com:443 140.82.112.22:443 1.1 CONNECT 200 TCP_TUNNEL:HIER_DIRECT api.enterprise.githubcopilot.com:443 "Mozilla/5.0 (compatible; Copilot/1.0)"
1761332531.123 172.30.0.20:35289 api.github.com:443 140.82.112.6:443 1.1 CONNECT 200 TCP_TUNNEL:HIER_DIRECT api.github.com:443 "Mozilla/5.0"
1761332532.456 172.30.0.20:35290 registry.npmjs.org:443 104.16.18.35:443 1.1 CONNECT 200 TCP_TUNNEL:HIER_DIRECT registry.npmjs.org:443 "-"
1761332533.789 172.30.0.20:35291 blocked-domain.example.com:443 0.0.0.0:0 1.1 CONNECT 403 NONE_NONE:HIER_NONE blocked-domain.example.com:443 "-"
1761332534.012 172.30.0.20:35292 denied.malicious.site:443 0.0.0.0:0 1.1 CONNECT 403 TCP_DENIED:HIER_NONE denied.malicious.site:443 "-"
1761332535.234 172.30.0.20:35293 pypi.org:443 151.101.0.63:443 1.1 CONNECT 200 TCP_TUNNEL:HIER_DIRECT pypi.org:443 "pip/23.0"
# Additional requests
1761332536.456 172.30.0.20:35294 api.github.com:443 140.82.112.6:443 1.1 GET 200 TCP_HIT:HIER_DIRECT api.github.com/repos/github/gh-aw "-"
1761332537.678 172.30.0.20:35295 blocked-domain.example.com:443 0.0.0.0:0 1.1 CONNECT 403 NONE_NONE:HIER_NONE blocked-domain.example.com:443 "-"
`

	// Write firewall log file
	logPath := filepath.Join(firewallLogsDir, "firewall-access.log")
	err = os.WriteFile(logPath, []byte(realWorldLogContent), 0644)
	if err != nil {
		t.Fatalf("Failed to create firewall log file: %v", err)
	}

	// Analyze the firewall logs
	analysis, err := analyzeFirewallLogs(runDir, true)
	if err != nil {
		t.Fatalf("Failed to analyze firewall logs: %v", err)
	}

	if analysis == nil {
		t.Fatal("Expected analysis result, got nil")
	}

	// Verify the analysis results
	expectedTotalRequests := 8
	if analysis.TotalRequests != expectedTotalRequests {
		t.Errorf("TotalRequests: got %d, want %d", analysis.TotalRequests, expectedTotalRequests)
	}

	expectedAllowedRequests := 5
	if analysis.AllowedRequests != expectedAllowedRequests {
		t.Errorf("AllowedRequests: got %d, want %d", analysis.AllowedRequests, expectedAllowedRequests)
	}

	expectedBlockedRequests := 3
	if analysis.BlockedRequests != expectedBlockedRequests {
		t.Errorf("BlockedRequests: got %d, want %d", analysis.BlockedRequests, expectedBlockedRequests)
	}

	// Verify allowed domains
	expectedAllowedDomains := []string{
		"api.enterprise.githubcopilot.com:443",
		"api.github.com:443",
		"pypi.org:443",
		"registry.npmjs.org:443",
	}
	if len(analysis.AllowedDomains) != len(expectedAllowedDomains) {
		t.Errorf("AllowedDomains count: got %d, want %d", len(analysis.AllowedDomains), len(expectedAllowedDomains))
	}
	for i, domain := range expectedAllowedDomains {
		if i >= len(analysis.AllowedDomains) {
			break
		}
		if analysis.AllowedDomains[i] != domain {
			t.Errorf("AllowedDomains[%d]: got %q, want %q", i, analysis.AllowedDomains[i], domain)
		}
	}

	// Verify blocked domains
	expectedBlockedDomains := []string{
		"blocked-domain.example.com:443",
		"denied.malicious.site:443",
	}
	if len(analysis.BlockedDomains) != len(expectedBlockedDomains) {
		t.Errorf("BlockedDomains count: got %d, want %d", len(analysis.BlockedDomains), len(expectedBlockedDomains))
	}
	for i, domain := range expectedBlockedDomains {
		if i >= len(analysis.BlockedDomains) {
			break
		}
		if analysis.BlockedDomains[i] != domain {
			t.Errorf("BlockedDomains[%d]: got %q, want %q", i, analysis.BlockedDomains[i], domain)
		}
	}

	// Verify per-domain statistics
	// api.github.com should have 2 allowed requests
	if stats, ok := analysis.RequestsByDomain["api.github.com:443"]; ok {
		if stats.Allowed != 2 {
			t.Errorf("api.github.com:443 Allowed: got %d, want 2", stats.Allowed)
		}
		if stats.Blocked != 0 {
			t.Errorf("api.github.com:443 Blocked: got %d, want 0", stats.Blocked)
		}
	} else {
		t.Error("api.github.com:443 not found in RequestsByDomain")
	}

	// blocked-domain.example.com should have 2 denied requests
	if stats, ok := analysis.RequestsByDomain["blocked-domain.example.com:443"]; ok {
		if stats.Allowed != 0 {
			t.Errorf("blocked-domain.example.com:443 Allowed: got %d, want 0", stats.Allowed)
		}
		if stats.Blocked != 2 {
			t.Errorf("blocked-domain.example.com:443 Blocked: got %d, want 2", stats.Blocked)
		}
	} else {
		t.Error("blocked-domain.example.com:443 not found in RequestsByDomain")
	}
}

// TestFirewallLogSummaryBuilding tests the aggregation of firewall logs across multiple runs
func TestFirewallLogSummaryBuilding(t *testing.T) {
	t.Parallel()
	// Create mock processed runs with firewall analysis
	processedRuns := []ProcessedRun{
		{
			Run: WorkflowRun{
				WorkflowName: "workflow-1",
			},
			FirewallAnalysis: &FirewallAnalysis{
				AnalysisBase: AnalysisBase{
					DomainBuckets: DomainBuckets{
						AllowedDomains: []string{"api.github.com:443", "api.npmjs.org:443"},
						BlockedDomains: []string{"blocked.example.com:443"},
					},
					TotalRequests:   10,
					AllowedRequests: 8,
					BlockedRequests: 2,
				},
				RequestsByDomain: map[string]DomainRequestStats{
					"api.github.com:443":      {Allowed: 5, Blocked: 0},
					"api.npmjs.org:443":       {Allowed: 3, Blocked: 0},
					"blocked.example.com:443": {Allowed: 0, Blocked: 2},
				},
			},
		},
		{
			Run: WorkflowRun{
				WorkflowName: "workflow-2",
			},
			FirewallAnalysis: &FirewallAnalysis{
				AnalysisBase: AnalysisBase{
					DomainBuckets: DomainBuckets{
						AllowedDomains: []string{"api.github.com:443"},
						BlockedDomains: []string{"denied.site:443"},
					},
					TotalRequests:   5,
					AllowedRequests: 3,
					BlockedRequests: 2,
				},
				RequestsByDomain: map[string]DomainRequestStats{
					"api.github.com:443": {Allowed: 3, Blocked: 0},
					"denied.site:443":    {Allowed: 0, Blocked: 2},
				},
			},
		},
	}

	// Build the firewall log summary
	summary := buildFirewallLogSummary(processedRuns)

	if summary == nil {
		t.Fatal("Expected summary, got nil")
	}

	// Verify aggregated totals
	expectedTotalRequests := 15
	if summary.TotalRequests != expectedTotalRequests {
		t.Errorf("TotalRequests: got %d, want %d", summary.TotalRequests, expectedTotalRequests)
	}

	expectedAllowedRequests := 11
	if summary.AllowedRequests != expectedAllowedRequests {
		t.Errorf("AllowedRequests: got %d, want %d", summary.AllowedRequests, expectedAllowedRequests)
	}

	expectedBlockedRequests := 4
	if summary.BlockedRequests != expectedBlockedRequests {
		t.Errorf("BlockedRequests: got %d, want %d", summary.BlockedRequests, expectedBlockedRequests)
	}

	// Verify unique domains
	expectedAllowedCount := 2
	if len(summary.AllowedDomains) != expectedAllowedCount {
		t.Errorf("AllowedDomains count: got %d, want %d", len(summary.AllowedDomains), expectedAllowedCount)
	}

	expectedBlockedCount := 2
	if len(summary.BlockedDomains) != expectedBlockedCount {
		t.Errorf("BlockedDomains count: got %d, want %d", len(summary.BlockedDomains), expectedBlockedCount)
	}

	// Verify aggregated per-domain stats
	// api.github.com should have 8 allowed requests (5 + 3)
	if stats, ok := summary.RequestsByDomain["api.github.com:443"]; ok {
		if stats.Allowed != 8 {
			t.Errorf("api.github.com:443 aggregated Allowed: got %d, want 8", stats.Allowed)
		}
	} else {
		t.Error("api.github.com:443 not found in aggregated RequestsByDomain")
	}

	// Verify by-workflow breakdown
	if len(summary.ByWorkflow) != 2 {
		t.Errorf("ByWorkflow count: got %d, want 2", len(summary.ByWorkflow))
	}

	if workflow1, ok := summary.ByWorkflow["workflow-1"]; ok {
		if workflow1.TotalRequests != 10 {
			t.Errorf("workflow-1 TotalRequests: got %d, want 10", workflow1.TotalRequests)
		}
	} else {
		t.Error("workflow-1 not found in ByWorkflow")
	}
}

// TestAnalyzeFirewallLogsFromSandboxPath tests that firewall logs can be found
// in sandbox/firewall/logs/ directory (the path after artifact download)
func TestAnalyzeFirewallLogsFromSandboxPath(t *testing.T) {
	t.Parallel()
	// Create temp directory for test
	runDir := testutil.TempDir(t, "firewall-test-*")

	// Create sandbox/firewall/logs directory (path after artifact download)
	firewallLogsDir := filepath.Join(runDir, "sandbox", "firewall", "logs")
	err := os.MkdirAll(firewallLogsDir, 0755)
	if err != nil {
		t.Fatalf("should create sandbox/firewall/logs directory: %v", err)
	}

	// Create test firewall log file
	logContent := `# Firewall access log
1701234567.123 172.30.0.20:35288 api.github.com:443 140.82.112.22:443 1.1 CONNECT 200 TCP_TUNNEL:HIER_DIRECT api.github.com:443 "-"
1701234568.456 172.30.0.20:35289 api.npmjs.org:443 151.101.0.162:443 1.1 CONNECT 200 TCP_TUNNEL:HIER_DIRECT api.npmjs.org:443 "-"
1701234569.789 172.30.0.20:35290 blocked.example.com:443 0.0.0.0:0 1.1 CONNECT 403 NONE_NONE:HIER_NONE blocked.example.com:443 "-"
1701234570.012 172.30.0.20:35291 blocked.test.com:443 0.0.0.0:0 1.1 CONNECT 403 NONE_NONE:HIER_NONE blocked.test.com:443 "-"
`
	logPath := filepath.Join(firewallLogsDir, "firewall-access.log")
	err = os.WriteFile(logPath, []byte(logContent), 0644)
	if err != nil {
		t.Fatalf("should write test firewall log: %v", err)
	}

	// Test the analysis
	analysis, err := analyzeFirewallLogs(runDir, true)
	if err != nil {
		t.Fatalf("analyzeFirewallLogs should succeed: %v", err)
	}
	if analysis == nil {
		t.Fatal("Analysis should not be nil")
	}

	// Verify results
	if analysis.TotalRequests != 4 {
		t.Errorf("TotalRequests: got %d, want 4", analysis.TotalRequests)
	}
	if analysis.AllowedRequests != 2 {
		t.Errorf("AllowedRequests: got %d, want 2", analysis.AllowedRequests)
	}
	if analysis.BlockedRequests != 2 {
		t.Errorf("BlockedRequests: got %d, want 2", analysis.BlockedRequests)
	}
}
