package cli

import (
	"bufio"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/github/gh-aw/pkg/console"
	"github.com/github/gh-aw/pkg/fileutil"
	"github.com/github/gh-aw/pkg/logger"
	"github.com/github/gh-aw/pkg/sliceutil"
)

var firewallLogLog = logger.New("cli:firewall_log")

// unknownDomain is a sentinel value used in RequestsByDomain when iptables drops
// traffic before Squid can identify the destination, and no fallback IP:port is
// available (both domain and destIPPort are "-"). These entries are tracked for
// informational purposes but excluded from BlockedDomains/AllowedDomains since
// they carry no actionable domain information.
const unknownDomain = "(unknown)"

// Pre-compiled regexes for firewall log parsing (performance optimization)
var (
	firewallLogFieldSplitter = regexp.MustCompile(`(?:[^\s"]+|"[^"]*")+`)

	// agentLogAllowDomainsPattern matches Codex CLI firewall warning lines that suggest
	// adding a blocked domain to the allow-list.
	// Captures the full token after --allow-domains (up to whitespace) to support
	// hostnames, protocol prefixes, wildcard patterns, and ports.
	// Example: "add --allow-domains chatgpt.com to your command"
	// Example: "add --allow-domains chatgpt.com,other.com to your command"
	// Example: "add --allow-domains https://api.example.com:443 to your command"
	agentLogAllowDomainsPattern = regexp.MustCompile(`--allow-domains\s+([^\s]+)`)
)

// Firewall Log Parser
//
// This package provides a Go implementation of the firewall logs parser that mirrors
// the JavaScript parser in pkg/workflow/js/parse_firewall_logs.cjs. It parses firewall
// proxy logs generated by agentic workflows to track network access patterns.
//
// # Log Format
//
// Firewall logs use a space-separated format with 10 fields:
//   timestamp client_ip:port domain dest_ip:port proto method status decision url user_agent
//
// Example log entries:
//   1761332530.474 172.30.0.20:35288 api.enterprise.githubcopilot.com:443 140.82.112.22:443 1.1 CONNECT 200 TCP_TUNNEL:HIER_DIRECT api.enterprise.githubcopilot.com:443 "-"
//   1761332531.123 172.30.0.20:35289 blocked.example.com:443 140.82.112.23:443 1.1 CONNECT 403 NONE_NONE:HIER_NONE blocked.example.com:443 "-"
//
// # Field Mapping
//
// This parser maintains field-for-field parity with the JavaScript parser:
//  1. timestamp     - Unix timestamp with decimal (e.g., "1761332530.474")
//  2. client_ip:port - Client IP and port (e.g., "172.30.0.20:35288") or "-"
//  3. domain        - Target domain:port (e.g., "api.github.com:443") or "-"
//  4. dest_ip:port  - Destination IP and port (e.g., "140.82.112.22:443") or "-"
//  5. proto         - Protocol version (e.g., "1.1") or "-"
//  6. method        - HTTP method (e.g., "CONNECT", "GET") or "-"
//  7. status        - HTTP status code (e.g., "200", "403") or "0"
//  8. decision      - Proxy decision (e.g., "TCP_TUNNEL:HIER_DIRECT") or "-"
//  9. url           - Request URL (e.g., "api.github.com:443") or "-"
// 10. user_agent    - User agent string (quoted, e.g., "Mozilla/5.0" or "-")
//
// # Normalization and Error Handling
//
// - Comment lines (starting with #) are skipped
// - Empty lines are skipped
// - Lines with fewer than 10 fields are rejected
// - Only timestamp field is validated (must be numeric with optional decimal point)
// - Other fields are accepted as-is without validation (matches JavaScript parser behavior)
// - User agent quotes are automatically stripped
//
// # Request Classification
//
// Requests are classified as allowed or denied based on status code and decision:
//
// Allowed indicators:
//   - Status codes: 200, 206, 304
//   - Decisions containing: TCP_TUNNEL, TCP_HIT, TCP_MISS
//
// Denied indicators:
//   - Status codes: 403, 407
//   - Decisions containing: NONE_NONE, TCP_DENIED
//
// Default: Denied (for safety when classification is ambiguous)
//
// # Output Examples
//
// Console output (via console.RenderStruct):
//   🔥 Firewall Log Analysis
//   Total Requests : 4
//   Allowed        : 2
//   Denied         : 2
//
// JSON output:
//   {
//     "total_requests": 4,
//     "allowed_requests": 2,
//     "blocked_requests": 2,
//     "allowed_domains": ["api.github.com:443", "api.npmjs.org:443"],
//     "blocked_domains": ["blocked.example.com:443", "blocked.test.com:443"],
//     "requests_by_domain": {
//       "api.github.com:443": {"allowed": 1, "blocked": 0},
//       "blocked.example.com:443": {"allowed": 0, "blocked": 1}
//     }
//   }

// FirewallLogEntry represents a parsed firewall log entry
// Format: timestamp client_ip:port domain dest_ip:port proto method status decision url user_agent
type FirewallLogEntry struct {
	Timestamp    string
	ClientIPPort string
	Domain       string
	DestIPPort   string
	Proto        string
	Method       string
	Status       string
	Decision     string
	URL          string
	UserAgent    string
}

// FirewallAnalysis represents analysis of firewall logs
// This mirrors the structure from the JavaScript parser
type FirewallAnalysis struct {
	AnalysisBase
	RequestsByDomain map[string]DomainRequestStats `json:"requests_by_domain,omitempty"`
}

// AddMetrics adds metrics from another analysis
func (f *FirewallAnalysis) AddMetrics(other LogAnalysis) {
	if otherFirewall, ok := other.(*FirewallAnalysis); ok {
		f.addBaseMetrics(&otherFirewall.AnalysisBase)

		// Merge request stats by domain (firewall-specific)
		if f.RequestsByDomain == nil {
			f.RequestsByDomain = make(map[string]DomainRequestStats)
		}
		for domain, stats := range otherFirewall.RequestsByDomain {
			existing := f.RequestsByDomain[domain]
			existing.Allowed += stats.Allowed
			existing.Blocked += stats.Blocked
			f.RequestsByDomain[domain] = existing
		}
	}
}

// DomainRequestStats tracks request statistics per domain
type DomainRequestStats struct {
	Allowed int `json:"allowed"`
	Blocked int `json:"blocked"`
}

// parseFirewallLogLine parses a single firewall log line
// Format: timestamp client_ip:port domain dest_ip:port proto method status decision url user_agent
// Returns nil if the line is invalid or should be skipped
func parseFirewallLogLine(line string) *FirewallLogEntry {
	trimmed := strings.TrimSpace(line)
	if trimmed == "" || strings.HasPrefix(trimmed, "#") {
		return nil
	}

	// Split by whitespace but preserve quoted strings
	// This regex matches non-whitespace sequences or quoted strings
	fields := firewallLogFieldSplitter.FindAllString(trimmed, -1)

	if len(fields) < 10 {
		return nil
	}

	// Only validate timestamp (essential for log format detection)
	// This matches the JavaScript parser behavior which only validates timestamp
	timestamp := fields[0]
	if matched, _ := regexp.MatchString(`^\d+(\.\d+)?$`, timestamp); !matched {
		return nil
	}

	// Extract fields without validation (matches JavaScript parser)
	clientIPPort := fields[1]
	domain := fields[2]
	destIPPort := fields[3]
	status := fields[6]
	decision := fields[7]

	// Remove quotes from user agent
	userAgent := fields[9]
	userAgent = strings.Trim(userAgent, `"`)

	return &FirewallLogEntry{
		Timestamp:    timestamp,
		ClientIPPort: clientIPPort,
		Domain:       domain,
		DestIPPort:   destIPPort,
		Proto:        fields[4],
		Method:       fields[5],
		Status:       status,
		Decision:     decision,
		URL:          fields[8],
		UserAgent:    userAgent,
	}
}

// isRequestAllowed determines if a request was allowed based on decision and status
// This mirrors the logic from the JavaScript parser
func isRequestAllowed(decision, status string) bool {
	// Check status code first
	if statusCode, err := strconv.Atoi(status); err == nil {
		if statusCode == http.StatusOK || statusCode == http.StatusPartialContent || statusCode == http.StatusNotModified {
			return true
		}
		if statusCode == http.StatusForbidden || statusCode == http.StatusProxyAuthRequired {
			return false
		}
	}

	// Check decision field
	if strings.Contains(decision, "TCP_TUNNEL") ||
		strings.Contains(decision, "TCP_HIT") ||
		strings.Contains(decision, "TCP_MISS") {
		return true
	}

	if strings.Contains(decision, "NONE_NONE") ||
		strings.Contains(decision, "TCP_DENIED") {
		return false
	}

	// Default to denied for safety
	return false
}

// parseFirewallLog parses a firewall log file and returns analysis
func parseFirewallLog(logPath string, verbose bool) (*FirewallAnalysis, error) {
	firewallLogLog.Printf("Parsing firewall log: %s", logPath)
	file, err := os.Open(logPath)
	if err != nil {
		firewallLogLog.Printf("Failed to open firewall log: %v", err)
		return nil, fmt.Errorf("failed to open firewall log: %w", err)
	}
	defer file.Close()

	analysis := &FirewallAnalysis{
		RequestsByDomain: make(map[string]DomainRequestStats),
	}

	allowedDomainsSet := make(map[string]struct{})
	blockedDomainsSet := make(map[string]struct{})

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		entry := parseFirewallLogLine(line)
		if entry == nil {
			continue
		}

		// Skip internal Squid error entries (client IP ::1, no domain, no destination)
		// These are internal Squid connection errors (e.g., error:transaction-end-before-headers)
		// and are not actual external network requests.
		// Example: 1773003472.027 ::1:52010 - -:- 0.0 - 0 NONE_NONE:HIER_NONE error:transaction-end-before-headers "-"
		if strings.HasPrefix(entry.ClientIPPort, "::1:") && entry.Domain == "-" && (entry.DestIPPort == "-:-" || entry.DestIPPort == "-") {
			continue
		}

		analysis.TotalRequests++

		// Determine if request was allowed or blocked
		isAllowed := isRequestAllowed(entry.Decision, entry.Status)

		// Extract domain - when domain is "-" (iptables-dropped traffic not visible to Squid),
		// fall back to dest IP:port so blocked requests show their actual destination instead of "-"
		// Only fall back if destIPPort is a valid host:port (not "-" or "-:-" which are placeholder values)
		domain := entry.Domain
		if domain == "-" && entry.DestIPPort != "-" && entry.DestIPPort != "-:-" {
			domain = entry.DestIPPort
		} else if domain == "-" {
			// Both domain and destIPPort are placeholders: iptables dropped the traffic before
			// Squid could identify the destination. Use a sentinel so the entry appears in
			// RequestsByDomain for informational purposes, but do NOT add it to the domain sets
			// since "-" is not an actionable domain name.
			domain = unknownDomain
		}

		if isAllowed {
			analysis.AllowedRequests++
			if domain != unknownDomain {
				allowedDomainsSet[domain] = struct{}{}
			}
		} else {
			analysis.BlockedRequests++
			if domain != unknownDomain {
				blockedDomainsSet[domain] = struct{}{}
			}
		}

		// Track request count per domain
		stats := analysis.RequestsByDomain[domain]
		if isAllowed {
			stats.Allowed++
		} else {
			stats.Blocked++
		}
		analysis.RequestsByDomain[domain] = stats
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading firewall log: %w", err)
	}

	// Convert sets to sorted slices
	analysis.AllowedDomains = sliceutil.MapKeys(allowedDomainsSet)
	analysis.BlockedDomains = sliceutil.MapKeys(blockedDomainsSet)

	sort.Strings(analysis.AllowedDomains)
	sort.Strings(analysis.BlockedDomains)

	if firewallLogLog.Enabled() {
		firewallLogLog.Printf("Firewall log parsed: total=%d, allowed=%d, blocked=%d, allowed_domains=%d, blocked_domains=%d",
			analysis.TotalRequests, analysis.AllowedRequests, analysis.BlockedRequests,
			len(analysis.AllowedDomains), len(analysis.BlockedDomains))
	}
	return analysis, nil
}

// analyzeFirewallLogs analyzes firewall logs in a run directory
// Firewall logs are stored in /tmp/gh-aw/squid-logs-{workflow-name}/ during execution
// and uploaded as artifacts to the logs directory
func analyzeFirewallLogs(runDir string, verbose bool) (*FirewallAnalysis, error) {
	firewallLogLog.Printf("Analyzing firewall logs in: %s", runDir)
	// Look for firewall logs in the run directory
	// The logs could be in several locations depending on how they were uploaded

	// First, check for sandbox/firewall/logs/ directory (new path after artifact download)
	// Firewall logs are uploaded from /tmp/gh-aw/sandbox/firewall/logs/ and the common parent
	// /tmp/gh-aw/ is stripped during artifact upload, resulting in sandbox/firewall/logs/ after download.
	// Within that directory, AWF writes Squid access logs to a squid-logs/ subdirectory.
	sandboxFirewallLogsDir := filepath.Join(runDir, "sandbox", "firewall", "logs")
	if fileutil.DirExists(sandboxFirewallLogsDir) {
		// AWF writes the Squid access.log to a squid-logs/ subdirectory within --proxy-logs-dir.
		// Check for that subdirectory first before falling back to the parent directory.
		squidSubDir := filepath.Join(sandboxFirewallLogsDir, "squid-logs")
		if fileutil.DirExists(squidSubDir) {
			firewallLogLog.Printf("Found firewall logs directory: sandbox/firewall/logs/squid-logs")
			if verbose {
				fmt.Fprintln(os.Stderr, console.FormatInfoMessage("Found firewall logs directory: sandbox/firewall/logs/squid-logs"))
			}
			analysis, err := analyzeMultipleFirewallLogs(squidSubDir, verbose)
			if err != nil {
				return nil, err
			}
			if analysis != nil {
				return analysis, nil
			}
		}
		// Fall back to direct *.log files at the sandbox/firewall/logs/ level (older AWF layout).
		firewallLogLog.Printf("Found firewall logs directory: sandbox/firewall/logs")
		if verbose {
			fmt.Fprintln(os.Stderr, console.FormatInfoMessage("Found firewall logs directory: sandbox/firewall/logs"))
		}
		return analyzeMultipleFirewallLogs(sandboxFirewallLogsDir, verbose)
	}

	// Second, check for directories starting with squid-logs or firewall-logs (legacy paths)
	// The actual directories may have workflow-specific suffixes like:
	// - squid-logs-smoke-copilot-firewall
	// - squid-logs-changeset-generator
	// - firewall-logs-{workflow-name}
	entries, err := os.ReadDir(runDir)
	if err != nil {
		firewallLogLog.Printf("Failed to read run directory: %v", err)
		return nil, fmt.Errorf("failed to read run directory: %w", err)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, "squid-logs") || strings.HasPrefix(name, "firewall-logs") {
			logsDir := filepath.Join(runDir, name)
			firewallLogLog.Printf("Found firewall logs directory: %s", name)
			if verbose {
				fmt.Fprintln(os.Stderr, console.FormatInfoMessage("Found firewall logs directory: "+name))
			}
			return analyzeMultipleFirewallLogs(logsDir, verbose)
		}
	}

	// Check for individual log files in the run directory
	files, err := filepath.Glob(filepath.Join(runDir, "*.log"))
	if err != nil {
		return nil, fmt.Errorf("failed to find firewall log files: %w", err)
	}

	// Filter for firewall log files (they typically have "access" or "firewall" in the name)
	firewallLogs := sliceutil.Filter(files, func(file string) bool {
		basename := filepath.Base(file)
		return strings.Contains(basename, "firewall") ||
			(strings.Contains(basename, "access") && !strings.Contains(basename, "access-"))
	})

	if len(firewallLogs) == 0 {
		firewallLogLog.Print("No firewall logs found")
		if verbose {
			fmt.Fprintln(os.Stderr, console.FormatInfoMessage("No firewall logs found in "+runDir))
		}
		return nil, nil
	}

	// Parse the first firewall log file found
	firewallLogLog.Printf("Found %d firewall log files, analyzing first: %s", len(firewallLogs), filepath.Base(firewallLogs[0]))
	if verbose {
		fmt.Fprintln(os.Stderr, console.FormatInfoMessage("Analyzing firewall log: "+filepath.Base(firewallLogs[0])))
	}

	return parseFirewallLog(firewallLogs[0], verbose)
}

// analyzeMultipleFirewallLogs analyzes multiple firewall log files in a directory
func analyzeMultipleFirewallLogs(logsDir string, verbose bool) (*FirewallAnalysis, error) {
	return aggregateLogFiles(
		logsDir,
		"*.log",
		verbose,
		parseFirewallLog,
		func() *FirewallAnalysis {
			return &FirewallAnalysis{
				RequestsByDomain: make(map[string]DomainRequestStats),
			}
		},
	)
}

// extractFirewallFromAgentLog scans agent-stdio.log for firewall-blocked domain warnings.
// This supplements dedicated proxy firewall logs (e.g., Squid access logs) by extracting
// network-block information from the agent's own output when proxy logs are unavailable.
//
// The Codex CLI emits lines containing "--allow-domains <domain>" when a domain is blocked
// by the sandbox firewall. For example:
//
//	"[WARN] chatgpt.com is not in the allowed domains. To allow access, add --allow-domains chatgpt.com to your command."
//
// Returns nil when no agent-stdio.log exists or no blocked domains are found.
func extractFirewallFromAgentLog(logsPath string, verbose bool) *FirewallAnalysis {
	agentStdioPath := filepath.Clean(filepath.Join(logsPath, "agent-stdio.log"))
	content, err := os.ReadFile(agentStdioPath) // #nosec G304 -- path is cleaned via filepath.Clean and logsPath is a trusted run output directory
	if err != nil {
		// File not present is normal (agent didn't run, or run used a different log path)
		firewallLogLog.Printf("No agent-stdio.log found at %s: %v", agentStdioPath, err)
		return nil
	}

	blockedDomainsSet := make(map[string]struct{})
	for line := range strings.SplitSeq(string(content), "\n") {
		if matches := agentLogAllowDomainsPattern.FindStringSubmatch(line); len(matches) > 1 {
			// Strip surrounding double quotes if present (e.g., --allow-domains "dom1,dom2")
			allowDomains := strings.Trim(matches[1], "\"")
			// Domains can be comma-separated in the suggestion
			for domain := range strings.SplitSeq(allowDomains, ",") {
				if d := strings.TrimSpace(domain); d != "" {
					blockedDomainsSet[d] = struct{}{}
				}
			}
		}
	}

	if len(blockedDomainsSet) == 0 {
		firewallLogLog.Printf("No blocked domains found in agent-stdio.log at %s", agentStdioPath)
		return nil
	}

	blockedDomains := sliceutil.SortedKeys(blockedDomainsSet)

	analysis := &FirewallAnalysis{
		AnalysisBase: AnalysisBase{
			TotalRequests:   len(blockedDomains),
			BlockedRequests: len(blockedDomains),
		},
		RequestsByDomain: make(map[string]DomainRequestStats),
	}
	analysis.SetBlockedDomains(blockedDomains)
	for _, d := range blockedDomains {
		analysis.RequestsByDomain[d] = DomainRequestStats{Blocked: 1}
	}

	firewallLogLog.Printf("Extracted %d firewall-blocked domain(s) from agent-stdio.log: %s", len(blockedDomains), strings.Join(blockedDomains, ", "))
	if verbose {
		fmt.Fprintln(os.Stderr, console.FormatWarningMessage(fmt.Sprintf(
			"Found %d firewall-blocked domain(s) in agent log: %s",
			len(blockedDomains), strings.Join(blockedDomains, ", "),
		)))
	}

	return analysis
}
