//go:build !integration

package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/github/gh-aw/pkg/parser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIsCompiledUpToDate(t *testing.T) {
	t.Parallel()
	tmpDir := t.TempDir()

	// Minimal valid workflow markdown
	mdContent := `---
name: test-workflow
on:
  workflow_dispatch:
engine: copilot
---

# Test Workflow

A simple test workflow.
`

	mdPath := filepath.Join(tmpDir, "test-workflow.md")
	require.NoError(t, os.WriteFile(mdPath, []byte(mdContent), 0644), "Should write test workflow")

	// Compute the real frontmatter hash for the test markdown
	cache := parser.NewImportCache("")
	realHash, err := parser.ComputeFrontmatterHashFromFile(mdPath, cache)
	require.NoError(t, err, "Should compute frontmatter hash")

	t.Run("matching hash returns Yes", func(t *testing.T) {
		lockPath := filepath.Join(tmpDir, "test-workflow.lock.yml")
		lockContent := `# gh-aw-metadata: {"schema_version":"v1","frontmatter_hash":"` + realHash + `"}
name: test-workflow
`
		require.NoError(t, os.WriteFile(lockPath, []byte(lockContent), 0644), "Should write lock file")

		result := isCompiledUpToDate(mdPath, lockPath)
		assert.Equal(t, "Yes", result, "Matching hash should return Yes")
	})

	t.Run("mismatched hash returns No", func(t *testing.T) {
		lockPath := filepath.Join(tmpDir, "mismatched.lock.yml")
		lockContent := `# gh-aw-metadata: {"schema_version":"v1","frontmatter_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
name: test-workflow
`
		require.NoError(t, os.WriteFile(lockPath, []byte(lockContent), 0644), "Should write lock file")

		result := isCompiledUpToDate(mdPath, lockPath)
		assert.Equal(t, "No", result, "Mismatched hash should return No")
	})

	t.Run("legacy lock file without hash returns Yes", func(t *testing.T) {
		lockPath := filepath.Join(tmpDir, "legacy.lock.yml")
		lockContent := `#
# This file was automatically generated by gh-aw. DO NOT EDIT.
#
name: test-workflow
`
		require.NoError(t, os.WriteFile(lockPath, []byte(lockContent), 0644), "Should write legacy lock file")

		result := isCompiledUpToDate(mdPath, lockPath)
		assert.Equal(t, "Yes", result, "Legacy lock file without hash should return Yes")
	})

	t.Run("nonexistent lock file returns No", func(t *testing.T) {
		result := isCompiledUpToDate(mdPath, filepath.Join(tmpDir, "nonexistent.lock.yml"))
		assert.Equal(t, "No", result, "Nonexistent lock file should return No")
	})
}
