package filecheck

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func TestBuildGeneratedIndex(t *testing.T) {
	t.Parallel()
	const generatedFilename = "generated.go"
	const generatedAdjustedFilename = "/virtual/generated_alias.go"
	const regularFilename = "regular.go"

	fset := token.NewFileSet()
	generatedFile, err := parser.ParseFile(fset, generatedFilename, `// Code generated by test. DO NOT EDIT.
//line /virtual/generated_alias.go:1
package p

func generated() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseFile(generated) error = %v", err)
	}
	regularFile, err := parser.ParseFile(fset, regularFilename, `package p

func regular() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseFile(regular) error = %v", err)
	}

	idx := BuildGeneratedIndex(&analysis.Pass{
		Fset:  fset,
		Files: []*ast.File{generatedFile, regularFile},
		Pkg:   types.NewPackage("github.com/github/gh-aw/pkg/linters/internal/filecheck/testdata", "p"),
	})
	if !IsGeneratedFile(generatedFilename, idx) {
		t.Fatalf("expected %q to be marked generated", generatedFilename)
	}
	if !IsGeneratedFile(generatedAdjustedFilename, idx) {
		t.Fatalf("expected adjusted filename %q to be marked generated", generatedAdjustedFilename)
	}
	if IsGeneratedFile(regularFilename, idx) {
		t.Fatalf("did not expect %q to be marked generated", regularFilename)
	}
}

func TestShouldSkipFilename(t *testing.T) {
	t.Parallel()
	idx := GeneratedIndex{
		"generated.go": {},
	}

	if !ShouldSkipFilename("example_test.go", idx) {
		t.Fatalf("expected test file to be skipped")
	}
	if !ShouldSkipFilename("generated.go", idx) {
		t.Fatalf("expected generated file to be skipped")
	}
	if ShouldSkipFilename("regular.go", idx) {
		t.Fatalf("did not expect regular file to be skipped")
	}
}

func TestBuildGeneratedIndexDoesNotMarkNonGeneratedWithLineDirective(t *testing.T) {
	t.Parallel()
	const regularFilename = "regular.go"
	const adjustedFilename = "/virtual/regular_alias.go"

	fset := token.NewFileSet()
	regularFile, err := parser.ParseFile(fset, regularFilename, `//line /virtual/regular_alias.go:1
package p

func regular() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseFile(regular) error = %v", err)
	}

	idx := BuildGeneratedIndex(&analysis.Pass{
		Fset:  fset,
		Files: []*ast.File{regularFile},
		Pkg:   types.NewPackage("github.com/github/gh-aw/pkg/linters/internal/filecheck/testdata", "p"),
	})
	if IsGeneratedFile(regularFilename, idx) {
		t.Fatalf("did not expect %q to be marked generated", regularFilename)
	}
	if IsGeneratedFile(adjustedFilename, idx) {
		t.Fatalf("did not expect adjusted filename %q to be marked generated", adjustedFilename)
	}
}
