const plugin = require("./dist/index.js");

module.exports = [
  {
    files: ["*.cjs", "**/*.cjs"],
    ignores: ["**/*.test.cjs", "**/*.test.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
    },
    plugins: {
      "gh-aw-custom": plugin,
    },
    rules: {
      "gh-aw-custom/no-core-exportvariable-non-string": "warn",
      "gh-aw-custom/no-core-setoutput-non-string": "warn",
      "gh-aw-custom/no-throw-plain-object": "warn",
      "gh-aw-custom/no-github-request-interpolated-route": "warn",
      "gh-aw-custom/no-json-stringify-error": "warn",
      "gh-aw-custom/no-json-stringify-equality": "warn",
      "gh-aw-custom/no-json-stringify-set-or-map": "warn",
      "gh-aw-custom/no-unsafe-catch-error-property": "warn",
      "gh-aw-custom/no-unsafe-promise-catch-error-property": "warn",
      "gh-aw-custom/prefer-get-error-message": "warn",
      "gh-aw-custom/prefer-get-error-message-over-string": "warn",
      "gh-aw-custom/prefer-number-isnan": "warn",
      "gh-aw-custom/require-async-entrypoint-catch": "warn",
      "gh-aw-custom/require-await-core-summary-write": "warn",
      "gh-aw-custom/require-fs-close-sync": "warn",
      "gh-aw-custom/require-error-cause-in-rethrow": "warn",
      "gh-aw-custom/require-fs-sync-try-catch": "warn",
      "gh-aw-custom/require-json-parse-try-catch": "warn",
      "gh-aw-custom/require-mkdirsync-try-catch": "warn",
      "gh-aw-custom/require-mkdtempsync-try-catch": "warn",
      "gh-aw-custom/require-realpathsync-try-catch": "warn",
      "gh-aw-custom/require-rmsync-try-catch": "warn",
      "gh-aw-custom/require-parseInt-radix": "warn",
      "gh-aw-custom/require-return-after-core-setfailed": "warn",
      "gh-aw-custom/require-spawnsync-error-check": "warn",
      "gh-aw-custom/require-spawn-error-listener": "warn",
      "gh-aw-custom/require-new-url-try-catch": "warn",
      "gh-aw-custom/require-decodeuricomponent-try-catch": "warn",
      "gh-aw-custom/prefer-core-logging": "warn",
      "gh-aw-custom/no-core-error-then-process-exit": "warn",
      "gh-aw-custom/no-core-error-then-process-exitcode": "warn",
      "gh-aw-custom/no-child-process-interpolated-command": "warn",
      "gh-aw-custom/no-exec-interpolated-command": "warn",
      "gh-aw-custom/require-execsync-try-catch": "warn",
      "gh-aw-custom/require-execfilesync-try-catch": "warn",
      "gh-aw-custom/require-fs-io-try-catch": "warn",
      "gh-aw-custom/require-fs-chmod-try-catch": "warn",
      "gh-aw-custom/no-setfailed-then-exit-zero": "warn",
      "gh-aw-custom/no-err-stack-then-string-fallback": "warn",
      "gh-aw-custom/no-caught-error-interpolation": "warn",
      "gh-aw-custom/require-fetch-try-catch": "warn",
      "gh-aw-custom/no-core-error-then-setfailed": "warn",
      "gh-aw-custom/no-duplicate-constant-values": "warn",
      "gh-aw-custom/require-escaped-regexp-interpolation": "warn",
      "gh-aw-custom/require-fetch-timeout": "warn",
      "gh-aw-custom/require-nan-check-after-env-numeric-parse": "warn",
      "gh-aw-custom/require-nan-check-after-split-index-parse": "warn",
      "gh-aw-custom/prefer-structured-clone": "warn",
      "gh-aw-custom/require-fetch-response-body-try-catch": "warn",
      "gh-aw-custom/require-error-code-in-thrown-error": "warn",
      "gh-aw-custom/require-invalid-date-check-before-compare": "warn",
      "gh-aw-custom/require-sync-exec-timeout": "warn",
      "gh-aw-custom/no-empty-catch-block": "warn",
      "gh-aw-custom/require-lastindex-reset-before-global-exec-loop": "warn",
      "gh-aw-custom/require-page-counter-increment-in-while-true-loop": "warn",
      "gh-aw-custom/no-math-minmax-array-spread": "warn",
      "gh-aw-custom/require-error-code-for-github-api-throw": "warn",
      "gh-aw-custom/require-http-response-error-listener": "error",
      "gh-aw-custom/no-string-fallback-for-non-string-message": "warn",
      "gh-aw-custom/require-getexecoutput-exitcode-check": "warn",
      "gh-aw-custom/prefer-actions-exec-over-child-process": "warn",
      "gh-aw-custom/no-misplaced-error-code-definition": "warn",
    },
  },
  {
    files: ["**/*.test.cjs", "**/*.test.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
  },
];
